# Worldwide Environmental Health and Mental Health

## Part 2
## Further Data Wrangling & Exploratory Data Analysis

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Micronutrient Status Data

In [255]:
#micronutrient status
df114 = pd.read_csv('WHO/VMNISIndicator_25-Hydroxyvitamin D_30102021.csv')
df115 = pd.read_csv('WHO/VMNISIndicator_Beta-carotene_30102021.csv')
df116 = pd.read_csv('WHO/VMNISIndicator_Calcium (plasma or serum)_30102021.csv')
df117 = pd.read_csv('WHO/VMNISIndicator_Copper (plasma or serum)_30102021.csv')
df118 = pd.read_csv('WHO/VMNISIndicator_Erythocyte glutamate-oxaloacetate transaminase (EGOT)_30102021.csv')
df119 = pd.read_csv('WHO/VMNISIndicator_Erythrocyte glutathione reductase activity coefficient (EGRAC)_30102021.csv')
df120 = pd.read_csv('WHO/VMNISIndicator_Erythrocyte transketolase activity coefficient (ETKAC)_30102021.csv')
df121 = pd.read_csv('WHO/VMNISIndicator_Ferritin_30102021.csv')
df122 = pd.read_csv('WHO/VMNISIndicator_Folate (plasma or serum)_30102021.csv')
df123 = pd.read_csv('WHO/VMNISIndicator_Folate (red blood cell)_30102021.csv')
df124 = pd.read_csv('WHO/VMNISIndicator_Goitre by ultrasound_30102021.csv')
df125 = pd.read_csv('WHO/VMNISIndicator_Haemoglobin_30102021.csv')
df126 = pd.read_csv('WHO/VMNISIndicator_Homocysteine_30102021.csv')
df127 = pd.read_csv('WHO/VMNISIndicator_Iodine_30102021.csv')
df128 = pd.read_csv('WHO/VMNISIndicator_Iron (serum or plasma)_30102021.csv')
df129 = pd.read_csv('WHO/VMNISIndicator_Iron deficiency anaemia_30102021.csv')
df130 = pd.read_csv('WHO/VMNISIndicator_Magnesium_30102021.csv')
df131 = pd.read_csv('WHO/VMNISIndicator_Mean corpuscular volume (MCV)_30102021.csv')
df132 = pd.read_csv('WHO/VMNISIndicator_Retinol binding protein_30102021.csv')
df133 = pd.read_csv('WHO/VMNISIndicator_Selenium (plama or serum)_30102021.csv')
df134 = pd.read_csv('WHO/VMNISIndicator_Thyroid stimulating hormone (TSH)_30102021.csv')
df135 = pd.read_csv('WHO/VMNISIndicator_Vitamin B12_30102021.csv')
df136 = pd.read_csv('WHO/VMNISIndicator_Vitamin C_30102021.csv')
df137 = pd.read_csv('WHO/VMNISIndicator_Vitamin E (alpha-tocopherol)_30102021.csv')
df138 = pd.read_csv('WHO/VMNISIndicator_Vitamin E (gamma-tocopherol)_30102021.csv')
df139 = pd.read_csv('WHO/VMNISIndicator_Xerophthalmia_30102021.csv')
df140 = pd.read_csv('WHO/VMNISIndicator_Zinc (plasma or serum)_30102021.csv')

### Exploring Completeness of Available Micronutrient Status Data

In [256]:
df114.info()
df114.head().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 51 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Indicator.                85 non-null     object
 1   CountryCode               85 non-null     object
 2   Country                   85 non-null     object
 3   Representativeness.       85 non-null     object
 4   Representativeness name   0 non-null      float64
 5   Area covered              85 non-null     object
 6   Date                      85 non-null     int64
 7   Begin month               79 non-null     float64
 8   Begin year                85 non-null     int64
 9   End month                 79 non-null     float64
 10  End year                  85 non-null     int64
 11  Population                85 non-null     object
 12  Gender                    85 non-null     object
 13  Age unit                  85 non-null     object
 14  Age from                  85 non-null     int64
 15  Age to                    72 non-null     float64
 16  Sample size               62 non-null     float64
 17  Indicator unit            65 non-null     object
 18  Mean                      57 non-null     float64
 19  Geo mean                  0 non-null      float64
 20  Median                    52 non-null     float64
 21  SD                        14 non-null     float64
 22  SE                        2 non-null      float64
 23  L95CI                     30 non-null     float64
 24  U95CI                     30 non-null     float64
 25  Deficiency cut-off        57 non-null     object
 26  Deficiency prevalence     57 non-null     float64
 27  Insufficiency cut-off     50 non-null     object
 28  Insufficiency prevalence  50 non-null     float64
 29  Sample collection method  85 non-null     object
 30  Sample type               85 non-null     object
 31  Fasting                   85 non-null     object
 32  Method of analysis        85 non-null     object
 33  General data comments     70 non-null     object
 34  Indicator comments        85 non-null     object
 35  Survey methodology        85 non-null     object
 36  Season                    85 non-null     object
 37  Old Reference no# 1       14 non-null     float64
 38  Reference no# 1           85 non-null     int64
 39  Reference 1               85 non-null     object
 40  Link to reference 1       85 non-null     object
 41  Old Reference no# 2       5 non-null      float64
 42  Reference no# 2           76 non-null     float64
 43  Reference 2               76 non-null     object
 44  Link to reference 2       76 non-null     object
 45  Old Reference no# 3       0 non-null      float64
 46  Reference no# 3           76 non-null     float64
 47  Reference 3               76 non-null     object
 48  Link to reference 3       64 non-null     object
 49  SurveyId                  85 non-null     int64
 50  Survey status             85 non-null     object
dtypes: float64(19), int64(6), object(26)
memory usage: 34.0+ KB

,0,1,2,3,4
Indicator.,25-Hydroxyvitamin D,25-Hydroxyvitamin D,25-Hydroxyvitamin D,25-Hydroxyvitamin D,25-Hydroxyvitamin D
CountryCode,AUS,AUS,AUS,AUS,AUS
Country,Australia,Australia,Australia,Australia,Australia
Representativeness.,national,national,national,national,national
Representativeness name,NaN,NaN,NaN,NaN,NaN
Area covered,both urban and rural,both urban and rural,both urban and rural,both urban and rural,both urban and rural
Date,2012,2012,2012,2012,2012
Begin month,3,3,3,3,3
Begin year,2011,2011,2011,2011,2011
End month,9,9,9,9,9
End year,2012,2012,2012,2012,2012
Population,Adolescents,Adults,Adults,Adults,Adults
Gender,All,All,All,All,All
Age unit,Year,Year,Year,Year,Year
Age from,12,18,18,18,18
Age to,17,NaN,NaN,NaN,NaN
Sample size,839,1506,2410,2416,3232
Indicator unit,nmol/L,NaN,NaN,NaN,NaN
Mean,69,NaN,NaN,NaN,NaN
Geo mean,NaN,NaN,NaN,NaN,NaN
Median,65,NaN,NaN,NaN,NaN
SD,NaN,NaN,NaN,NaN,NaN
SE,NaN,NaN,NaN,NaN,NaN
L95CI,NaN,NaN,NaN,NaN,NaN
U95CI,NaN,NaN,NaN,NaN,NaN
Deficiency cut-off,<30 nmol/L,NaN,NaN,NaN,NaN
Deficiency prevalence,3.1,NaN,NaN,NaN,NaN
Insufficiency cut-off,<50 nmol/L,<50 mnol/L,<50 nmol/L,<50 mnol/L,<50 mnol/L
Insufficiency prevalence,15.4,30.5,14.3,36,16.8
Sample collection method,Venipuncture,Venipuncture,Venipuncture,Venipuncture,Venipuncture
Sample type,Blood serum,Blood serum,Blood serum,Blood serum,Blood serum
Fasting,Casual,Casual,Casual,Casual,Casual
Method of analysis,Liquid chromatography–mass spectrometry (LC-MS),Liquid chromatography–mass spectrometry (LC-MS),Liquid chromatography–mass spectrometry (LC-MS),Liquid chromatography–mass spectrometry (LC-MS),Liquid chromatography–mass spectrometry (LC-MS)
General data comments,Sample size for prevalence as noted above. Sam...,"Spring (September, October, November). Upper b...","Summer (December, January, February). Upper bo...","Winter (June, July, August). Upper bound of ag...","Autumn (March, April, May). Upper bound of age..."
Indicator comments,25-hydroxyvitamin D assessed by liquid chromat...,25-hydroxyvitamin D assessed by liquid chromat...,25-hydroxyvitamin D assessed by liquid chromat...,25-hydroxyvitamin D assessed by liquid chromat...,25-hydroxyvitamin D assessed by liquid chromat...
Survey methodology,The Australian Health Survey is made up of the...,The Australian Health Survey is made up of the...,The Australian Health Survey is made up of the...,The Australian Health Survey is made up of the...,The Australian Health Survey is made up of the...
Season,All seasons,All seasons,All seasons,All seasons,All seasons
Old Reference no# 1,NaN,NaN,NaN,NaN,NaN
Reference no# 1,61,61,61,61,61
Reference 1,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...
Link to reference 1,http://www.abs.gov.au/ausstats/abs@.nsf/Primar...,http://www.abs.gov.au/ausstats/abs@.nsf/Primar...,http://www.abs.gov.au/ausstats/abs@.nsf/Primar...,http://www.abs.gov.au/ausstats/abs@.nsf/Primar...,http://www.abs.gov.au/ausstats/abs@.nsf/Primar...
Old Reference no# 2,NaN,NaN,NaN,NaN,NaN
Reference no# 2,107,107,107,107,107
Reference 2,"Australian Health Survey: user's guide, 2011-1...","Australian Health Survey: user's guide, 2011-1...","Australian Health Survey: user's guide, 2011-1...","Australian Health Survey: user's guide, 2011-1...","Australian Health Survey: user's guide, 2011-1..."
Link to reference 2,http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...
Old Reference no# 3,NaN,NaN,NaN,NaN,NaN
Reference no# 3,176,176,176,176,176
Reference 3,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...
Link to reference 3,http://www.ausstats.abs.gov.au/ausstats/subscr...,http://www.ausstats.abs.gov.au/ausstats/subscr...,http://www.ausstats.abs.gov.au/ausstats/subscr...,http://www.ausstats.abs.gov.au/ausstats/subscr...,http://www.ausstats.abs.gov.au/ausstats/subscr...
SurveyId,10160,10160,10160,10160,10160
Survey status,verified,verified,verified,verified,verified

Checking for missing values:

In [257]:
missing = pd.concat([df114.isnull().sum(), 100 * df114.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                          count           %
Indicator.                    0    0.000000
Link to reference 1           0    0.000000
Reference 1                   0    0.000000
Reference no# 1               0    0.000000
Season                        0    0.000000
Survey methodology            0    0.000000
Indicator comments            0    0.000000
Method of analysis            0    0.000000
Fasting                       0    0.000000
Sample type                   0    0.000000
Sample collection method      0    0.000000
SurveyId                      0    0.000000
Age from                      0    0.000000
Survey status                 0    0.000000
Gender                        0    0.000000
CountryCode                   0    0.000000
Country                       0    0.000000
Representativeness.           0    0.000000
Area covered                  0    0.000000
Date                          0    0.000000
Age unit                      0    0.000000
Begin year                    0    0.000000
End year                      0    0.000000
Population                    0    0.000000
End month                     6    7.058824
Begin month                   6    7.058824
Reference 3                   9   10.588235
Reference no# 3               9   10.588235
Link to reference 2           9   10.588235
Reference 2                   9   10.588235
Reference no# 2               9   10.588235
Age to                       13   15.294118
General data comments        15   17.647059
Indicator unit               20   23.529412
Link to reference 3          21   24.705882
Sample size                  23   27.058824
Deficiency prevalence        28   32.941176
Mean                         28   32.941176
Deficiency cut-off           28   32.941176
Median                       33   38.823529
Insufficiency prevalence     35   41.176471
Insufficiency cut-off        35   41.176471
U95CI                        55   64.705882
L95CI                        55   64.705882
Old Reference no# 1          71   83.529412
SD                           71   83.529412
Old Reference no# 2          80   94.117647
SE                           83   97.647059
Geo mean                     85  100.000000
Old Reference no# 3          85  100.000000
Representativeness name      85  100.000000

In [258]:
df114.Country.unique()

array(['Australia', 'Austria', 'Canada', 'China', 'Germany', 'France',
       'United Kingdom of Great Britain and Northern', 'Ireland'],
      dtype=object)

In [259]:
df114['Begin year'].unique()

array([2011, 2010, 2007, 2009, 1997, 2006, 1994, 2000, 2008])

In [260]:
labels=["Indicator.", "Country", "Date", "Population", "Gender", "Indicator unit", "Deficiency prevalence", "Mean", "Deficiency cut-off", "Median", "Insufficiency prevalence", "Insufficiency cut-off", "U95CI", "L95CI"]
df114=df114[labels]

In [261]:
df114.shape
df114.head(15)

,Indicator.,Country,Date,Population,Gender,Indicator unit,Deficiency prevalence,Mean,Deficiency cut-off,Median,Insufficiency prevalence,Insufficiency cut-off,U95CI,L95CI
0,25-Hydroxyvitamin D,Australia,2012,Adolescents,All,nmol/L,3.1,69.0,<30 nmol/L,65.0,15.4,<50 nmol/L,NaN,NaN
1,25-Hydroxyvitamin D,Australia,2012,Adults,All,NaN,NaN,NaN,NaN,NaN,30.5,<50 mnol/L,NaN,NaN
2,25-Hydroxyvitamin D,Australia,2012,Adults,All,NaN,NaN,NaN,NaN,NaN,14.3,<50 nmol/L,NaN,NaN
3,25-Hydroxyvitamin D,Australia,2012,Adults,All,NaN,NaN,NaN,NaN,NaN,36.0,<50 mnol/L,NaN,NaN
4,25-Hydroxyvitamin D,Australia,2012,Adults,All,NaN,NaN,NaN,NaN,NaN,16.8,<50 mnol/L,NaN,NaN
5,25-Hydroxyvitamin D,Australia,2012,Adults,All,nmol/L,6.5,65.7,<30 nmol/L,66.0,23.5,<50 mnol/L,NaN,NaN
6,25-Hydroxyvitamin D,Australia,2012,Adults,All,nmol/L,11.6,64.2,<30 nmol/L,64.0,31.1,<50 mnol/L,NaN,NaN
7,25-Hydroxyvitamin D,Australia,2012,Adults,All,nmol/L,10.8,62.1,<30 nmol/L,61.0,30.8,<50 mnol/L,NaN,NaN
8,25-Hydroxyvitamin D,Australia,2012,Adults,All,nmol/L,6.9,64.5,<30 nmol/L,65.0,22.9,<50 mnol/L,NaN,NaN
9,25-Hydroxyvitamin D,Australia,2012,Adults,All,nmol/L,4.5,65.8,<30 nmol/L,66.0,21.6,<50 mnol/L,NaN,NaN
10,25-Hydroxyvitamin D,Australia,2012,Adults,All,nmol/L,2.4,68.9,<30 nmol/L,68.0,17.5,<50 mnol/L,NaN,NaN
11,25-Hydroxyvitamin D,Australia,2012,Adults,Female,nmol/L,6.4,66.2,<30 nmol/L,66.0,22.7,<50 mnol/L,NaN,NaN
12,25-Hydroxyvitamin D,Australia,2012,Elderly,All,nmol/L,2.4,69.8,<30 nmol/L,69.0,15.4,<50 mnol/L,NaN,NaN
13,25-Hydroxyvitamin D,Australia,2012,Elderly,All,nmol/L,3.9,68.6,<30 nmol/L,68.0,20.2,<50 mnol/L,NaN,NaN
14,25-Hydroxyvitamin D,Australia,2012,Men,Male,nmol/L,6.5,65.2,<30 nmol/L,65.0,24.2,<50 mnol/L,NaN,NaN

In [262]:
(df114["Country"] + ", " + df114["Population"]).value_counts()

Australia, Adults                                        11
United Kingdom of Great Britain and Northern, Elderly     9
Ireland, Adults                                           8
Canada, Elderly                                           6
China, Adolescents                                        6
Canada, Adolescents                                       6
United Kingdom of Great Britain and Northern, Men         5
Canada, Adults                                            4
Austria, Adolescents                                      4
Austria, Men                                              4
Canada, Men                                               4
France, Men                                               3
Austria, Women                                            2
France, Women                                             2
Austria, Elderly                                          2
France, Adults                                            2
Germany, Adults                                           2
Australia, Elderly                                        2
Australia, Men                                            1
Australia, Adolescents                                    1
Canada, Women                                             1
dtype: int64

In [263]:
df114.Country.value_counts()

Canada                                          21
Australia                                       15
United Kingdom of Great Britain and Northern    14
Austria                                         12
Ireland                                          8
France                                           7
China                                            6
Germany                                          2
Name: Country, dtype: int64

In [264]:
df115.info()
df115.head().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 49 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Indicator.                32 non-null     object
 1   CountryCode               32 non-null     object
 2   Country                   32 non-null     object
 3   Representativeness.       32 non-null     object
 4   Representativeness name   0 non-null      float64
 5   Area covered              32 non-null     object
 6   Date                      32 non-null     int64
 7   Begin month               32 non-null     int64
 8   Begin year                32 non-null     int64
 9   End month                 32 non-null     int64
 10  End year                  32 non-null     int64
 11  Population                32 non-null     object
 12  Gender                    32 non-null     object
 13  Age unit                  32 non-null     object
 14  Age from                  32 non-null     int64
 15  Age to                    27 non-null     float64
 16  Sample size               24 non-null     float64
 17  Indicator unit            32 non-null     object
 18  Mean                      26 non-null     float64
 19  Geo mean                  0 non-null      float64
 20  Median                    20 non-null     float64
 21  SD                        14 non-null     float64
 22  SE                        0 non-null      float64
 23  L95CI                     16 non-null     float64
 24  U95CI                     16 non-null     float64
 25  Deficiency cut-off        18 non-null     object
 26  Deficiency prevalence     18 non-null     float64
 27  Sample collection method  32 non-null     object
 28  Sample type               32 non-null     object
 29  Fasting                   32 non-null     object
 30  Method of analysis        32 non-null     object
 31  General data comments     13 non-null     object
 32  Indicator comments        32 non-null     object
 33  Survey methodology        32 non-null     object
 34  Season                    32 non-null     object
 35  Old Reference no# 1       20 non-null     float64
 36  Reference no# 1           32 non-null     int64
 37  Reference 1               32 non-null     object
 38  Link to reference 1       32 non-null     object
 39  Old Reference no# 2       11 non-null     float64
 40  Reference no# 2           23 non-null     float64
 41  Reference 2               23 non-null     object
 42  Link to reference 2       17 non-null     object
 43  Old Reference no# 3       6 non-null      float64
 44  Reference no# 3           23 non-null     float64
 45  Reference 3               23 non-null     object
 46  Link to reference 3       11 non-null     object
 47  SurveyId                  32 non-null     int64
 48  Survey status             32 non-null     object
dtypes: float64(16), int64(8), object(25)
memory usage: 12.4+ KB

,0,1,2,3,4
Indicator.,Beta-carotene,Beta-carotene,Beta-carotene,Beta-carotene,Beta-carotene
CountryCode,AUT,AUT,AUT,AUT,AUT
Country,Austria,Austria,Austria,Austria,Austria
Representativeness.,national,national,national,national,national
Representativeness name,NaN,NaN,NaN,NaN,NaN
Area covered,both urban and rural,both urban and rural,both urban and rural,both urban and rural,both urban and rural
Date,2012,2012,2012,2012,2012
Begin month,8,8,8,8,8
Begin year,2010,2010,2010,2010,2010
End month,2,2,2,2,2
End year,2012,2012,2012,2012,2012
Population,Adolescents,Adolescents,Adolescents,Adolescents,Elderly
Gender,Female,Female,Male,Male,Female
Age unit,Year,Year,Year,Year,Year
Age from,10,13,10,13,65
Age to,12,14,12,14,80
Sample size,NaN,NaN,NaN,NaN,100
Indicator unit,µmol/L,µmol/L,µmol/L,µmol/L,µmol/L
Mean,0.56,0.29,0.48,0.33,0.4
Geo mean,NaN,NaN,NaN,NaN,NaN
Median,NaN,NaN,NaN,NaN,NaN
SD,NaN,NaN,NaN,NaN,NaN
SE,NaN,NaN,NaN,NaN,NaN
L95CI,0.46,0.22,0.39,0.22,0.34
U95CI,0.65,0.35,0.57,0.35,0.45
Deficiency cut-off,NaN,NaN,NaN,NaN,<0.373 µmol/L
Deficiency prevalence,NaN,NaN,NaN,NaN,55.9
Sample collection method,Venipuncture,Venipuncture,Venipuncture,Venipuncture,Venipuncture
Sample type,Blood plasma,Blood plasma,Blood plasma,Blood plasma,Blood plasma
Fasting,Not known,Not known,Not known,Not known,Not known
Method of analysis,High performance liquid chromatography (HPLC),High performance liquid chromatography (HPLC),High performance liquid chromatography (HPLC),High performance liquid chromatography (HPLC),High performance liquid chromatography (HPLC)
General data comments,NaN,NaN,NaN,NaN,Other cut off and prevalence reported: 0.373-0...
Indicator comments,Plasma B-carotene assessed by reversed phased ...,Plasma B-carotene assessed by reversed phased ...,Plasma B-carotene assessed by reversed phased ...,Plasma B-carotene assessed by reversed phased ...,Plasma B-carotene assessed by reversed phased ...
Survey methodology,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...
Season,Not specified,Not specified,Not specified,Not specified,Not specified
Old Reference no# 1,NaN,NaN,NaN,NaN,NaN
Reference no# 1,963,963,963,963,963
Reference 1,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...
Link to reference 1,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...
Old Reference no# 2,NaN,NaN,NaN,NaN,NaN
Reference no# 2,1244,1244,1244,1244,1244
Reference 2,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene..."
Link to reference 2,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...
Old Reference no# 3,NaN,NaN,NaN,NaN,NaN
Reference no# 3,1399,1399,1399,1399,1399
Reference 3,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H..."
Link to reference 3,NaN,NaN,NaN,NaN,NaN
SurveyId,10872,10872,10872,10872,10872
Survey status,verified,verified,verified,verified,verified

Checking for missing values:

In [265]:
missing = pd.concat([df115.isnull().sum(), 100 * df115.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                          count        %
Indicator.                    0    0.000
Link to reference 1           0    0.000
Reference 1                   0    0.000
Reference no# 1               0    0.000
Season                        0    0.000
Survey methodology            0    0.000
Indicator comments            0    0.000
Method of analysis            0    0.000
Fasting                       0    0.000
Sample type                   0    0.000
Sample collection method      0    0.000
SurveyId                      0    0.000
Indicator unit                0    0.000
Age from                      0    0.000
Survey status                 0    0.000
CountryCode                   0    0.000
Representativeness.           0    0.000
Gender                        0    0.000
Area covered                  0    0.000
Date                          0    0.000
Age unit                      0    0.000
Begin month                   0    0.000
Begin year                    0    0.000
End month                     0    0.000
Population                    0    0.000
End year                      0    0.000
Country                       0    0.000
Age to                        5   15.625
Mean                          6   18.750
Sample size                   8   25.000
Reference 2                   9   28.125
Reference no# 3               9   28.125
Reference 3                   9   28.125
Reference no# 2               9   28.125
Median                       12   37.500
Old Reference no# 1          12   37.500
Deficiency cut-off           14   43.750
Deficiency prevalence        14   43.750
Link to reference 2          15   46.875
U95CI                        16   50.000
L95CI                        16   50.000
SD                           18   56.250
General data comments        19   59.375
Link to reference 3          21   65.625
Old Reference no# 2          21   65.625
Old Reference no# 3          26   81.250
Representativeness name      32  100.000
SE                           32  100.000
Geo mean                     32  100.000

In [266]:
df115.Country.unique()

array(['Austria', 'France',
       'United Kingdom of Great Britain and Northern'], dtype=object)

In [267]:
df115['Begin year'].unique()

array([2010, 1994, 2000])

This indicator is also available for very few countries and years.

In [268]:
df116.info()
df116.head().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 49 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Indicator.                23 non-null     object
 1   CountryCode               23 non-null     object
 2   Country                   23 non-null     object
 3   Representativeness.       23 non-null     object
 4   Representativeness name   0 non-null      float64
 5   Area covered              23 non-null     object
 6   Date                      23 non-null     int64
 7   Begin month               23 non-null     int64
 8   Begin year                23 non-null     int64
 9   End month                 23 non-null     int64
 10  End year                  23 non-null     int64
 11  Population                23 non-null     object
 12  Gender                    23 non-null     object
 13  Age unit                  23 non-null     object
 14  Age from                  23 non-null     int64
 15  Age to                    23 non-null     int64
 16  Sample size               4 non-null      float64
 17  Indicator unit            21 non-null     object
 18  Mean                      21 non-null     float64
 19  Geo mean                  0 non-null      float64
 20  Median                    11 non-null     float64
 21  SD                        0 non-null      float64
 22  SE                        0 non-null      float64
 23  L95CI                     21 non-null     float64
 24  U95CI                     21 non-null     float64
 25  Deficiency cut-off        2 non-null      object
 26  Deficiency prevalence     2 non-null      float64
 27  Insufficiency cut-off     0 non-null      float64
 28  Insufficiency prevalence  0 non-null      float64
 29  Sample collection method  23 non-null     object
 30  Sample type               23 non-null     object
 31  Method of analysis        23 non-null     object
 32  General data comments     11 non-null     object
 33  Indicator comments        23 non-null     object
 34  Survey methodology        23 non-null     object
 35  Old Reference no# 1       0 non-null      float64
 36  Reference no# 1           23 non-null     int64
 37  Reference 1               23 non-null     object
 38  Link to reference 1       23 non-null     object
 39  Old Reference no# 2       0 non-null      float64
 40  Reference no# 2           23 non-null     int64
 41  Reference 2               23 non-null     object
 42  Link to reference 2       23 non-null     object
 43  Old Reference no# 3       0 non-null      float64
 44  Reference no# 3           23 non-null     int64
 45  Reference 3               23 non-null     object
 46  Link to reference 3       11 non-null     object
 47  SurveyId                  23 non-null     int64
 48  Survey status             23 non-null     object
dtypes: float64(15), int64(11), object(23)
memory usage: 8.9+ KB

,0,1,2,3,4
Indicator.,Calcium (plasma or serum),Calcium (plasma or serum),Calcium (plasma or serum),Calcium (plasma or serum),Calcium (plasma or serum)
CountryCode,AUT,AUT,AUT,AUT,AUT
Country,Austria,Austria,Austria,Austria,Austria
Representativeness.,national,national,national,national,national
Representativeness name,NaN,NaN,NaN,NaN,NaN
Area covered,both urban and rural,both urban and rural,both urban and rural,both urban and rural,both urban and rural
Date,2012,2012,2012,2012,2012
Begin month,8,8,8,8,8
Begin year,2010,2010,2010,2010,2010
End month,2,2,2,2,2
End year,2012,2012,2012,2012,2012
Population,Adolescents,Adolescents,Adolescents,Adolescents,Elderly
Gender,Female,Female,Male,Male,Female
Age unit,Year,Year,Year,Year,Year
Age from,10,13,10,13,65
Age to,12,14,12,14,80
Sample size,NaN,NaN,NaN,NaN,87
Indicator unit,mmol/L,mmol/L,mmol/L,mmol/L,mmol/L
Mean,2.54,2.53,2.57,2.54,2.42
Geo mean,NaN,NaN,NaN,NaN,NaN
Median,NaN,NaN,NaN,NaN,NaN
SD,NaN,NaN,NaN,NaN,NaN
SE,NaN,NaN,NaN,NaN,NaN
L95CI,2.51,2.47,2.53,2.45,2.38
U95CI,2.58,2.6,2.6,2.62,2.46
Deficiency cut-off,NaN,NaN,NaN,NaN,<2.26 mmol/L
Deficiency prevalence,NaN,NaN,NaN,NaN,19.6
Insufficiency cut-off,NaN,NaN,NaN,NaN,NaN
Insufficiency prevalence,NaN,NaN,NaN,NaN,NaN
Sample collection method,Venipuncture,Venipuncture,Venipuncture,Venipuncture,Venipuncture
Sample type,Blood plasma,Blood plasma,Blood plasma,Blood plasma,Blood plasma
Method of analysis,Other,Other,Other,Other,Other
General data comments,NaN,NaN,NaN,NaN,NaN
Indicator comments,Plasma calcium assessed by photometric detecti...,Plasma calcium assessed by photometric detecti...,Plasma calcium assessed by photometric detecti...,Plasma calcium assessed by photometric detecti...,Plasma calcium assessed by photometric detecti...
Survey methodology,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...
Old Reference no# 1,NaN,NaN,NaN,NaN,NaN
Reference no# 1,963,963,963,963,963
Reference 1,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...
Link to reference 1,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...
Old Reference no# 2,NaN,NaN,NaN,NaN,NaN
Reference no# 2,1244,1244,1244,1244,1244
Reference 2,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene..."
Link to reference 2,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...
Old Reference no# 3,NaN,NaN,NaN,NaN,NaN
Reference no# 3,1399,1399,1399,1399,1399
Reference 3,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H..."
Link to reference 3,NaN,NaN,NaN,NaN,NaN
SurveyId,10872,10872,10872,10872,10872
Survey status,verified,verified,verified,verified,verified

Checking for missing values:

In [269]:
missing = pd.concat([df116.isnull().sum(), 100 * df116.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                          count           %
Indicator.                    0    0.000000
Reference 3                   0    0.000000
Reference no# 3               0    0.000000
Link to reference 2           0    0.000000
Reference 2                   0    0.000000
Reference no# 2               0    0.000000
Link to reference 1           0    0.000000
Reference 1                   0    0.000000
Reference no# 1               0    0.000000
Survey methodology            0    0.000000
Indicator comments            0    0.000000
Method of analysis            0    0.000000
Sample type                   0    0.000000
Sample collection method      0    0.000000
SurveyId                      0    0.000000
Survey status                 0    0.000000
Area covered                  0    0.000000
Age to                        0    0.000000
Population                    0    0.000000
Gender                        0    0.000000
Age unit                      0    0.000000
Begin year                    0    0.000000
Begin month                   0    0.000000
Date                          0    0.000000
End year                      0    0.000000
End month                     0    0.000000
Representativeness.           0    0.000000
Country                       0    0.000000
CountryCode                   0    0.000000
Age from                      0    0.000000
L95CI                         2    8.695652
Mean                          2    8.695652
Indicator unit                2    8.695652
U95CI                         2    8.695652
Link to reference 3          12   52.173913
General data comments        12   52.173913
Median                       12   52.173913
Sample size                  19   82.608696
Deficiency prevalence        21   91.304348
Deficiency cut-off           21   91.304348
Insufficiency prevalence     23  100.000000
Insufficiency cut-off        23  100.000000
Old Reference no# 2          23  100.000000
Representativeness name      23  100.000000
SE                           23  100.000000
Old Reference no# 3          23  100.000000
SD                           23  100.000000
Geo mean                     23  100.000000
Old Reference no# 1          23  100.000000

In [270]:
df116.Country.unique()

array(['Austria', 'Canada'], dtype=object)

In [271]:
df116['Begin year'].unique()

array([2010, 2009])

Also available for few countries and years so will not be used.

In [272]:
df117.info()
df117.head().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 50 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Indicator.                20 non-null     object
 1   CountryCode               20 non-null     object
 2   Country                   20 non-null     object
 3   Representativeness.       20 non-null     object
 4   Representativeness name   0 non-null      float64
 5   Area covered              20 non-null     object
 6   Date                      20 non-null     int64
 7   Begin month               0 non-null      float64
 8   Begin year                9 non-null      float64
 9   End month                 0 non-null      float64
 10  End year                  20 non-null     int64
 11  Population                20 non-null     object
 12  Gender                    20 non-null     object
 13  Age unit                  20 non-null     object
 14  Age from                  20 non-null     int64
 15  Age to                    20 non-null     int64
 16  Sample size               20 non-null     int64
 17  Indicator unit            20 non-null     object
 18  Mean                      11 non-null     float64
 19  Geo mean                  0 non-null      float64
 20  Median                    12 non-null     float64
 21  SD                        11 non-null     float64
 22  SE                        0 non-null      float64
 23  L95CI                     0 non-null      float64
 24  U95CI                     0 non-null      float64
 25  Deficiency cut-off        0 non-null      float64
 26  Deficiency prevalence     0 non-null      float64
 27  Sample collection method  20 non-null     object
 28  Sample type               20 non-null     object
 29  Fasting                   20 non-null     object
 30  Method of analysis        20 non-null     object
 31  Data adjusted for         20 non-null     object
 32  General data comments     9 non-null      object
 33  Indicator comments        20 non-null     object
 34  Survey methodology        20 non-null     object
 35  Season                    20 non-null     object
 36  Old Reference no# 1       0 non-null      float64
 37  Reference no# 1           20 non-null     int64
 38  Reference 1               20 non-null     object
 39  Link to reference 1       20 non-null     object
 40  Old Reference no# 2       0 non-null      float64
 41  Reference no# 2           9 non-null      float64
 42  Reference 2               9 non-null      object
 43  Link to reference 2       9 non-null      object
 44  Old Reference no# 3       0 non-null      float64
 45  Reference no# 3           9 non-null      float64
 46  Reference 3               9 non-null      object
 47  Link to reference 3       9 non-null      object
 48  SurveyId                  20 non-null     int64
 49  Survey status             20 non-null     object
dtypes: float64(18), int64(7), object(25)
memory usage: 7.9+ KB

,0,1,2,3,4
Indicator.,Copper (plasma or serum),Copper (plasma or serum),Copper (plasma or serum),Copper (plasma or serum),Copper (plasma or serum)
CountryCode,CHN,CHN,CHN,CHN,CHN
Country,China,China,China,China,China
Representativeness.,national,national,national,national,national
Representativeness name,NaN,NaN,NaN,NaN,NaN
Area covered,both urban and rural,both urban and rural,both urban and rural,both urban and rural,both urban and rural
Date,2012,2012,2012,2012,2012
Begin month,NaN,NaN,NaN,NaN,NaN
Begin year,2010,2010,2010,2010,2010
End month,NaN,NaN,NaN,NaN,NaN
End year,2012,2012,2012,2012,2012
Population,Pregnant women,Pregnant women,Pregnant women,Pregnant women,Pregnant women
Gender,Female,Female,Female,Female,Female
Age unit,Year,Year,Year,Year,Year
Age from,18,18,18,18,18
Age to,25,44,44,44,44
Sample size,528,291,491,555,1400
Indicator unit,µmol/L,µmol/L,µmol/L,µmol/L,µmol/L
Mean,NaN,NaN,NaN,NaN,NaN
Geo mean,NaN,NaN,NaN,NaN,NaN
Median,30.77,24.73,32.69,31.18,30.69
SD,NaN,NaN,NaN,NaN,NaN
SE,NaN,NaN,NaN,NaN,NaN
L95CI,NaN,NaN,NaN,NaN,NaN
U95CI,NaN,NaN,NaN,NaN,NaN
Deficiency cut-off,NaN,NaN,NaN,NaN,NaN
Deficiency prevalence,NaN,NaN,NaN,NaN,NaN
Sample collection method,Venipuncture,Venipuncture,Venipuncture,Venipuncture,Venipuncture
Sample type,Blood serum,Blood serum,Blood serum,Blood serum,Blood serum
Fasting,Fasting/first morning sample,Fasting/first morning sample,Fasting/first morning sample,Fasting/first morning sample,Fasting/first morning sample
Method of analysis,Inductively coupled plasma (ICP),Inductively coupled plasma (ICP),Inductively coupled plasma (ICP),Inductively coupled plasma (ICP),Inductively coupled plasma (ICP)
Data adjusted for,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable
General data comments,Women in all trimesters of pregnancy.,Women in first trimester of pregnancy only.,Women in 3rd trimester of pregnancy only.,Women in 2nd trimester of pregnancy only.,Women in all trimesters of pregnancy.
Indicator comments,Blood samples collected after a fasting period...,Blood samples collected after a fasting period...,Blood samples collected after a fasting period...,Blood samples collected after a fasting period...,Blood samples collected after a fasting period...
Survey methodology,Survey covering civilian non-institutionalized...,Survey covering civilian non-institutionalized...,Survey covering civilian non-institutionalized...,Survey covering civilian non-institutionalized...,Survey covering civilian non-institutionalized...
Season,All seasons,All seasons,All seasons,All seasons,All seasons
Old Reference no# 1,NaN,NaN,NaN,NaN,NaN
Reference no# 1,1106,1106,1106,1106,1106
Reference 1,"Li M, Hu Y, Mao D, Wang R, Chen J, Li W et al....","Li M, Hu Y, Mao D, Wang R, Chen J, Li W et al....","Li M, Hu Y, Mao D, Wang R, Chen J, Li W et al....","Li M, Hu Y, Mao D, Wang R, Chen J, Li W et al....","Li M, Hu Y, Mao D, Wang R, Chen J, Li W et al...."
Link to reference 1,www.mdpi.com/journal/nutrients,www.mdpi.com/journal/nutrients,www.mdpi.com/journal/nutrients,www.mdpi.com/journal/nutrients,www.mdpi.com/journal/nutrients
Old Reference no# 2,NaN,NaN,NaN,NaN,NaN
Reference no# 2,1107,1107,1107,1107,1107
Reference 2,"Hu Y, Chen J, Wang R, Li M, Yun C, Li W, Yang ...","Hu Y, Chen J, Wang R, Li M, Yun C, Li W, Yang ...","Hu Y, Chen J, Wang R, Li M, Yun C, Li W, Yang ...","Hu Y, Chen J, Wang R, Li M, Yun C, Li W, Yang ...","Hu Y, Chen J, Wang R, Li M, Yun C, Li W, Yang ..."
Link to reference 2,www.mdpi.com/journal/nutrients,www.mdpi.com/journal/nutrients,www.mdpi.com/journal/nutrients,www.mdpi.com/journal/nutrients,www.mdpi.com/journal/nutrients
Old Reference no# 3,NaN,NaN,NaN,NaN,NaN
Reference no# 3,1112,1112,1112,1112,1112
Reference 3,"Hu YC, Chen J, Li M, Wang R, Li WD, Yang YH et...","Hu YC, Chen J, Li M, Wang R, Li WD, Yang YH et...","Hu YC, Chen J, Li M, Wang R, Li WD, Yang YH et...","Hu YC, Chen J, Li M, Wang R, Li WD, Yang YH et...","Hu YC, Chen J, Li M, Wang R, Li WD, Yang YH et..."
Link to reference 3,http://zhyfyxzz.yiigle.com/CN112150201702/9445...,http://zhyfyxzz.yiigle.com/CN112150201702/9445...,http://zhyfyxzz.yiigle.com/CN112150201702/9445...,http://zhyfyxzz.yiigle.com/CN112150201702/9445...,http://zhyfyxzz.yiigle.com/CN112150201702/9445...
SurveyId,10961,10961,10961,10961,10961
Survey status,verified,verified,verified,verified,verified

Checking for missing values:

In [273]:
missing = pd.concat([df117.isnull().sum(), 100 * df117.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                          count      %
Indicator.                    0    0.0
Link to reference 1           0    0.0
Reference 1                   0    0.0
Reference no# 1               0    0.0
Season                        0    0.0
Survey methodology            0    0.0
Indicator comments            0    0.0
Data adjusted for             0    0.0
Method of analysis            0    0.0
Fasting                       0    0.0
Sample type                   0    0.0
Sample collection method      0    0.0
SurveyId                      0    0.0
Indicator unit                0    0.0
Sample size                   0    0.0
Survey status                 0    0.0
Age from                      0    0.0
Date                          0    0.0
Age to                        0    0.0
Country                       0    0.0
CountryCode                   0    0.0
End year                      0    0.0
Population                    0    0.0
Area covered                  0    0.0
Representativeness.           0    0.0
Age unit                      0    0.0
Gender                        0    0.0
Median                        8   40.0
SD                            9   45.0
Mean                          9   45.0
Reference no# 3              11   55.0
Reference 2                  11   55.0
Reference 3                  11   55.0
Reference no# 2              11   55.0
Link to reference 3          11   55.0
Link to reference 2          11   55.0
General data comments        11   55.0
Begin year                   11   55.0
Representativeness name      20  100.0
Begin month                  20  100.0
Old Reference no# 2          20  100.0
End month                    20  100.0
Deficiency prevalence        20  100.0
Deficiency cut-off           20  100.0
Old Reference no# 3          20  100.0
L95CI                        20  100.0
SE                           20  100.0
Geo mean                     20  100.0
Old Reference no# 1          20  100.0
U95CI                        20  100.0

In [274]:
df117.Country.unique()

array(['China', 'Kuwait'], dtype=object)

In [275]:
df117['Begin year'].unique()

array([2010.,   nan])

Due to lack of data, this indicator will not be used either.

In [276]:
df118.info()
df118.head().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 51 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Indicator.                      13 non-null     object
 1   CountryCode                     13 non-null     object
 2   Country                         13 non-null     object
 3   Representativeness.             13 non-null     object
 4   Representativeness name         0 non-null      float64
 5   Area covered                    13 non-null     object
 6   Date                            13 non-null     int64
 7   Begin month                     13 non-null     int64
 8   Begin year                      13 non-null     int64
 9   End month                       13 non-null     int64
 10  End year                        13 non-null     int64
 11  Population                      13 non-null     object
 12  Gender                          13 non-null     object
 13  Age unit                        13 non-null     object
 14  Age from                        13 non-null     int64
 15  Age to                          13 non-null     int64
 16  Sample size                     5 non-null      float64
 17  Indicator unit                  0 non-null      float64
 18  Mean                            10 non-null     float64
 19  Geo mean                        0 non-null      float64
 20  Median                          0 non-null      float64
 21  SD                              0 non-null      float64
 22  SE                              0 non-null      float64
 23  L95CI                           10 non-null     float64
 24  U95CI                           10 non-null     float64
 25  Deficiency threshold            5 non-null      object
 26  Prevalence of deficiency        5 non-null      float64
 27  Marginal deficiency range       0 non-null      float64
 28  Marginal deficiency prevalence  0 non-null      float64
 29  Sample collection method        13 non-null     object
 30  Sample type                     13 non-null     object
 31  Fasting                         13 non-null     object
 32  Method of analysis              13 non-null     object
 33  General data comments           0 non-null      float64
 34  Indicator comments              13 non-null     object
 35  Survey methodology              13 non-null     object
 36  Season                          13 non-null     object
 37  Old Reference no# 1             0 non-null      float64
 38  Reference no# 1                 13 non-null     int64
 39  Reference 1                     13 non-null     object
 40  Link to reference 1             13 non-null     object
 41  Old Reference no# 2             0 non-null      float64
 42  Reference no# 2                 13 non-null     int64
 43  Reference 2                     13 non-null     object
 44  Link to reference 2             13 non-null     object
 45  Old Reference no# 3             0 non-null      float64
 46  Reference no# 3                 13 non-null     int64
 47  Reference 3                     13 non-null     object
 48  Link to reference 3             0 non-null      float64
 49  SurveyId                        13 non-null     int64
 50  Survey status                   13 non-null     object
dtypes: float64(18), int64(11), object(22)
memory usage: 5.3+ KB

,0,1,2,3,4
Indicator.,Erythocyte glutamate-oxaloacetate transaminase...,Erythocyte glutamate-oxaloacetate transaminase...,Erythocyte glutamate-oxaloacetate transaminase...,Erythocyte glutamate-oxaloacetate transaminase...,Erythocyte glutamate-oxaloacetate transaminase...
CountryCode,AUT,AUT,AUT,AUT,AUT
Country,Austria,Austria,Austria,Austria,Austria
Representativeness.,national,national,national,national,national
Representativeness name,NaN,NaN,NaN,NaN,NaN
Area covered,both urban and rural,both urban and rural,both urban and rural,both urban and rural,both urban and rural
Date,2012,2012,2012,2012,2012
Begin month,8,8,8,8,8
Begin year,2010,2010,2010,2010,2010
End month,2,2,2,2,2
End year,2012,2012,2012,2012,2012
Population,Adolescents,Adolescents,Adolescents,Adolescents,Elderly
Gender,Female,Female,Male,Male,All
Age unit,Year,Year,Year,Year,Year
Age from,10,13,10,13,65
Age to,12,14,12,14,80
Sample size,NaN,NaN,NaN,NaN,192
Indicator unit,NaN,NaN,NaN,NaN,NaN
Mean,1.8,1.79,1.85,1.79,NaN
Geo mean,NaN,NaN,NaN,NaN,NaN
Median,NaN,NaN,NaN,NaN,NaN
SD,NaN,NaN,NaN,NaN,NaN
SE,NaN,NaN,NaN,NaN,NaN
L95CI,1.75,1.68,1.79,1.69,NaN
U95CI,1.85,1.89,1.9,1.89,NaN
Deficiency threshold,NaN,NaN,NaN,NaN,≥1.85
Prevalence of deficiency,NaN,NaN,NaN,NaN,23.8
Marginal deficiency range,NaN,NaN,NaN,NaN,NaN
Marginal deficiency prevalence,NaN,NaN,NaN,NaN,NaN
Sample collection method,Venipuncture,Venipuncture,Venipuncture,Venipuncture,Venipuncture
Sample type,Red blood cell,Red blood cell,Red blood cell,Red blood cell,Red blood cell
Fasting,Not known,Not known,Not known,Not known,Not known
Method of analysis,Erythrocyte enzyme activation test,Erythrocyte enzyme activation test,Erythrocyte enzyme activation test,Erythrocyte enzyme activation test,Erythrocyte enzyme activation test
General data comments,NaN,NaN,NaN,NaN,NaN
Indicator comments,Activation of erythrocyte glutamate-oxaloaceta...,Activation of erythrocyte glutamate-oxaloaceta...,Activation of erythrocyte glutamate-oxaloaceta...,Activation of erythrocyte glutamate-oxaloaceta...,Activation of erythrocyte glutamate-oxaloaceta...
Survey methodology,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...
Season,Not specified,Not specified,Not specified,Not specified,Not specified
Old Reference no# 1,NaN,NaN,NaN,NaN,NaN
Reference no# 1,963,963,963,963,963
Reference 1,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...
Link to reference 1,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...
Old Reference no# 2,NaN,NaN,NaN,NaN,NaN
Reference no# 2,1244,1244,1244,1244,1244
Reference 2,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene..."
Link to reference 2,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...
Old Reference no# 3,NaN,NaN,NaN,NaN,NaN
Reference no# 3,1399,1399,1399,1399,1399
Reference 3,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H..."
Link to reference 3,NaN,NaN,NaN,NaN,NaN
SurveyId,10872,10872,10872,10872,10872
Survey status,verified,verified,verified,verified,verified

Checking for missing values:

In [277]:
missing = pd.concat([df118.isnull().sum(), 100 * df118.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                                count           %
Indicator.                          0    0.000000
Sample type                         0    0.000000
Fasting                             0    0.000000
Method of analysis                  0    0.000000
Indicator comments                  0    0.000000
Survey methodology                  0    0.000000
Season                              0    0.000000
Sample collection method            0    0.000000
Reference no# 1                     0    0.000000
Link to reference 1                 0    0.000000
Reference no# 2                     0    0.000000
Reference 2                         0    0.000000
Link to reference 2                 0    0.000000
Reference no# 3                     0    0.000000
Reference 3                         0    0.000000
Reference 1                         0    0.000000
SurveyId                            0    0.000000
Survey status                       0    0.000000
Population                          0    0.000000
CountryCode                         0    0.000000
Country                             0    0.000000
Representativeness.                 0    0.000000
Area covered                        0    0.000000
Date                                0    0.000000
Begin month                         0    0.000000
Begin year                          0    0.000000
End month                           0    0.000000
End year                            0    0.000000
Gender                              0    0.000000
Age to                              0    0.000000
Age from                            0    0.000000
Age unit                            0    0.000000
Mean                                3   23.076923
U95CI                               3   23.076923
L95CI                               3   23.076923
Deficiency threshold                8   61.538462
Prevalence of deficiency            8   61.538462
Sample size                         8   61.538462
Link to reference 3                13  100.000000
Geo mean                           13  100.000000
Median                             13  100.000000
Old Reference no# 3                13  100.000000
SD                                 13  100.000000
General data comments              13  100.000000
SE                                 13  100.000000
Marginal deficiency prevalence     13  100.000000
Old Reference no# 1                13  100.000000
Marginal deficiency range          13  100.000000
Indicator unit                     13  100.000000
Representativeness name            13  100.000000
Old Reference no# 2                13  100.000000

In [278]:
df118.Country.unique()

array(['Austria'], dtype=object)

This data is available for only one country so this indicator will not be used.

In [279]:
df119.info()
df119.head().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 51 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Indicator.                      27 non-null     object
 1   CountryCode                     27 non-null     object
 2   Country                         27 non-null     object
 3   Representativeness.             27 non-null     object
 4   Representativeness name         0 non-null      float64
 5   Area covered                    27 non-null     object
 6   Date                            27 non-null     int64
 7   Begin month                     27 non-null     int64
 8   Begin year                      27 non-null     int64
 9   End month                       27 non-null     int64
 10  End year                        27 non-null     int64
 11  Population                      27 non-null     object
 12  Gender                          27 non-null     object
 13  Age unit                        27 non-null     object
 14  Age from                        27 non-null     int64
 15  Age to                          22 non-null     float64
 16  Sample size                     14 non-null     float64
 17  Indicator unit                  0 non-null      float64
 18  Mean                            24 non-null     float64
 19  Geo mean                        0 non-null      float64
 20  Median                          14 non-null     float64
 21  SD                              14 non-null     float64
 22  SE                              0 non-null      float64
 23  L95CI                           10 non-null     float64
 24  U95CI                           10 non-null     float64
 25  Deficiency threshold            17 non-null     object
 26  Prevalence of deficiency        17 non-null     float64
 27  Marginal deficiency range       0 non-null      float64
 28  Marginal deficiency prevalence  0 non-null      float64
 29  Sample collection method        27 non-null     object
 30  Sample type                     27 non-null     object
 31  Fasting                         27 non-null     object
 32  Method of analysis              27 non-null     object
 33  General data comments           14 non-null     object
 34  Indicator comments              27 non-null     object
 35  Survey methodology              27 non-null     object
 36  Season                          27 non-null     object
 37  Old Reference no# 1             14 non-null     float64
 38  Reference no# 1                 27 non-null     int64
 39  Reference 1                     27 non-null     object
 40  Link to reference 1             27 non-null     object
 41  Old Reference no# 2             5 non-null      float64
 42  Reference no# 2                 18 non-null     float64
 43  Reference 2                     18 non-null     object
 44  Link to reference 2             18 non-null     object
 45  Old Reference no# 3             0 non-null      float64
 46  Reference no# 3                 18 non-null     float64
 47  Reference 3                     18 non-null     object
 48  Link to reference 3             5 non-null      object
 49  SurveyId                        27 non-null     int64
 50  Survey status                   27 non-null     object
dtypes: float64(19), int64(8), object(24)
memory usage: 10.9+ KB

,0,1,2,3,4
Indicator.,Erythrocyte glutathione reductase activity coe...,Erythrocyte glutathione reductase activity coe...,Erythrocyte glutathione reductase activity coe...,Erythrocyte glutathione reductase activity coe...,Erythrocyte glutathione reductase activity coe...
CountryCode,AUT,AUT,AUT,AUT,AUT
Country,Austria,Austria,Austria,Austria,Austria
Representativeness.,national,national,national,national,national
Representativeness name,NaN,NaN,NaN,NaN,NaN
Area covered,both urban and rural,both urban and rural,both urban and rural,both urban and rural,both urban and rural
Date,2012,2012,2012,2012,2012
Begin month,8,8,8,8,8
Begin year,2010,2010,2010,2010,2010
End month,2,2,2,2,2
End year,2012,2012,2012,2012,2012
Population,Adolescents,Adolescents,Adolescents,Adolescents,Elderly
Gender,Female,Female,Male,Male,All
Age unit,Year,Year,Year,Year,Year
Age from,10,13,10,13,65
Age to,12,14,12,14,80
Sample size,NaN,NaN,NaN,NaN,NaN
Indicator unit,NaN,NaN,NaN,NaN,NaN
Mean,1.3,1.35,1.26,1.32,NaN
Geo mean,NaN,NaN,NaN,NaN,NaN
Median,NaN,NaN,NaN,NaN,NaN
SD,NaN,NaN,NaN,NaN,NaN
SE,NaN,NaN,NaN,NaN,NaN
L95CI,1.28,1.29,1.24,1.25,NaN
U95CI,1.32,1.41,1.29,1.38,NaN
Deficiency threshold,NaN,NaN,NaN,NaN,≥1.4
Prevalence of deficiency,NaN,NaN,NaN,NaN,6.6
Marginal deficiency range,NaN,NaN,NaN,NaN,NaN
Marginal deficiency prevalence,NaN,NaN,NaN,NaN,NaN
Sample collection method,Venipuncture,Venipuncture,Venipuncture,Venipuncture,Venipuncture
Sample type,Red blood cell,Red blood cell,Red blood cell,Red blood cell,Red blood cell
Fasting,Not known,Not known,Not known,Not known,Not known
Method of analysis,Erythrocyte enzyme activation test,Erythrocyte enzyme activation test,Erythrocyte enzyme activation test,Erythrocyte enzyme activation test,Erythrocyte enzyme activation test
General data comments,NaN,NaN,NaN,NaN,NaN
Indicator comments,Erythrocyte glutathione reductase activity ass...,Erythrocyte glutathione reductase activity ass...,Erythrocyte glutathione reductase activity ass...,Erythrocyte glutathione reductase activity ass...,Erythrocyte glutathione reductase activity ass...
Survey methodology,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...
Season,Not specified,Not specified,Not specified,Not specified,Not specified
Old Reference no# 1,NaN,NaN,NaN,NaN,NaN
Reference no# 1,963,963,963,963,963
Reference 1,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...
Link to reference 1,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...
Old Reference no# 2,NaN,NaN,NaN,NaN,NaN
Reference no# 2,1244,1244,1244,1244,1244
Reference 2,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene..."
Link to reference 2,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...
Old Reference no# 3,NaN,NaN,NaN,NaN,NaN
Reference no# 3,1399,1399,1399,1399,1399
Reference 3,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H..."
Link to reference 3,NaN,NaN,NaN,NaN,NaN
SurveyId,10872,10872,10872,10872,10872
Survey status,verified,verified,verified,verified,verified

Checking for missing values:

In [280]:
missing = pd.concat([df119.isnull().sum(), 100 * df119.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                                count           %
Indicator.                          0    0.000000
Link to reference 1                 0    0.000000
Reference 1                         0    0.000000
Reference no# 1                     0    0.000000
Season                              0    0.000000
Survey methodology                  0    0.000000
Indicator comments                  0    0.000000
Method of analysis                  0    0.000000
Fasting                             0    0.000000
Sample type                         0    0.000000
Sample collection method            0    0.000000
SurveyId                            0    0.000000
Age from                            0    0.000000
Survey status                       0    0.000000
Gender                              0    0.000000
CountryCode                         0    0.000000
Country                             0    0.000000
Representativeness.                 0    0.000000
Area covered                        0    0.000000
Date                                0    0.000000
Age unit                            0    0.000000
Begin year                          0    0.000000
End month                           0    0.000000
End year                            0    0.000000
Population                          0    0.000000
Begin month                         0    0.000000
Mean                                3   11.111111
Age to                              5   18.518519
Reference 3                         9   33.333333
Reference no# 3                     9   33.333333
Link to reference 2                 9   33.333333
Reference 2                         9   33.333333
Reference no# 2                     9   33.333333
Prevalence of deficiency           10   37.037037
Deficiency threshold               10   37.037037
General data comments              13   48.148148
Old Reference no# 1                13   48.148148
Sample size                        13   48.148148
Median                             13   48.148148
SD                                 13   48.148148
U95CI                              17   62.962963
L95CI                              17   62.962963
Old Reference no# 2                22   81.481481
Link to reference 3                22   81.481481
Representativeness name            27  100.000000
SE                                 27  100.000000
Old Reference no# 3                27  100.000000
Marginal deficiency prevalence     27  100.000000
Marginal deficiency range          27  100.000000
Geo mean                           27  100.000000
Indicator unit                     27  100.000000

In [281]:
df119.Country.unique()

array(['Austria', 'United Kingdom of Great Britain and Northern'],
      dtype=object)

In [282]:
df119['Begin year'].unique()

array([2010, 1994, 2000])

Another indicator with too little data to use for this project.

In [283]:
df120.info()
df120.head().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 51 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Indicator.                      27 non-null     object
 1   CountryCode                     27 non-null     object
 2   Country                         27 non-null     object
 3   Representativeness.             27 non-null     object
 4   Representativeness name         0 non-null      float64
 5   Area covered                    27 non-null     object
 6   Date                            27 non-null     int64
 7   Begin month                     27 non-null     int64
 8   Begin year                      27 non-null     int64
 9   End month                       27 non-null     int64
 10  End year                        27 non-null     int64
 11  Population                      27 non-null     object
 12  Gender                          27 non-null     object
 13  Age unit                        27 non-null     object
 14  Age from                        27 non-null     int64
 15  Age to                          22 non-null     float64
 16  Sample size                     14 non-null     float64
 17  Indicator unit                  0 non-null      float64
 18  Mean                            24 non-null     float64
 19  Geo mean                        0 non-null      float64
 20  Median                          14 non-null     float64
 21  SD                              14 non-null     float64
 22  SE                              0 non-null      float64
 23  L95CI                           10 non-null     float64
 24  U95CI                           10 non-null     float64
 25  Deficiency threshold            17 non-null     object
 26  Prevalence of deficiency        17 non-null     float64
 27  Marginal deficiency range       0 non-null      float64
 28  Marginal deficiency prevalence  0 non-null      float64
 29  Sample collection method        27 non-null     object
 30  Sample type                     27 non-null     object
 31  Fasting                         27 non-null     object
 32  Method of analysis              27 non-null     object
 33  General data comments           14 non-null     object
 34  Indicator comments              27 non-null     object
 35  Survey methodology              27 non-null     object
 36  Season                          27 non-null     object
 37  Old Reference no# 1             14 non-null     float64
 38  Count of Reference no# 1        27 non-null     int64
 39  Reference 1                     27 non-null     object
 40  Link to reference 1             27 non-null     object
 41  Old Reference no# 2             5 non-null      float64
 42  Reference no# 2                 18 non-null     float64
 43  Reference 2                     18 non-null     object
 44  Link to reference 2             18 non-null     object
 45  Old Reference no# 3             0 non-null      float64
 46  Reference no# 3                 18 non-null     float64
 47  Reference 3                     18 non-null     object
 48  Link to reference 3             5 non-null      object
 49  SurveyId                        27 non-null     int64
 50  Survey status                   27 non-null     object
dtypes: float64(19), int64(8), object(24)
memory usage: 10.9+ KB

,0,1,2,3,4
Indicator.,Erythrocyte transketolase activity coefficient...,Erythrocyte transketolase activity coefficient...,Erythrocyte transketolase activity coefficient...,Erythrocyte transketolase activity coefficient...,Erythrocyte transketolase activity coefficient...
CountryCode,AUT,AUT,AUT,AUT,AUT
Country,Austria,Austria,Austria,Austria,Austria
Representativeness.,national,national,national,national,national
Representativeness name,NaN,NaN,NaN,NaN,NaN
Area covered,both urban and rural,both urban and rural,both urban and rural,both urban and rural,both urban and rural
Date,2012,2012,2012,2012,2012
Begin month,8,8,8,8,8
Begin year,2010,2010,2010,2010,2010
End month,2,2,2,2,2
End year,2012,2012,2012,2012,2012
Population,Adolescents,Adolescents,Adolescents,Adolescents,Elderly
Gender,Female,Female,Male,Male,All
Age unit,Year,Year,Year,Year,Year
Age from,10,13,10,13,65
Age to,12,14,12,14,80
Sample size,NaN,NaN,NaN,NaN,NaN
Indicator unit,NaN,NaN,NaN,NaN,NaN
Mean,1.17,1.18,1.18,1.17,NaN
Geo mean,NaN,NaN,NaN,NaN,NaN
Median,NaN,NaN,NaN,NaN,NaN
SD,NaN,NaN,NaN,NaN,NaN
SE,NaN,NaN,NaN,NaN,NaN
L95CI,1.16,1.15,1.16,1.14,NaN
U95CI,1.19,1.19,1.2,1.2,NaN
Deficiency threshold,NaN,NaN,NaN,NaN,≥1.25
Prevalence of deficiency,NaN,NaN,NaN,NaN,24.2
Marginal deficiency range,NaN,NaN,NaN,NaN,NaN
Marginal deficiency prevalence,NaN,NaN,NaN,NaN,NaN
Sample collection method,Venipuncture,Venipuncture,Venipuncture,Venipuncture,Venipuncture
Sample type,Red blood cell,Red blood cell,Red blood cell,Red blood cell,Red blood cell
Fasting,Not known,Not known,Not known,Not known,Not known
Method of analysis,Erythrocyte enzyme activation test,Erythrocyte enzyme activation test,Erythrocyte enzyme activation test,Erythrocyte enzyme activation test,Erythrocyte enzyme activation test
General data comments,NaN,NaN,NaN,NaN,NaN
Indicator comments,ETKAC assessed by photometry using the method ...,ETKAC assessed by photometry using the method ...,ETKAC assessed by photometry using the method ...,ETKAC assessed by photometry using the method ...,ETKAC assessed by photometry using the method ...
Survey methodology,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...,National representative survey. First of the n...
Season,Not specified,Not specified,Not specified,Not specified,Not specified
Old Reference no# 1,NaN,NaN,NaN,NaN,NaN
Count of Reference no# 1,1,1,1,1,1
Reference 1,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...,Institut für ErnährungswissenschaftenUniversit...
Link to reference 1,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,http://www.bmgf.gv.at/cms/home/attachments/4/5...
Old Reference no# 2,NaN,NaN,NaN,NaN,NaN
Reference no# 2,1244,1244,1244,1244,1244
Reference 2,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...","Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene..."
Link to reference 2,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...,https://econtent.hogrefe.com/doi/abs/10.1024/0...
Old Reference no# 3,NaN,NaN,NaN,NaN,NaN
Reference no# 3,1399,1399,1399,1399,1399
Reference 3,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...","Elmadfa I, Meyer AL, Wottawa D, Wagner K and H..."
Link to reference 3,NaN,NaN,NaN,NaN,NaN
SurveyId,10872,10872,10872,10872,10872
Survey status,verified,verified,verified,verified,verified

Checking for missing values:

In [284]:
missing = pd.concat([df120.isnull().sum(), 100 * df120.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                                count           %
Indicator.                          0    0.000000
Link to reference 1                 0    0.000000
Reference 1                         0    0.000000
Count of Reference no# 1            0    0.000000
Season                              0    0.000000
Survey methodology                  0    0.000000
Indicator comments                  0    0.000000
Method of analysis                  0    0.000000
Fasting                             0    0.000000
Sample type                         0    0.000000
Sample collection method            0    0.000000
SurveyId                            0    0.000000
Age from                            0    0.000000
Survey status                       0    0.000000
Gender                              0    0.000000
CountryCode                         0    0.000000
Country                             0    0.000000
Representativeness.                 0    0.000000
Area covered                        0    0.000000
Date                                0    0.000000
Age unit                            0    0.000000
Begin year                          0    0.000000
End month                           0    0.000000
End year                            0    0.000000
Population                          0    0.000000
Begin month                         0    0.000000
Mean                                3   11.111111
Age to                              5   18.518519
Reference 3                         9   33.333333
Reference no# 3                     9   33.333333
Link to reference 2                 9   33.333333
Reference 2                         9   33.333333
Reference no# 2                     9   33.333333
Prevalence of deficiency           10   37.037037
Deficiency threshold               10   37.037037
General data comments              13   48.148148
Old Reference no# 1                13   48.148148
Sample size                        13   48.148148
Median                             13   48.148148
SD                                 13   48.148148
U95CI                              17   62.962963
L95CI                              17   62.962963
Old Reference no# 2                22   81.481481
Link to reference 3                22   81.481481
Representativeness name            27  100.000000
SE                                 27  100.000000
Old Reference no# 3                27  100.000000
Marginal deficiency prevalence     27  100.000000
Marginal deficiency range          27  100.000000
Geo mean                           27  100.000000
Indicator unit                     27  100.000000

In [285]:
df120.Country.unique()

array(['Austria', 'United Kingdom of Great Britain and Northern'],
      dtype=object)

In [286]:
df120['Begin year'].unique()

array([2010, 1994, 2000])

Another indicator with too little data to use for this project.

In [287]:
df121.info()
df121.head().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 49 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Indicator.                       149 non-null    object
 1   CountryCode                      149 non-null    object
 2   Country                          149 non-null    object
 3   Representativeness.              149 non-null    object
 4   Representativeness name          0 non-null      float64
 5   Area covered                     149 non-null    object
 6   Date                             149 non-null    int64
 7   Begin month                      140 non-null    float64
 8   Begin year                       149 non-null    int64
 9   End month                        140 non-null    float64
 10  End year                         149 non-null    int64
 11  Population                       149 non-null    object
 12  Gender                           149 non-null    object
 13  Age unit                         149 non-null    object
 14  Age from                         148 non-null    float64
 15  Age to                           129 non-null    float64
 16  Sample size                      121 non-null    float64
 17  Indicator unit                   113 non-null    object
 18  Mean                             58 non-null     float64
 19  Geo mean                         52 non-null     float64
 20  Median                           51 non-null     float64
 21  SD                               50 non-null     float64
 22  SE                               4 non-null      float64
 23  L95CI                            60 non-null     float64
 24  U95CI                            60 non-null     float64
 25  1st prev desc                    149 non-null    object
 26  Depleted iron stores cut-off     111 non-null    object
 27  Depleted iron stores prevalence  111 non-null    float64
 28  Sample collection method         149 non-null    object
 29  Sample type                      149 non-null    object
 30  Method of analysis               149 non-null    object
 31  Data adjusted for                149 non-null    object
 32  General data comments            96 non-null     object
 33  Indicator comments               149 non-null    object
 34  Survey methodology               149 non-null    object
 35  Old Reference no# 1              26 non-null     float64
 36  Reference no# 1                  149 non-null    int64
 37  Reference 1                      149 non-null    object
 38  Link to reference 1              127 non-null    object
 39  Old Reference no# 2              14 non-null     float64
 40  Reference no# 2                  84 non-null     float64
 41  Reference 2                      84 non-null     object
 42  Link to reference 2              75 non-null     object
 43  Old Reference no# 3              7 non-null      float64
 44  Reference no# 3                  76 non-null     float64
 45  Reference 3                      76 non-null     object
 46  Link to reference 3              64 non-null     object
 47  SurveyId                         149 non-null    int64
 48  Survey status                    149 non-null    object
dtypes: float64(19), int64(5), object(25)
memory usage: 57.2+ KB

,0,1,2,3,4
Indicator.,Ferritin,Ferritin,Ferritin,Ferritin,Ferritin
CountryCode,AUS,AUS,AUS,AUS,AUS
Country,Australia,Australia,Australia,Australia,Australia
Representativeness.,national,national,national,national,national
Representativeness name,NaN,NaN,NaN,NaN,NaN
Area covered,both urban and rural,both urban and rural,both urban and rural,both urban and rural,both urban and rural
Date,2012,2012,2012,2012,2012
Begin month,3,3,3,3,3
Begin year,2011,2011,2011,2011,2011
End month,9,9,9,9,9
End year,2012,2012,2012,2012,2012
Population,Adolescents,Adults,Adults,Adults,Adults
Gender,All,All,All,All,All
Age unit,Year,Year,Year,Year,Year
Age from,12,18,18,25,35
Age to,17,NaN,24,34,44
Sample size,722,8890,409,1158,1531
Indicator unit,µg/L,µg/L,µg/L,µg/L,µg/L
Mean,45.1,145,86.9,118.7,139.1
Geo mean,NaN,NaN,NaN,NaN,NaN
Median,37,108,68.7,84.7,100
SD,NaN,NaN,NaN,NaN,NaN
SE,NaN,NaN,NaN,NaN,NaN
L95CI,NaN,NaN,NaN,NaN,NaN
U95CI,NaN,NaN,NaN,NaN,NaN
1st prev desc,Depleted iron stores,Depleted iron stores,Depleted iron stores,Depleted iron stores,Depleted iron stores
Depleted iron stores cut-off,NaN,<15 µg/L,NaN,NaN,NaN
Depleted iron stores prevalence,NaN,4.8,NaN,NaN,NaN
Sample collection method,Venipuncture,Venipuncture,Venipuncture,Venipuncture,Venipuncture
Sample type,Blood serum,Blood serum,Blood serum,Blood serum,Blood serum
Method of analysis,Electro-chemiluminescence,Electro-chemiluminescence,Electro-chemiluminescence,Electro-chemiluminescence,Electro-chemiluminescence
Data adjusted for,Inflamation,Inflamation,Inflamation,Inflamation,Inflamation
General data comments,NaN,Upper bound of age range not provided (over 75...,NaN,NaN,NaN
Indicator comments,Ferritin assessed using Chemiluminescent Micro...,Ferritin assessed using Chemiluminescent Micro...,Ferritin assessed using Chemiluminescent Micro...,Ferritin assessed using Chemiluminescent Micro...,Ferritin assessed using Chemiluminescent Micro...
Survey methodology,The Australian Health Survey is made up of the...,The Australian Health Survey is made up of the...,The Australian Health Survey is made up of the...,The Australian Health Survey is made up of the...,The Australian Health Survey is made up of the...
Old Reference no# 1,NaN,NaN,NaN,NaN,NaN
Reference no# 1,61,61,61,61,61
Reference 1,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...
Link to reference 1,http://www.abs.gov.au/ausstats/abs@.nsf/Primar...,http://www.abs.gov.au/ausstats/abs@.nsf/Primar...,http://www.abs.gov.au/ausstats/abs@.nsf/Primar...,http://www.abs.gov.au/ausstats/abs@.nsf/Primar...,http://www.abs.gov.au/ausstats/abs@.nsf/Primar...
Old Reference no# 2,NaN,NaN,NaN,NaN,NaN
Reference no# 2,107,107,107,107,107
Reference 2,"Australian Health Survey: user's guide, 2011-1...","Australian Health Survey: user's guide, 2011-1...","Australian Health Survey: user's guide, 2011-1...","Australian Health Survey: user's guide, 2011-1...","Australian Health Survey: user's guide, 2011-1..."
Link to reference 2,http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...
Old Reference no# 3,NaN,NaN,NaN,NaN,NaN
Reference no# 3,176,176,176,176,176
Reference 3,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...,Australian Health Survey: biomedical results f...
Link to reference 3,http://www.ausstats.abs.gov.au/ausstats/subscr...,http://www.ausstats.abs.gov.au/ausstats/subscr...,http://www.ausstats.abs.gov.au/ausstats/subscr...,http://www.ausstats.abs.gov.au/ausstats/subscr...,http://www.ausstats.abs.gov.au/ausstats/subscr...
SurveyId,10160,10160,10160,10160,10160
Survey status,verified,verified,verified,verified,verified

Checking for missing values:

In [288]:
missing = pd.concat([df121.isnull().sum(), 100 * df121.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                                 count           %
Indicator.                           0    0.000000
Reference 1                          0    0.000000
Reference no# 1                      0    0.000000
Survey methodology                   0    0.000000
Indicator comments                   0    0.000000
Data adjusted for                    0    0.000000
Method of analysis                   0    0.000000
Sample type                          0    0.000000
Sample collection method             0    0.000000
1st prev desc                        0    0.000000
SurveyId                             0    0.000000
Age unit                             0    0.000000
Survey status                        0    0.000000
Population                           0    0.000000
CountryCode                          0    0.000000
Country                              0    0.000000
Representativeness.                  0    0.000000
Area covered                         0    0.000000
Gender                               0    0.000000
Begin year                           0    0.000000
End year                             0    0.000000
Date                                 0    0.000000
Age from                             1    0.671141
End month                            9    6.040268
Begin month                          9    6.040268
Age to                              20   13.422819
Link to reference 1                 22   14.765101
Sample size                         28   18.791946
Indicator unit                      36   24.161074
Depleted iron stores cut-off        38   25.503356
Depleted iron stores prevalence     38   25.503356
General data comments               53   35.570470
Reference 2                         65   43.624161
Reference no# 2                     65   43.624161
Reference 3                         73   48.993289
Reference no# 3                     73   48.993289
Link to reference 2                 74   49.664430
Link to reference 3                 85   57.046980
L95CI                               89   59.731544
U95CI                               89   59.731544
Mean                                91   61.073826
Geo mean                            97   65.100671
Median                              98   65.771812
SD                                  99   66.442953
Old Reference no# 1                123   82.550336
Old Reference no# 2                135   90.604027
Old Reference no# 3                142   95.302013
SE                                 145   97.315436
Representativeness name            149  100.000000

In [289]:
df121.Country.unique()

array(['Australia', 'Austria', 'Bangladesh', 'Belize', 'Canada',
       'Colombia', 'Costa Rica', 'Dominica', 'Ecuador', 'France',
       'United Kingdom of Great Britain and Northern', 'Kenya', 'Morocco',
       'Mexico', 'Mauritius', 'Malawi', 'Nepal', 'New Zealand',
       'Saint Vincent and the Grenadines'], dtype=object)

In [290]:
df121['Begin year'].unique()

array([2011, 2010, 2009, 2008, 1996, 2012, 1994, 2006, 2000, 1999, 1995,
       2015, 2016, 2002])

In [291]:
labels=["Indicator.", "Country", "Date", "Population", "Gender", "Indicator unit", "Mean", "Depleted iron stores cut-off", "Depleted iron stores prevalence", "Median", "U95CI", "L95CI"]
df121=df121[labels]

In [292]:
df121.shape
df121.head(15)

,Indicator.,Country,Date,Population,Gender,Indicator unit,Mean,Depleted iron stores cut-off,Depleted iron stores prevalence,Median,U95CI,L95CI
0,Ferritin,Australia,2012,Adolescents,All,µg/L,45.1,NaN,NaN,37.0,NaN,NaN
1,Ferritin,Australia,2012,Adults,All,µg/L,145.0,<15 µg/L,4.8,108.0,NaN,NaN
2,Ferritin,Australia,2012,Adults,All,µg/L,86.9,NaN,NaN,68.7,NaN,NaN
3,Ferritin,Australia,2012,Adults,All,µg/L,118.7,NaN,NaN,84.7,NaN,NaN
4,Ferritin,Australia,2012,Adults,All,µg/L,139.1,NaN,NaN,100.0,NaN,NaN
5,Ferritin,Australia,2012,Adults,All,µg/L,166.1,NaN,NaN,123.0,NaN,NaN
6,Ferritin,Australia,2012,Adults,All,µg/L,182.1,NaN,NaN,138.0,NaN,NaN
7,Ferritin,Australia,2012,Adults,Female,µg/L,86.9,<15 µg/L,8.0,60.0,NaN,NaN
8,Ferritin,Australia,2012,Elderly,All,µg/L,184.9,NaN,NaN,141.0,NaN,NaN
9,Ferritin,Australia,2012,Elderly,All,µg/L,157.4,NaN,NaN,123.0,NaN,NaN
10,Ferritin,Australia,2012,Men,Male,µg/L,204.5,<15 µg/L,1.6,165.0,NaN,NaN
11,Ferritin,Austria,2012,Adolescents,Female,µg/L,20.0,NaN,NaN,NaN,25.0,14.0
12,Ferritin,Austria,2012,Adolescents,Female,µg/L,11.0,NaN,NaN,NaN,15.0,8.0
13,Ferritin,Austria,2012,Adolescents,Male,µg/L,17.0,NaN,NaN,NaN,19.0,15.0
14,Ferritin,Austria,2012,Adolescents,Male,µg/L,9.0,NaN,NaN,NaN,13.0,4.0

In [293]:
(df121["Country"] + ", " + df121["Population"]).value_counts()

Nepal, Adolescents                                       16
Ecuador, Adolescents                                      9
United Kingdom of Great Britain and Northern, Elderly     9
Costa Rica, Men                                           8
Mexico, Elderly                                           8
Australia, Adults                                         7
France, Men                                               7
Ecuador, Men                                              6
Canada, Elderly                                           5
Malawi, Men                                               5
United Kingdom of Great Britain and Northern, Men         5
Canada, Men                                               4
Kenya, Men                                                4
Austria, Adolescents                                      4
Austria, Men                                              4
New Zealand, Men                                          4
Bangladesh, Adolescents                                   4
New Zealand, Adolescents                                  4
France, Adults                                            4
Malawi, Adolescents                                       3
France, Women                                             3
Canada, Adolescents                                       3
New Zealand, Elderly                                      2
Australia, Elderly                                        2
New Zealand, Women                                        2
Austria, Elderly                                          2
Austria, Women                                            2
Canada, Adults                                            2
Saint Vincent and the Grenadines, Adolescents             1
Belize, Adolescents                                       1
Mauritius, Men                                            1
Dominica, Adolescents                                     1
New Zealand, Adults                                       1
Morocco, Men                                              1
Australia, Men                                            1
Australia, Adolescents                                    1
Colombia, Adolescents                                     1
Canada, Women                                             1
Ecuador, Women                                            1
dtype: int64

In [294]:
df121.Country.value_counts()

Ecuador                                         16
Nepal                                           16
Canada                                          15
United Kingdom of Great Britain and Northern    14
France                                          14
New Zealand                                     13
Austria                                         12
Australia                                       11
Costa Rica                                       8
Mexico                                           8
Malawi                                           8
Bangladesh                                       4
Kenya                                            4
Saint Vincent and the Grenadines                 1
Belize                                           1
Colombia                                         1
Mauritius                                        1
Dominica                                         1
Morocco                                          1
Name: Country, dtype: int64

In [295]:
df122.info()
df122.head().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 48 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Indicator.                97 non-null     object
 1   Country                   97 non-null     object
 2   CountryCode               97 non-null     object
 3   Representativeness.       97 non-null     object
 4   Representativeness name   0 non-null      float64
 5   Area covered              97 non-null     object
 6   Date                      97 non-null     int64
 7   Begin month               97 non-null     int64
 8   Begin year                97 non-null     int64
 9   End month                 97 non-null     int64
 10  End year                  97 non-null     int64
 11  Population                97 non-null     object
 12  Gender                    97 non-null     object
 13  Age unit                  97 non-null     object
 14  Age from                  97 non-null     int64
 15  Age to                    72 non-null     float64
 16  Sample size               93 non-null     float64
 17  Indicator unit            86 non-null     object
 18  Mean                      72 non-null     float64
 19  Geo mean                  0 non-null      float64
 20  Median                    56 non-null     float64
 21  SD                        29 non-null     float64
 22  SE                        4 non-null      float64
 23  L95CI                     38 non-null     float64
 24  U95CI                     38 non-null     float64
 25  Deficiency cut-off        56 non-null     object
 26  Deficiency prevalence     56 non-null     float64
 27  Sample collection method  97 non-null     object
 28  Sample type               97 non-null     object
 29  Fasting                   97 non-null     object
 30  Method of analysis        97 non-null     object
 31  General data comments     29 non-null     object
 32  Indicator comments        97 non-null     object
 33  Survey methodology        97 non-null     object
 34  Old Reference no# 1       14 non-null     float64
 35  Reference no# 1           97 non-null     int64
 36  Reference 1               97 non-null     object
 37  Link to reference 1       91 non-null     object
 38  Old Reference no# 2       5 non-null      float64
 39  Reference no# 2           66 non-null     float64
 40  Reference 2               66 non-null     object
 41  Link to reference 2       66 non-null     object
 42  Old Reference no# 3       0 non-null      float64
 43  Reference no# 3           59 non-null     float64
 44  Reference 3               59 non-null     object
 45  Link to reference 3       46 non-null     object
 46  SurveyId                  97 non-null     int64
 47  Survey status             97 non-null     object
dtypes: float64(16), int64(8), object(24)
memory usage: 36.5+ KB

,0,1,2,3,4
Indicator.,Folate (plasma or serum),Folate (plasma or serum),Folate (plasma or serum),Folate (plasma or serum),Folate (plasma or serum)
Country,Afghanistan,Chile,Chile,Chile,Chile
CountryCode,AFG,CHL,CHL,CHL,CHL
Representativeness.,national,national,national,national,national
Representativeness name,NaN,NaN,NaN,NaN,NaN
Area covered,both urban and rural,both urban and rural,both urban and rural,both urban and rural,both urban and rural
Date,2013,2010,2010,2010,2010
Begin month,6,10,10,10,10
Begin year,2013,2009,2009,2009,2009
End month,10,9,9,9,9
End year,2013,2010,2010,2010,2010
Population,Adolescents,Elderly,Elderly,Elderly,Elderly
Gender,Female,All,Female,Female,Female
Age unit,Year,Year,Year,Year,Year
Age from,10,65,65,65,75
Age to,19,NaN,NaN,74,NaN
Sample size,741,823,510,269,241
Indicator unit,NaN,nmol/L,nmol/L,nmol/L,nmol/L
Mean,NaN,48.03,49.61,44.18,50.75
Geo mean,NaN,NaN,NaN,NaN,NaN
Median,NaN,44.18,44.18,48.71,44.4
SD,NaN,NaN,NaN,NaN,NaN
SE,NaN,NaN,NaN,NaN,NaN
L95CI,NaN,NaN,NaN,NaN,NaN
U95CI,NaN,NaN,NaN,NaN,NaN
Deficiency cut-off,<6.8 nmol/L,<10 nmol/L,<10 nmol/L,<10 nmol/L,<10 nmol/L
Deficiency prevalence,7.4,0.3,0.4,0,0.9
Sample collection method,Venipuncture,Venipuncture,Venipuncture,Venipuncture,Venipuncture
Sample type,Blood serum,Blood serum,Blood serum,Blood serum,Blood serum
Fasting,Not known,Fasting/first morning sample,Fasting/first morning sample,Fasting/first morning sample,Fasting/first morning sample
Method of analysis,Electro-chemiluminescence,Electro-chemiluminescence,Electro-chemiluminescence,Electro-chemiluminescence,Electro-chemiluminescence
General data comments,NaN,Upper bound of age range not reported (>75 y)....,Upper bound of age range not reported (>75 y)....,Study considered values >45 nmol/L as supraphy...,Upper bound of age range not reported (>75 y)....
Indicator comments,Serum folate assessed using electrochemilumine...,91% of samples were processed before 4 h from ...,91% of samples were processed before 4 h from ...,91% of samples were processed before 4 h from ...,91% of samples were processed before 4 h from ...
Survey methodology,Survey designed to provide national estimates ...,Survey representative at national and regional...,Survey representative at national and regional...,Survey representative at national and regional...,Survey representative at national and regional...
Old Reference no# 1,NaN,NaN,NaN,NaN,NaN
Reference no# 1,102,1102,1102,1102,1102
Reference 1,"Ministry of Public Health (Afghanistan), UNICE...",Encuesta Nacional de Salud (ENS) Chile 2009-20...,Encuesta Nacional de Salud (ENS) Chile 2009-20...,Encuesta Nacional de Salud (ENS) Chile 2009-20...,Encuesta Nacional de Salud (ENS) Chile 2009-20...
Link to reference 1,http://reliefweb.int/sites/reliefweb.int/files...,http://www.minsal.cl/portal/url/item/bcb03d7bc...,http://www.minsal.cl/portal/url/item/bcb03d7bc...,http://www.minsal.cl/portal/url/item/bcb03d7bc...,http://www.minsal.cl/portal/url/item/bcb03d7bc...
Old Reference no# 2,NaN,NaN,NaN,NaN,NaN
Reference no# 2,NaN,1103,1103,1103,1103
Reference 2,NaN,"Castillo-Lancellotti C, Margozzini P, Valdivia...","Castillo-Lancellotti C, Margozzini P, Valdivia...","Castillo-Lancellotti C, Margozzini P, Valdivia...","Castillo-Lancellotti C, Margozzini P, Valdivia..."
Link to reference 2,NaN,http://www.scielo.cl/scielo.php?script=sci_art...,http://www.scielo.cl/scielo.php?script=sci_art...,http://www.scielo.cl/scielo.php?script=sci_art...,http://www.scielo.cl/scielo.php?script=sci_art...
Old Reference no# 3,NaN,NaN,NaN,NaN,NaN
Reference no# 3,NaN,NaN,NaN,NaN,NaN
Reference 3,NaN,NaN,NaN,NaN,NaN
Link to reference 3,NaN,NaN,NaN,NaN,NaN
SurveyId,10003,10959,10959,10959,10959
Survey status,verified,verified,verified,verified,verified

Checking for missing values:

In [296]:
missing = pd.concat([df122.isnull().sum(), 100 * df122.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                          count           %
Indicator.                    0    0.000000
Reference 1                   0    0.000000
Reference no# 1               0    0.000000
Survey methodology            0    0.000000
Indicator comments            0    0.000000
Method of analysis            0    0.000000
Fasting                       0    0.000000
Sample type                   0    0.000000
Sample collection method      0    0.000000
SurveyId                      0    0.000000
Age from                      0    0.000000
Age unit                      0    0.000000
Survey status                 0    0.000000
Population                    0    0.000000
Country                       0    0.000000
CountryCode                   0    0.000000
Representativeness.           0    0.000000
Gender                        0    0.000000
Date                          0    0.000000
Begin month                   0    0.000000
Begin year                    0    0.000000
End month                     0    0.000000
Area covered                  0    0.000000
End year                      0    0.000000
Sample size                   4    4.123711
Link to reference 1           6    6.185567
Indicator unit               11   11.340206
Age to                       25   25.773196
Mean                         25   25.773196
Link to reference 2          31   31.958763
Reference 2                  31   31.958763
Reference no# 2              31   31.958763
Reference 3                  38   39.175258
Reference no# 3              38   39.175258
Deficiency cut-off           41   42.268041
Deficiency prevalence        41   42.268041
Median                       41   42.268041
Link to reference 3          51   52.577320
L95CI                        59   60.824742
U95CI                        59   60.824742
General data comments        68   70.103093
SD                           68   70.103093
Old Reference no# 1          83   85.567010
Old Reference no# 2          92   94.845361
SE                           93   95.876289
Representativeness name      97  100.000000
Old Reference no# 3          97  100.000000
Geo mean                     97  100.000000

In [297]:
df122.Country.unique()

array(['Afghanistan', 'Chile', 'Costa Rica', 'Ecuador',
       'United Kingdom of Great Britain and Northern', 'Austria',
       'Ireland', 'France', 'Australia', 'New Zealand'], dtype=object)

In [298]:
df122['Begin year'].unique()

array([2013, 2009, 2008, 2012, 1994, 2010, 2000, 2006, 2011])

In [299]:
labels=["Indicator.", "Country", "Date", "Population", "Gender", "Indicator unit", "Deficiency prevalence", "Mean", "Deficiency cut-off", "Median", "U95CI", "L95CI"]
df122=df122[labels]

In [300]:
df122.shape
df122.head(15)

,Indicator.,Country,Date,Population,Gender,Indicator unit,Deficiency prevalence,Mean,Deficiency cut-off,Median,U95CI,L95CI
0,Folate (plasma or serum),Afghanistan,2013,Adolescents,Female,NaN,7.4,NaN,<6.8 nmol/L,NaN,NaN,NaN
1,Folate (plasma or serum),Chile,2010,Elderly,All,nmol/L,0.3,48.03,<10 nmol/L,44.18,NaN,NaN
2,Folate (plasma or serum),Chile,2010,Elderly,Female,nmol/L,0.4,49.61,<10 nmol/L,44.18,NaN,NaN
3,Folate (plasma or serum),Chile,2010,Elderly,Female,nmol/L,0.0,44.18,<10 nmol/L,48.71,NaN,NaN
4,Folate (plasma or serum),Chile,2010,Elderly,Female,nmol/L,0.9,50.75,<10 nmol/L,44.40,NaN,NaN
5,Folate (plasma or serum),Chile,2010,Elderly,Male,nmol/L,0.1,45.54,<10 nmol/L,44.18,NaN,NaN
6,Folate (plasma or serum),Chile,2010,Elderly,Male,nmol/L,0.0,45.31,<10 nmol/L,44.86,NaN,NaN
7,Folate (plasma or serum),Chile,2010,Elderly,Male,nmol/L,0.2,45.76,<10 nmol/L,42.59,NaN,NaN
8,Folate (plasma or serum),Costa Rica,2009,Elderly,All,nmol/L,1.4,31.50,<13.6 nmol/L,NaN,NaN,NaN
9,Folate (plasma or serum),Costa Rica,2009,Elderly,Female,nmol/L,NaN,33.76,NaN,NaN,35.35,32.40
10,Folate (plasma or serum),Costa Rica,2009,Elderly,Male,nmol/L,NaN,28.33,NaN,NaN,30.36,26.29
11,Folate (plasma or serum),Costa Rica,2009,Elderly,All,nmol/L,1.3,32.86,<13.6 nmol/L,NaN,35.12,30.59
12,Folate (plasma or serum),Costa Rica,2009,Elderly,All,nmol/L,1.6,30.14,<13.6 nmol/L,NaN,32.40,28.10
13,Folate (plasma or serum),Costa Rica,2009,Elderly,All,nmol/L,1.2,31.95,<13.6 nmol/L,NaN,33.76,29.91
14,Folate (plasma or serum),Ecuador,2012,Adolescents,All,NaN,0.2,NaN,<9 nmol/L,NaN,NaN,NaN

In [301]:
(df122["Country"] + ", " + df122["Population"]).value_counts()

United Kingdom of Great Britain and Northern, Elderly    9
Ireland, Adults                                          8
Australia, Adults                                        7
Chile, Elderly                                           7
Ecuador, Adolescents                                     6
Costa Rica, Elderly                                      6
United Kingdom of Great Britain and Northern, Men        5
Ecuador, Adults                                          5
Austria, Men                                             4
New Zealand, Men                                         4
France, Adults                                           4
Austria, Adolescents                                     4
France, Men                                              3
Ireland, Elderly                                         3
Ecuador, Men                                             3
New Zealand, Adolescents                                 3
Austria, Elderly                                         3
Australia, Elderly                                       2
Austria, Women                                           2
New Zealand, Adults                                      2
New Zealand, Elderly                                     2
Ecuador, Women                                           1
New Zealand, Women                                       1
Afghanistan, Adolescents                                 1
Australia, Adolescents                                   1
Australia, Men                                           1
dtype: int64

In [302]:
df122.Country.value_counts()

Ecuador                                         15
United Kingdom of Great Britain and Northern    14
Austria                                         13
New Zealand                                     12
Ireland                                         11
Australia                                       11
France                                           7
Chile                                            7
Costa Rica                                       6
Afghanistan                                      1
Name: Country, dtype: int64

In [303]:
df123.info()
df123.head().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 50 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Indicator.                61 non-null     object
 1   CountryCode               61 non-null     object
 2   Country                   61 non-null     object
 3   Representativeness.       61 non-null     object
 4   Representativeness name   0 non-null      float64
 5   Area covered              61 non-null     object
 6   Date                      61 non-null     int64
 7   Begin month               61 non-null     int64
 8   Begin year                61 non-null     int64
 9   End month                 61 non-null     int64
 10  End year                  61 non-null     int64
 11  Population                61 non-null     object
 12  Gender                    61 non-null     object
 13  Age unit                  61 non-null     object
 14  Age from                  61 non-null     int64
 15  Age to                    50 non-null     float64
 16  Sample size               61 non-null     int64
 17  Indicator unit            55 non-null     object
 18  Mean                      34 non-null     float64
 19  Geo mean                  8 non-null      float64
 20  Median                    39 non-null     float64
 21  SD                        31 non-null     float64
 22  SE                        2 non-null      float64
 23  L95CI                     21 non-null     float64
 24  U95CI                     21 non-null     float64
 25  Deficiency cut-off        41 non-null     object
 26  Deficiency prevalence     41 non-null     float64
 27  Insufficiency cut-off     9 non-null      object
 28  Insufficiency prevalence  9 non-null      float64
 29  Sample collection method  61 non-null     object
 30  Sample type               61 non-null     object
 31  Fasting                   61 non-null     object
 32  Method of analysis        61 non-null     object
 33  General data comments     29 non-null     object
 34  Indicator comments        61 non-null     object
 35  Survey methodology        61 non-null     object
 36  Old Reference no# 1       14 non-null     float64
 37  Reference no# 1           61 non-null     int64
 38  Reference 1               61 non-null     object
 39  Link to reference 1       61 non-null     object
 40  Old Reference no# 2       5 non-null      float64
 41  Reference no# 2           29 non-null     float64
 42  Reference 2               29 non-null     object
 43  Link to reference 2       29 non-null     object
 44  Old Reference no# 3       0 non-null      float64
 45  Reference no# 3           29 non-null     float64
 46  Reference 3               29 non-null     object
 47  Link to reference 3       29 non-null     object
 48  SurveyId                  61 non-null     int64
 49  Survey status             61 non-null     object
dtypes: float64(16), int64(9), object(25)
memory usage: 24.0+ KB

,0,1,2,3,4
Indicator.,Folate (red blood cell),Folate (red blood cell),Folate (red blood cell),Folate (red blood cell),Folate (red blood cell)
CountryCode,AUS,ECU,ECU,ECU,ECU
Country,Australia,Ecuador,Ecuador,Ecuador,Ecuador
Representativeness.,national,national,national,national,national
Representativeness name,NaN,NaN,NaN,NaN,NaN
Area covered,both urban and rural,both urban and rural,both urban and rural,both urban and rural,both urban and rural
Date,2012,2012,2012,2012,2012
Begin month,3,7,7,7,7
Begin year,2011,2012,2012,2012,2012
End month,9,12,12,12,12
End year,2012,2012,2012,2012,2012
Population,Adults,Adolescents,Adolescents,Adolescents,Adolescents
Gender,Female,All,All,Female,Female
Age unit,Year,Year,Year,Year,Year
Age from,18,12,15,12,15
Age to,NaN,14,19,14,19
Sample size,5312,1688,2306,824,1260
Indicator unit,nmol/L,NaN,NaN,nmol/L,nmol/L
Mean,1711.4,NaN,NaN,846.35,860.17
Geo mean,NaN,NaN,NaN,NaN,NaN
Median,1659,NaN,NaN,776.11,772.48
SD,NaN,NaN,NaN,318.6,341.49
SE,NaN,NaN,NaN,NaN,NaN
L95CI,NaN,NaN,NaN,813.49,821.65
U95CI,NaN,NaN,NaN,878.98,898.47
Deficiency cut-off,NaN,<342 nmol/L,<342 nmol/L,<342 nmol/L,<342 nmol/L
Deficiency prevalence,NaN,1.1,1.4,1.2,0.8
Insufficiency cut-off,<906 nmol/L,NaN,NaN,NaN,NaN
Insufficiency prevalence,0.8,NaN,NaN,NaN,NaN
Sample collection method,Venipuncture,Venipuncture,Venipuncture,Venipuncture,Venipuncture
Sample type,Whole blood,Red blood cell,Red blood cell,Red blood cell,Red blood cell
Fasting,Casual,Fasting/first morning sample,Fasting/first morning sample,Fasting/first morning sample,Fasting/first morning sample
Method of analysis,Electro-chemiluminescence,Protein binding assay,Protein binding assay,Protein binding assay,Protein binding assay
General data comments,Upper bound of age range not specified. Sample...,NaN,NaN,NaN,NaN
Indicator comments,Red blood cell folate measured using competiti...,Blood collected after at least 8 hours of fast...,Blood collected after at least 8 hours of fast...,Blood collected after at least 8 hours of fast...,Blood collected after at least 8 hours of fast...
Survey methodology,The Australian Health Survey is made up of the...,"Survey representative at national, regional an...","Survey representative at national, regional an...","Survey representative at national, regional an...","Survey representative at national, regional an..."
Old Reference no# 1,NaN,NaN,NaN,NaN,NaN
Reference no# 1,61,837,837,837,837
Reference 1,Australian Health Survey: biomedical results f...,"Freire WB, Ramírez-Luzuriaga MJ, Belmont P, Me...","Freire WB, Ramírez-Luzuriaga MJ, Belmont P, Me...","Freire WB, Ramírez-Luzuriaga MJ, Belmont P, Me...","Freire WB, Ramírez-Luzuriaga MJ, Belmont P, Me..."
Link to reference 1,http://www.abs.gov.au/ausstats/abs@.nsf/Primar...,http://www.ecuadorencifras.gob.ec/documentos/w...,http://www.ecuadorencifras.gob.ec/documentos/w...,http://www.ecuadorencifras.gob.ec/documentos/w...,http://www.ecuadorencifras.gob.ec/documentos/w...
Old Reference no# 2,NaN,NaN,NaN,NaN,NaN
Reference no# 2,107,NaN,NaN,NaN,NaN
Reference 2,"Australian Health Survey: user's guide, 2011-1...",NaN,NaN,NaN,NaN
Link to reference 2,http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,NaN,NaN,NaN,NaN
Old Reference no# 3,NaN,NaN,NaN,NaN,NaN
Reference no# 3,176,NaN,NaN,NaN,NaN
Reference 3,Australian Health Survey: biomedical results f...,NaN,NaN,NaN,NaN
Link to reference 3,http://www.ausstats.abs.gov.au/ausstats/subscr...,NaN,NaN,NaN,NaN
SurveyId,10160,10846,10846,10846,10846
Survey status,verified,verified,verified,verified,verified

Checking for missing values:

In [304]:
missing = pd.concat([df123.isnull().sum(), 100 * df123.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                          count           %
Indicator.                    0    0.000000
Link to reference 1           0    0.000000
Reference 1                   0    0.000000
Reference no# 1               0    0.000000
Survey methodology            0    0.000000
Indicator comments            0    0.000000
Method of analysis            0    0.000000
Fasting                       0    0.000000
Sample type                   0    0.000000
Sample collection method      0    0.000000
SurveyId                      0    0.000000
Sample size                   0    0.000000
Age from                      0    0.000000
Survey status                 0    0.000000
Gender                        0    0.000000
CountryCode                   0    0.000000
Country                       0    0.000000
Representativeness.           0    0.000000
Area covered                  0    0.000000
Date                          0    0.000000
Age unit                      0    0.000000
Begin year                    0    0.000000
End month                     0    0.000000
End year                      0    0.000000
Begin month                   0    0.000000
Population                    0    0.000000
Indicator unit                6    9.836066
Age to                       11   18.032787
Deficiency cut-off           20   32.786885
Deficiency prevalence        20   32.786885
Median                       22   36.065574
Mean                         27   44.262295
SD                           30   49.180328
Link to reference 3          32   52.459016
General data comments        32   52.459016
Reference 3                  32   52.459016
Reference no# 3              32   52.459016
Link to reference 2          32   52.459016
Reference 2                  32   52.459016
Reference no# 2              32   52.459016
U95CI                        40   65.573770
L95CI                        40   65.573770
Old Reference no# 1          47   77.049180
Insufficiency prevalence     52   85.245902
Insufficiency cut-off        52   85.245902
Geo mean                     53   86.885246
Old Reference no# 2          56   91.803279
SE                           59   96.721311
Old Reference no# 3          61  100.000000
Representativeness name      61  100.000000

In [305]:
df123.Country.unique()

array(['Australia', 'Ecuador',
       'United Kingdom of Great Britain and Northern', 'Ireland', 'Nepal',
       'New Zealand'], dtype=object)

In [306]:
df123['Begin year'].unique()

array([2011, 2012, 1994, 2000, 2008, 2016])

In [307]:
labels=["Indicator.", "Country", "Date", "Population", "Gender", "Indicator unit", "Deficiency prevalence", "Mean", "Deficiency cut-off", "Median", "Insufficiency prevalence", "Insufficiency cut-off", "U95CI", "L95CI"]
df123=df123[labels]

In [308]:
df123.shape
df123.head(15)

,Indicator.,Country,Date,Population,Gender,Indicator unit,Deficiency prevalence,Mean,Deficiency cut-off,Median,Insufficiency prevalence,Insufficiency cut-off,U95CI,L95CI
0,Folate (red blood cell),Australia,2012,Adults,Female,nmol/L,NaN,1711.40,NaN,1659.00,0.8,<906 nmol/L,NaN,NaN
1,Folate (red blood cell),Ecuador,2012,Adolescents,All,NaN,1.1,NaN,<342 nmol/L,NaN,NaN,NaN,NaN,NaN
2,Folate (red blood cell),Ecuador,2012,Adolescents,All,NaN,1.4,NaN,<342 nmol/L,NaN,NaN,NaN,NaN,NaN
3,Folate (red blood cell),Ecuador,2012,Adolescents,Female,nmol/L,1.2,846.35,<342 nmol/L,776.11,NaN,NaN,878.98,813.49
4,Folate (red blood cell),Ecuador,2012,Adolescents,Female,nmol/L,0.8,860.17,<342 nmol/L,772.48,NaN,NaN,898.47,821.65
5,Folate (red blood cell),Ecuador,2012,Adolescents,Male,nmol/L,NaN,893.03,NaN,815.31,NaN,NaN,929.06,856.77
6,Folate (red blood cell),Ecuador,2012,Adolescents,Male,nmol/L,NaN,799.44,NaN,731.69,NaN,NaN,831.40,767.49
7,Folate (red blood cell),Ecuador,2012,Adults,All,NaN,1.1,NaN,<342 nmol/L,NaN,NaN,NaN,NaN,NaN
8,Folate (red blood cell),Ecuador,2012,Adults,All,NaN,1.1,NaN,<342 nmol/L,NaN,NaN,NaN,NaN,NaN
9,Folate (red blood cell),Ecuador,2012,Adults,All,NaN,0.1,NaN,<342 nmol/L,NaN,NaN,NaN,NaN,NaN
10,Folate (red blood cell),Ecuador,2012,Adults,All,NaN,0.2,NaN,<342 nmol/L,NaN,NaN,NaN,NaN,NaN
11,Folate (red blood cell),Ecuador,2012,Men,Male,nmol/L,NaN,850.20,NaN,795.82,NaN,NaN,887.14,813.27
12,Folate (red blood cell),Ecuador,2012,Men,Male,nmol/L,NaN,911.39,NaN,849.52,NaN,NaN,941.52,881.47
13,Folate (red blood cell),Ecuador,2012,Men,Male,nmol/L,NaN,959.65,NaN,887.59,NaN,NaN,996.59,922.49
14,Folate (red blood cell),Ecuador,2012,Men,Male,nmol/L,NaN,1029.22,NaN,913.42,NaN,NaN,1106.49,951.95

In [309]:
(df123["Country"] + ", " + df123["Population"]).value_counts()

United Kingdom of Great Britain and Northern, Elderly    9
Ireland, Adults                                          8
Nepal, Adolescents                                       8
Ecuador, Adolescents                                     6
United Kingdom of Great Britain and Northern, Men        5
New Zealand, Men                                         4
Ecuador, Men                                             4
Ecuador, Adults                                          4
New Zealand, Adolescents                                 3
Ireland, Elderly                                         3
New Zealand, Elderly                                     2
New Zealand, Adults                                      2
Ecuador, Women                                           1
New Zealand, Women                                       1
Australia, Adults                                        1
dtype: int64

In [310]:
df123.Country.value_counts()

Ecuador                                         15
United Kingdom of Great Britain and Northern    14
New Zealand                                     12
Ireland                                         11
Nepal                                            8
Australia                                        1
Name: Country, dtype: int64

In [311]:
df124.info()
df124.head().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 47 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Indicator.                                                        6 non-null      object
 1   CountryCode                                                       6 non-null      object
 2   Country                                                           6 non-null      object
 3   Representativeness.                                               6 non-null      object
 4   Representativeness name                                           0 non-null      float64
 5   Area covered                                                      6 non-null      object
 6   Date                                                              6 non-null      int64
 7   Begin month                                                       5 non-null      float64
 8   Begin year                                                        6 non-null      int64
 9   End month                                                         5 non-null      float64
 10  End year                                                          6 non-null      int64
 11  Population                                                        6 non-null      object
 12  Gender                                                            6 non-null      object
 13  Age unit                                                          6 non-null      object
 14  Age from                                                          6 non-null      int64
 15  Age to                                                            6 non-null      int64
 16  Sample size                                                       6 non-null      int64
 17  Indicator unit                                                    5 non-null      object
 18  Mean                                                              0 non-null      float64
 19  Geo mean                                                          0 non-null      float64
 20  Median                                                            5 non-null      float64
 21  SD                                                                0 non-null      float64
 22  SE                                                                0 non-null      float64
 23  L95CI                                                             0 non-null      float64
 24  U95CI                                                             0 non-null      float64
 25  Prevalence >97th percentile of reference population based on age  1 non-null      float64
 26  Prevalence >97th percentile of reference population based on BSA  0 non-null      float64
 27  Method of analysis                                                6 non-null      object
 28  Data adjusted for                                                 6 non-null      object
 29  General data comments                                             0 non-null      float64
 30  Indicator comments                                                6 non-null      object
 31  Survey methodology                                                6 non-null      object
 32  Season                                                            6 non-null      object
 33  Old Reference no# 1                                               6 non-null      int64
 34  Reference no# 1                                                   6 non-null      int64
 35  Reference 1                                                       6 non-null      object
 36  Link to reference 1                                               5 non-null      object
 37  Old Reference no# 2                                               5 non-null      float64
 38  Reference no# 2                                                   5 non-null      float64
 39  Reference 2                                                       5 non-null      object
 40  Link to reference 2                                               0 non-null      float64
 41  Old Reference no# 3                                               5 non-null      float64
 42  Reference no# 3                                                   5 non-null      float64
 43  Reference 3                                                       5 non-null      object
 44  Link to reference 3                                               5 non-null      object
 45  SurveyId                                                          6 non-null      int64
 46  Survey status                                                     6 non-null      object
dtypes: float64(18), int64(9), object(20)
memory usage: 2.3+ KB

,0,1,2,3,4
Indicator.,Goitre by ultrasound,Goitre by ultrasound,Goitre by ultrasound,Goitre by ultrasound,Goitre by ultrasound
CountryCode,FRA,FRA,FRA,FRA,FRA
Country,France,France,France,France,France
Representativeness.,national,national,national,national,national
Representativeness name,NaN,NaN,NaN,NaN,NaN
Area covered,both urban and rural,both urban and rural,both urban and rural,both urban and rural,both urban and rural
Date,1995,1995,1995,1995,1995
Begin month,12,12,12,12,12
Begin year,1994,1994,1994,1994,1994
End month,12,12,12,12,12
End year,1995,1995,1995,1995,1995
Population,Men,Men,Men,Women,Women
Gender,Male,Male,Male,Female,Female
Age unit,Year,Year,Year,Year,Year
Age from,45,50,55,50,55
Age to,49,54,59,54,59
Sample size,438,361,442,299,288
Indicator unit,mL,mL,mL,mL,mL
Mean,NaN,NaN,NaN,NaN,NaN
Geo mean,NaN,NaN,NaN,NaN,NaN
Median,13.3,13.3,12.8,8.8,8.3
SD,NaN,NaN,NaN,NaN,NaN
SE,NaN,NaN,NaN,NaN,NaN
L95CI,NaN,NaN,NaN,NaN,NaN
U95CI,NaN,NaN,NaN,NaN,NaN
Prevalence >97th percentile of reference population based on age,NaN,NaN,NaN,NaN,NaN
Prevalence >97th percentile of reference population based on BSA,NaN,NaN,NaN,NaN,NaN
Method of analysis,Ultrasound,Ultrasound,Ultrasound,Ultrasound,Ultrasound
Data adjusted for,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable
General data comments,NaN,NaN,NaN,NaN,NaN
Indicator comments,Thyroid volume estimated using a high frequenc...,Thyroid volume estimated using a high frequenc...,Thyroid volume estimated using a high frequenc...,Thyroid volume estimated using a high frequenc...,Thyroid volume estimated using a high frequenc...
Survey methodology,Randomized double-blind trial designed to test...,Randomized double-blind trial designed to test...,Randomized double-blind trial designed to test...,Randomized double-blind trial designed to test...,Randomized double-blind trial designed to test...
Season,All seasons,All seasons,All seasons,All seasons,All seasons
Old Reference no# 1,1269,1269,1269,1269,1269
Reference no# 1,606,606,606,606,606
Reference 1,"Valeix P, Zarebska M, Preziosi P, Galan P, Pel...","Valeix P, Zarebska M, Preziosi P, Galan P, Pel...","Valeix P, Zarebska M, Preziosi P, Galan P, Pel...","Valeix P, Zarebska M, Preziosi P, Galan P, Pel...","Valeix P, Zarebska M, Preziosi P, Galan P, Pel..."
Link to reference 1,https://www.thelancet.com/pdfs/journals/lancet...,https://www.thelancet.com/pdfs/journals/lancet...,https://www.thelancet.com/pdfs/journals/lancet...,https://www.thelancet.com/pdfs/journals/lancet...,https://www.thelancet.com/pdfs/journals/lancet...
Old Reference no# 2,1270,1270,1270,1270,1270
Reference no# 2,608,608,608,608,608
Reference 2,"Barrère X, Valeix P, Preziosi P, Bensimon M, P...","Barrère X, Valeix P, Preziosi P, Bensimon M, P...","Barrère X, Valeix P, Preziosi P, Bensimon M, P...","Barrère X, Valeix P, Preziosi P, Bensimon M, P...","Barrère X, Valeix P, Preziosi P, Bensimon M, P..."
Link to reference 2,NaN,NaN,NaN,NaN,NaN
Old Reference no# 3,5307,5307,5307,5307,5307
Reference no# 3,609,609,609,609,609
Reference 3,"Faure H, Preziosi P, Roussel AM, Bertrais S, G...","Faure H, Preziosi P, Roussel AM, Bertrais S, G...","Faure H, Preziosi P, Roussel AM, Bertrais S, G...","Faure H, Preziosi P, Roussel AM, Bertrais S, G...","Faure H, Preziosi P, Roussel AM, Bertrais S, G..."
Link to reference 3,https://www.nature.com/articles/1602372,https://www.nature.com/articles/1602372,https://www.nature.com/articles/1602372,https://www.nature.com/articles/1602372,https://www.nature.com/articles/1602372
SurveyId,10537,10537,10537,10537,10537
Survey status,verified,verified,verified,verified,verified

Checking for missing values:

In [312]:
missing = pd.concat([df124.isnull().sum(), 100 * df124.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                                                    count           %
Indicator.                                              0    0.000000
Reference 1                                             0    0.000000
Reference no# 1                                         0    0.000000
Old Reference no# 1                                     0    0.000000
Season                                                  0    0.000000
Survey methodology                                      0    0.000000
Indicator comments                                      0    0.000000
Data adjusted for                                       0    0.000000
Method of analysis                                      0    0.000000
SurveyId                                                0    0.000000
Sample size                                             0    0.000000
Age to                                                  0    0.000000
Age from                                                0    0.000000
Survey status                                           0    0.000000
Gender                                                  0    0.000000
CountryCode                                             0    0.000000
Country                                                 0    0.000000
Representativeness.                                     0    0.000000
Area covered                                            0    0.000000
Age unit                                                0    0.000000
Begin year                                              0    0.000000
Date                                                    0    0.000000
End year                                                0    0.000000
Population                                              0    0.000000
End month                                               1   16.666667
Link to reference 3                                     1   16.666667
Reference 3                                             1   16.666667
Median                                                  1   16.666667
Begin month                                             1   16.666667
Reference no# 3                                         1   16.666667
Old Reference no# 3                                     1   16.666667
Reference 2                                             1   16.666667
Indicator unit                                          1   16.666667
Reference no# 2                                         1   16.666667
Link to reference 1                                     1   16.666667
Old Reference no# 2                                     1   16.666667
Prevalence >97th percentile of reference popula...      5   83.333333
Link to reference 2                                     6  100.000000
SE                                                      6  100.000000
Representativeness name                                 6  100.000000
Mean                                                    6  100.000000
Geo mean                                                6  100.000000
General data comments                                   6  100.000000
Prevalence >97th percentile of reference popula...      6  100.000000
U95CI                                                   6  100.000000
SD                                                      6  100.000000
L95CI                                                   6  100.000000

In [313]:
df124.Country.unique()

array(['France', 'Slovakia'], dtype=object)

In [314]:
df124['Begin year'].unique()

array([1994, 1988])

Another indicator with too little data to use for this project.

In [315]:
df125.info()
df125.head().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1247 entries, 0 to 1246
Data columns (total 53 columns):
 #   Column                                                                                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                                                                                          --------------  -----
 0   Applied filters:
Micronutrient is Anaemia
Representativeness is national
Population Group is Adolescents, Adults, Men, Elderly, or Women
Year is greater than or equal to 1990  1246 non-null   object
 1   Unnamed: 1                                                                                                                                                                      1246 non-null   object
 2   Unnamed: 2                                                                                                                                                                      1246 non-null   object
 3   Unnamed: 3                                                                                                                                                                      1246 non-null   object
 4   Unnamed: 4                                                                                                                                                                      1 non-null      object
 5   Unnamed: 5                                                                                                                                                                      1246 non-null   object
 6   Unnamed: 6                                                                                                                                                                      1246 non-null   object
 7   Unnamed: 7                                                                                                                                                                      981 non-null    object
 8   Unnamed: 8                                                                                                                                                                      1241 non-null   object
 9   Unnamed: 9                                                                                                                                                                      981 non-null    object
 10  Unnamed: 10                                                                                                                                                                     1246 non-null   object
 11  Unnamed: 11                                                                                                                                                                     1246 non-null   object
 12  Unnamed: 12                                                                                                                                                                     1246 non-null   object
 13  Unnamed: 13                                                                                                                                                                     1246 non-null   object
 14  Unnamed: 14                                                                                                                                                                     1232 non-null   object
 15  Unnamed: 15                                                                                                                                                                     1075 non-null   object
 16  Unnamed: 16                                                                                                                                                                     1096 non-null   object
 17  Unnamed: 17                                                                                                                                                                     546 non-null    object
 18  Unnamed: 18                                                                                                                                                                     531 non-null    object
 19  Unnamed: 19                                                                                                                                                                     17 non-null     object
 20  Unnamed: 20                                                                                                                                                                     69 non-null     object
 21  Unnamed: 21                                                                                                                                                                     325 non-null    object
 22  Unnamed: 22                                                                                                                                                                     9 non-null      object
 23  Unnamed: 23                                                                                                                                                                     192 non-null    object
 24  Unnamed: 24                                                                                                                                                                     192 non-null    object
 25  Unnamed: 25                                                                                                                                                                     1052 non-null   object
 26  Unnamed: 26                                                                                                                                                                     1052 non-null   object
 27  Unnamed: 27                                                                                                                                                                     339 non-null    object
 28  Unnamed: 28                                                                                                                                                                     339 non-null    object
 29  Unnamed: 29                                                                                                                                                                     371 non-null    object
 30  Unnamed: 30                                                                                                                                                                     371 non-null    object
 31  Unnamed: 31                                                                                                                                                                     366 non-null    object
 32  Unnamed: 32                                                                                                                                                                     366 non-null    object
 33  Unnamed: 33                                                                                                                                                                     1246 non-null   object
 34  Unnamed: 34                                                                                                                                                                     1246 non-null   object
 35  Unnamed: 35                                                                                                                                                                     1246 non-null   object
 36  Unnamed: 36                                                                                                                                                                     433 non-null    object
 37  Unnamed: 37                                                                                                                                                                     1245 non-null   object
 38  Unnamed: 38                                                                                                                                                                     1140 non-null   object
 39  Unnamed: 39                                                                                                                                                                     596 non-null    object
 40  Unnamed: 40                                                                                                                                                                     1246 non-null   object
 41  Unnamed: 41                                                                                                                                                                     1246 non-null   object
 42  Unnamed: 42                                                                                                                                                                     832 non-null    object
 43  Unnamed: 43                                                                                                                                                                     86 non-null     object
 44  Unnamed: 44                                                                                                                                                                     367 non-null    object
 45  Unnamed: 45                                                                                                                                                                     367 non-null    object
 46  Unnamed: 46                                                                                                                                                                     239 non-null    object
 47  Unnamed: 47                                                                                                                                                                     24 non-null     object
 48  Unnamed: 48                                                                                                                                                                     180 non-null    object
 49  Unnamed: 49                                                                                                                                                                     180 non-null    object
 50  Unnamed: 50                                                                                                                                                                     122 non-null    object
 51  Unnamed: 51                                                                                                                                                                     1246 non-null   object
 52  Unnamed: 52                                                                                                                                                                     1246 non-null   object
dtypes: object(53)
memory usage: 516.5+ KB

,0,1,2,3,4
"Applied filters:\nMicronutrient is Anaemia\nRepresentativeness is national\nPopulation Group is Adolescents, Adults, Men, Elderly, or Women\nYear is greater than or equal to 1990",NaN,Indicator.,Haemoglobin,Haemoglobin,Haemoglobin
Unnamed: 1,NaN,CountryCode,AFG,AFG,AFG
Unnamed: 2,NaN,Country,Afghanistan,Afghanistan,Afghanistan
Unnamed: 3,NaN,Representativeness.,national,national,national
Unnamed: 4,NaN,Representativeness name,NaN,NaN,NaN
Unnamed: 5,NaN,Area covered,both urban and rural,both urban and rural,both urban and rural
Unnamed: 6,NaN,Date,2004,2004,2004
Unnamed: 7,NaN,Begin month,5,5,5
Unnamed: 8,NaN,Begin year,2004,2004,2004
Unnamed: 9,NaN,End month,6,6,6
Unnamed: 10,NaN,End year,2004,2004,2004
Unnamed: 11,NaN,Population,Adolescents,Adolescents,Men
Unnamed: 12,NaN,Gender,Female,Male,Male
Unnamed: 13,NaN,Age unit,Year,Year,Year
Unnamed: 14,NaN,Age from,15,18,18
Unnamed: 15,NaN,Age to,19,19,60
Unnamed: 16,NaN,Sample size,314,58,576
Unnamed: 17,NaN,Indicator unit,g/L,g/L,g/L
Unnamed: 18,NaN,Mean,130,154,153
Unnamed: 19,NaN,Geo mean,NaN,NaN,NaN
Unnamed: 20,NaN,Median,NaN,NaN,NaN
Unnamed: 21,NaN,SD,15,13,15
Unnamed: 22,NaN,SE,NaN,NaN,NaN
Unnamed: 23,NaN,L95CI,NaN,NaN,NaN
Unnamed: 24,NaN,U95CI,NaN,NaN,NaN
Unnamed: 25,NaN,Anaemia cut-off,<120 g/L,<120 g/L,<130 g/L
Unnamed: 26,NaN,Anaemia prevalence,20.4,4.3,7.1
Unnamed: 27,NaN,Mild anaemia cut-off,NaN,NaN,NaN
Unnamed: 28,NaN,Mild anaemia prevalence,NaN,NaN,NaN
Unnamed: 29,NaN,Moderate anaemia cut-off,NaN,NaN,NaN
Unnamed: 30,NaN,Moderate anaemia prevalence,NaN,NaN,NaN
Unnamed: 31,NaN,Severe anaemia cut-off,NaN,NaN,NaN
Unnamed: 32,NaN,Severe anaemia prevalence,NaN,NaN,NaN
Unnamed: 33,NaN,Sample collection method,Capillary puncture,Capillary puncture,Capillary puncture
Unnamed: 34,NaN,Method of analysis,Colorimetry (Hemocue),Colorimetry (Hemocue),Colorimetry (Hemocue)
Unnamed: 35,NaN,Data adjusted for,Altitude and smoking,Altitude and smoking,Altitude and smoking
Unnamed: 36,NaN,General data comments,NaN,NaN,NaN
Unnamed: 37,NaN,Indicator comments,Quality control of HemoCue instruments perform...,Quality control of HemoCue instruments perform...,Quality control of HemoCue instruments perform...
Unnamed: 38,NaN,Survey methodology,Final data collected on 32 of the 39 selected ...,Final data collected on 32 of the 39 selected ...,Final data collected on 32 of the 39 selected ...
Unnamed: 39,NaN,Old Reference no# 1,5173,5173,5173
Unnamed: 40,NaN,Reference no# 1,131,131,131
Unnamed: 41,NaN,Reference 1,Ministry of Public Health of the Islamic Repub...,Ministry of Public Health of the Islamic Repub...,Ministry of Public Health of the Islamic Repub...
Unnamed: 42,NaN,Link to reference 1,NaN,NaN,NaN
Unnamed: 43,NaN,Old Reference no# 2,NaN,NaN,NaN
Unnamed: 44,NaN,Reference no# 2,NaN,NaN,NaN
Unnamed: 45,NaN,Reference 2,NaN,NaN,NaN
Unnamed: 46,NaN,Link to reference 2,NaN,NaN,NaN
Unnamed: 47,NaN,Old Reference no# 3,NaN,NaN,NaN
Unnamed: 48,NaN,Reference no# 3,NaN,NaN,NaN
Unnamed: 49,NaN,Reference 3,NaN,NaN,NaN
Unnamed: 50,NaN,Link to reference 3,NaN,NaN,NaN
Unnamed: 51,NaN,SurveyId,10120,10120,10120
Unnamed: 52,NaN,Survey status,verified,verified,verified

In [316]:
df125.head()

,"Applied filters:\nMicronutrient is Anaemia\nRepresentativeness is national\nPopulation Group is Adolescents, Adults, Men, Elderly, or Women\nYear is greater than or equal to 1990",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
2,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
3,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
4,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified

In [317]:
df125.drop(labels=[0], axis=0, inplace=True)
df125.head()

,"Applied filters:\nMicronutrient is Anaemia\nRepresentativeness is national\nPopulation Group is Adolescents, Adults, Men, Elderly, or Women\nYear is greater than or equal to 1990",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
1,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
2,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
3,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
4,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
5,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified

In [318]:
df125.columns = df125.iloc[0]
df125 = df125[1:]
df125.head()

1,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
2,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
3,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
4,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
5,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
6,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified

In [319]:
df125.reset_index(inplace=True)
df125.head()

1,index,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,2,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
1,3,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
2,4,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
3,5,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
4,6,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified

In [320]:
df125.drop(labels='index', axis=1, inplace=True)
df125.head()

1,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
1,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
2,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
3,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified
4,Haemoglobin,AFG,Afghanistan,national,NaN,both urban and rural,2004,5,2004,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10120,verified

Checking for missing values:

In [321]:
missing = pd.concat([df125.isnull().sum(), 100 * df125.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                             count           %
1
Indicator.                       0    0.000000
Reference 1                      0    0.000000
Reference no# 1                  0    0.000000
Data adjusted for                0    0.000000
Method of analysis               0    0.000000
Sample collection method         0    0.000000
SurveyId                         0    0.000000
Age unit                         0    0.000000
Gender                           0    0.000000
Population                       0    0.000000
Survey status                    0    0.000000
CountryCode                      0    0.000000
Country                          0    0.000000
Representativeness.              0    0.000000
Area covered                     0    0.000000
End year                         0    0.000000
Date                             0    0.000000
Indicator comments               1    0.080321
Begin year                       5    0.401606
Age from                        14    1.124498
Survey methodology             106    8.514056
Sample size                    150   12.048193
Age to                         171   13.734940
Anaemia prevalence             194   15.582329
Anaemia cut-off                194   15.582329
End month                      265   21.285141
Begin month                    265   21.285141
Link to reference 1            414   33.253012
Old Reference no# 1            650   52.208835
Indicator unit                 700   56.224900
Mean                           715   57.429719
General data comments          813   65.301205
Moderate anaemia cut-off       875   70.281124
Moderate anaemia prevalence    875   70.281124
Reference 2                    879   70.602410
Reference no# 2                879   70.602410
Severe anaemia cut-off         880   70.682731
Severe anaemia prevalence      880   70.682731
Mild anaemia prevalence        907   72.851406
Mild anaemia cut-off           907   72.851406
SD                             921   73.975904
Link to reference 2           1007   80.883534
U95CI                         1054   84.658635
L95CI                         1054   84.658635
Reference no# 3               1066   85.622490
Reference 3                   1066   85.622490
Link to reference 3           1124   90.281124
Old Reference no# 2           1160   93.172691
Median                        1177   94.538153
Old Reference no# 3           1222   98.152610
Geo mean                      1229   98.714859
SE                            1237   99.357430
Representativeness name       1245  100.000000

In [322]:
df125.Country.unique()

array(['Afghanistan', 'Albania.', 'Armenia', 'Australia', 'Austria',
       'Azerbaijan', 'Burundi', 'Benin', 'Burkina Faso', 'Bangladesh',
       'Bahrain', 'Belize', 'Bolivia (Plurinational State of)', 'Brazil',
       'Brunei Darussalam', 'Bhutan', 'Central African Republic',
       'Canada', 'Chile', 'China', "Côte d'Ivoire", 'Cameroon',
       'Democratic Republic of the Congo', 'Congo', 'Colombia',
       'Cabo Verde', 'Costa Rica', 'Dominica', 'Dominican Republic',
       'Ecuador', 'Egypt', 'Ethiopia', 'Fiji', 'France', 'Gabon',
       'United Kingdom of Great Britain and Northern', 'Guinea',
       'Equatorial Guinea', 'Guyana', 'Haiti', 'Indonesia', 'India',
       'Japan', 'Kenya', 'Kuwait', "Lao People's Democratic Republic",
       'Sri Lanka', 'Lesotho', 'Morocco', 'Republic of Moldova',
       'Madagascar', 'Maldives', 'Mexico', 'Mali', 'Myanmar', 'Mauritius',
       'Malawi', 'Namibia', 'Niger', 'Nepal', 'New Zealand', 'Oman',
       'Peru', 'Philippines', 'Papua New Guinea',
       'West Bank and Gaza Strip', 'Rwanda', 'Senegal', 'Sierra Leone',
       'Sao Tome and Principe', 'Eswatini', 'Togo', 'Thailand',
       'Tajikistan', 'Timor-Leste', 'Tuvalu', 'Uganda', 'Viet Nam',
       'South Africa', 'Zambia', 'Zimbabwe'], dtype=object)

In [323]:
df125['Begin year'].unique()

array(['2004', '2013', '2008', '2000', '2005', '2015', '2011', '2010',
       '1996', '2006', '2003', '2016', '2001', '1997', '1998', '2002',
       '2009', '1992', '1995', '2007', '1993', '2012', '2014', '1994',
       '1999', nan, '2017'], dtype=object)

In [324]:
labels=["Indicator.", "Country", "Date", "Population", "Gender", "Indicator unit", "Anaemia prevalence", "Mean", "Anaemia cut-off", "Median", "U95CI", "L95CI"]
df125=df125[labels]

In [325]:
df125.shape
df125.head(15)

1,Indicator.,Country,Date,Population,Gender,Indicator unit,Anaemia prevalence,Mean,Anaemia cut-off,Median,U95CI,L95CI
0,Haemoglobin,Afghanistan,2004,Adolescents,Female,g/L,20.4,130,<120 g/L,NaN,NaN,NaN
1,Haemoglobin,Afghanistan,2004,Adolescents,Male,g/L,4.3,154,<120 g/L,NaN,NaN,NaN
2,Haemoglobin,Afghanistan,2004,Men,Male,g/L,7.1,153,<130 g/L,NaN,NaN,NaN
3,Haemoglobin,Afghanistan,2004,Men,Male,g/L,3.8,156,<130 g/L,NaN,NaN,NaN
4,Haemoglobin,Afghanistan,2004,Men,Male,g/L,10.8,151,<130 g/L,NaN,NaN,NaN
5,Haemoglobin,Afghanistan,2004,Men,Male,g/L,8.2,151,<130 g/L,NaN,NaN,NaN
6,Haemoglobin,Afghanistan,2004,Men,Male,g/L,8.2,150,<130 g/L,NaN,NaN,NaN
7,Haemoglobin,Afghanistan,2013,Adolescents,Female,g/L,30.9,124.7,<120 g/L,NaN,NaN,NaN
8,Haemoglobin,Albania.,2009,Adolescents,Female,NaN,17.9,NaN,<120 g/L,NaN,NaN,NaN
9,Haemoglobin,Albania.,2009,Adolescents,Male,NaN,6,NaN,<130 g/L,NaN,NaN,NaN
10,Haemoglobin,Albania.,2009,Men,Male,NaN,4.7,NaN,<130 g/L,NaN,NaN,NaN
11,Haemoglobin,Albania.,2009,Men,Male,NaN,4.4,NaN,<130 g/L,NaN,NaN,NaN
12,Haemoglobin,Albania.,2009,Men,Male,NaN,5.9,NaN,<130 g/L,NaN,NaN,NaN
13,Haemoglobin,Albania.,2009,Men,Male,NaN,3.4,NaN,<130 g/L,NaN,NaN,NaN
14,Haemoglobin,Albania.,2009,Men,Male,NaN,6.2,NaN,<130 g/L,NaN,NaN,NaN

In [326]:
(df125["Country"] + ", " + df125["Population"]).value_counts()

China, Adolescents          86
Kuwait, Adolescents         36
Bangladesh, Adolescents     35
Uganda, Men                 28
Egypt, Adolescents          27
                            ..
Cameroon, Adolescents        1
Zambia, Men                  1
Egypt, Men                   1
Dominica, Adolescents        1
Brunei Darussalam, Women     1
Length: 159, dtype: int64

In [327]:
df125.Country.value_counts()

China                               121
Thailand                             80
Japan                                71
Kuwait                               36
Bangladesh                           35
                                   ...
Republic of Moldova                   1
Brazil                                1
Mauritius                             1
Bolivia (Plurinational State of)      1
Tajikistan                            1
Name: Country, Length: 81, dtype: int64

In [328]:
df126.info()
df126.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 51 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Indicator.                         54 non-null     object
 1   CountryCode                        54 non-null     object
 2   Country                            54 non-null     object
 3   Representativeness.                54 non-null     object
 4   Representativeness name            0 non-null      float64
 5   Area covered                       54 non-null     object
 6   Date                               54 non-null     int64
 7   Begin month                        54 non-null     int64
 8   Begin year                         54 non-null     int64
 9   End month                          54 non-null     int64
 10  End year                           54 non-null     int64
 11  Population                         54 non-null     object
 12  Gender                             54 non-null     object
 13  Age unit                           54 non-null     object
 14  Age from                           53 non-null     float64
 15  Age to                             48 non-null     float64
 16  Sample size                        42 non-null     float64
 17  Indicator unit                     43 non-null     object
 18  Mean                               32 non-null     float64
 19  Geo mean                           0 non-null      float64
 20  Median                             16 non-null     float64
 21  SD                                 19 non-null     float64
 22  SE                                 0 non-null      float64
 23  L95CI                              24 non-null     float64
 24  U95CI                              24 non-null     float64
 25  Elevated threshold                 28 non-null     object
 26  Prevalence of elevated Hcy         28 non-null     float64
 27  Mildly elevated threshold          5 non-null      object
 28  Prevalence of mildly elevated Hcy  5 non-null      float64
 29  Sample type                        54 non-null     object
 30  Fasting                            54 non-null     object
 31  Method of analysis                 54 non-null     object
 32  Data adjusted for                  54 non-null     object
 33  General data comments              10 non-null     object
 34  Indicator comments                 54 non-null     object
 35  Survey methodology                 54 non-null     object
 36  Season                             54 non-null     object
 37  Old Reference no# 1                5 non-null      float64
 38  Reference no# 1                    54 non-null     int64
 39  Reference 1                        54 non-null     object
 40  Link to reference 1                40 non-null     object
 41  Old Reference no# 2                5 non-null      float64
 42  Reference no# 2                    40 non-null     float64
 43  Reference 2                        40 non-null     object
 44  Link to reference 2                40 non-null     object
 45  Old Reference no# 3                0 non-null      float64
 46  Reference no# 3                    40 non-null     float64
 47  Reference 3                        40 non-null     object
 48  Link to reference 3                27 non-null     object
 49  SurveyId                           54 non-null     int64
 50  Survey status                      54 non-null     object
dtypes: float64(18), int64(7), object(26)
memory usage: 21.6+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Homocysteine,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
1,Homocysteine,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
2,Homocysteine,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
3,Homocysteine,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
4,Homocysteine,CAN,Canada,national,NaN,both urban and rural,2009,3,2007,2,...,NaN,744.0,2007-2009 Canadian Health Measures Survey: cyc...,http://www.statcan.gc.ca/pub/82-623-x/82-623-x...,NaN,745.0,Canadian Health Measures Survey (CHMS) data us...,http://www23.statcan.gc.ca/imdb-bmdi/document/...,10808,verified

Checking for missing values:

In [329]:
missing = pd.concat([df126.isnull().sum(), 100 * df126.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                                   count           %
Indicator.                             0    0.000000
Reference 1                            0    0.000000
Reference no# 1                        0    0.000000
Season                                 0    0.000000
Survey methodology                     0    0.000000
Indicator comments                     0    0.000000
Data adjusted for                      0    0.000000
Method of analysis                     0    0.000000
Fasting                                0    0.000000
Sample type                            0    0.000000
SurveyId                               0    0.000000
Age unit                               0    0.000000
Survey status                          0    0.000000
Population                             0    0.000000
CountryCode                            0    0.000000
Country                                0    0.000000
Representativeness.                    0    0.000000
Area covered                           0    0.000000
Date                                   0    0.000000
Gender                                 0    0.000000
Begin year                             0    0.000000
End month                              0    0.000000
End year                               0    0.000000
Begin month                            0    0.000000
Age from                               1    1.851852
Age to                                 6   11.111111
Indicator unit                        11   20.370370
Sample size                           12   22.222222
Reference 3                           14   25.925926
Reference no# 3                       14   25.925926
Link to reference 2                   14   25.925926
Reference 2                           14   25.925926
Reference no# 2                       14   25.925926
Link to reference 1                   14   25.925926
Mean                                  22   40.740741
Elevated threshold                    26   48.148148
Prevalence of elevated Hcy            26   48.148148
Link to reference 3                   27   50.000000
U95CI                                 30   55.555556
L95CI                                 30   55.555556
SD                                    35   64.814815
Median                                38   70.370370
General data comments                 44   81.481481
Old Reference no# 2                   49   90.740741
Prevalence of mildly elevated Hcy     49   90.740741
Mildly elevated threshold             49   90.740741
Old Reference no# 1                   49   90.740741
Representativeness name               54  100.000000
Geo mean                              54  100.000000
Old Reference no# 3                   54  100.000000
SE                                    54  100.000000

In [330]:
df126.Country.unique()

array(['Austria', 'Canada', 'Ireland', 'Costa Rica',
       'United Kingdom of Great Britain and Northern'], dtype=object)

In [331]:
df126['Begin year'].unique()

array([2010, 2007, 2008, 2000])

In [332]:
labels=["Indicator.", "Country", "Date", "Population", "Gender", "Elevated threshold", "Prevalence of elevated Hcy", "Mean", "Median", "U95CI", "L95CI"]
df126=df126[labels]

In [333]:
df126.shape
df126.head(15)

,Indicator.,Country,Date,Population,Gender,Elevated threshold,Prevalence of elevated Hcy,Mean,Median,U95CI,L95CI
0,Homocysteine,Austria,2012,Adolescents,Female,NaN,NaN,8.7,NaN,9.0,8.3
1,Homocysteine,Austria,2012,Adolescents,Female,NaN,NaN,8.8,NaN,9.6,8.0
2,Homocysteine,Austria,2012,Adolescents,Male,NaN,NaN,9.4,NaN,9.8,9.0
3,Homocysteine,Austria,2012,Adolescents,Male,NaN,NaN,10.1,NaN,10.9,9.3
4,Homocysteine,Canada,2009,Adolescents,All,NaN,NaN,NaN,NaN,NaN,NaN
5,Homocysteine,Canada,2009,Adolescents,Female,>13 µmol/L,0.0,NaN,NaN,NaN,NaN
6,Homocysteine,Canada,2009,Adolescents,Male,NaN,NaN,NaN,NaN,NaN,NaN
7,Homocysteine,Canada,2009,Adults,All,>13 µmol/L,3.2,NaN,NaN,NaN,NaN
8,Homocysteine,Canada,2009,Adults,All,>13 µmol/L,5.8,NaN,NaN,NaN,NaN
9,Homocysteine,Ireland,2010,Adults,All,NaN,NaN,NaN,11.4,NaN,NaN
10,Homocysteine,Ireland,2010,Adults,All,NaN,NaN,NaN,11.8,NaN,NaN
11,Homocysteine,Ireland,2010,Adults,All,NaN,NaN,NaN,12.4,NaN,NaN
12,Homocysteine,Ireland,2010,Adults,Female,NaN,NaN,NaN,11.1,NaN,NaN
13,Homocysteine,Ireland,2010,Adults,Female,NaN,NaN,NaN,11.7,NaN,NaN
14,Homocysteine,Ireland,2010,Adults,Male,NaN,NaN,NaN,12.0,NaN,NaN

In [334]:
(df126["Country"] + ", " + df126["Population"]).value_counts()

Ireland, Adults                                      8
Costa Rica, Elderly                                  6
United Kingdom of Great Britain and Northern, Men    5
Costa Rica, Women                                    4
Austria, Adolescents                                 4
Austria, Men                                         4
Costa Rica, Men                                      4
Austria, Elderly                                     3
Canada, Adolescents                                  3
Canada, Elderly                                      3
Ireland, Elderly                                     3
Austria, Women                                       2
Canada, Adults                                       2
Canada, Men                                          2
Canada, Women                                        1
dtype: int64

In [335]:
df126.Country.value_counts()

Costa Rica                                      14
Austria                                         13
Canada                                          11
Ireland                                         11
United Kingdom of Great Britain and Northern     5
Name: Country, dtype: int64

In [336]:
df127.info()
df127.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Indicator.                106 non-null    object
 1   CountryCode               106 non-null    object
 2   Country                   106 non-null    object
 3   Representativeness.       106 non-null    object
 4   Representativeness name   0 non-null      float64
 5   Area covered              106 non-null    object
 6   Date                      106 non-null    int64
 7   Begin month               95 non-null     float64
 8   Begin year                106 non-null    int64
 9   End month                 95 non-null     float64
 10  End year                  106 non-null    int64
 11  Population                106 non-null    object
 12  Gender                    106 non-null    object
 13  Age unit                  106 non-null    object
 14  Age from                  106 non-null    int64
 15  Age to                    92 non-null     float64
 16  Sample size               76 non-null     float64
 17  Indicator unit            101 non-null    object
 18  Mean                      28 non-null     float64
 19  Geo mean                  11 non-null     float64
 20  Median                    78 non-null     float64
 21  SD                        3 non-null      float64
 22  SE                        8 non-null      float64
 23  L95CI                     46 non-null     float64
 24  U95CI                     46 non-null     float64
 25  Sample type               106 non-null    object
 26  Fasting                   106 non-null    object
 27  Sample collection method  106 non-null    object
 28  Method of analysis        106 non-null    object
 29  Data adjusted for         106 non-null    object
 30  General data comments     39 non-null     object
 31  Indicator comments        106 non-null    object
 32  Survey methodology        106 non-null    object
 33  Old Reference no# 1       23 non-null     float64
 34  Reference no# 1           106 non-null    int64
 35  Reference 1               106 non-null    object
 36  Link to reference 1       96 non-null     object
 37  Old Reference no# 2       14 non-null     float64
 38  Reference no# 2           87 non-null     float64
 39  Reference 2               87 non-null     object
 40  Link to reference 2       78 non-null     object
 41  Old Reference no# 3       10 non-null     float64
 42  Reference no# 3           83 non-null     float64
 43  Reference 3               83 non-null     object
 44  Link to reference 3       57 non-null     object
 45  SurveyId                  106 non-null    int64
 46  Survey status             106 non-null    object
dtypes: float64(17), int64(6), object(24)
memory usage: 39.0+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Iodine,BEL,Belgium,national,NaN,both urban and rural,2018,4.0,2018,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11332,verified
1,Iodine,BEL,Belgium,national,NaN,both urban and rural,2018,4.0,2018,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11332,verified
2,Iodine,BEL,Belgium,national,NaN,both urban and rural,2018,4.0,2018,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11332,verified
3,Iodine,BEL,Belgium,national,NaN,both urban and rural,2018,4.0,2018,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11332,verified
4,Iodine,BEL,Belgium,national,NaN,both urban and rural,2018,4.0,2018,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11332,verified

Checking for missing values:

In [337]:
missing = pd.concat([df127.isnull().sum(), 100 * df127.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                          count           %
Indicator.                    0    0.000000
Reference 1                   0    0.000000
Reference no# 1               0    0.000000
Survey methodology            0    0.000000
Indicator comments            0    0.000000
Data adjusted for             0    0.000000
Method of analysis            0    0.000000
Sample collection method      0    0.000000
Fasting                       0    0.000000
Sample type                   0    0.000000
SurveyId                      0    0.000000
Age from                      0    0.000000
Age unit                      0    0.000000
Survey status                 0    0.000000
Population                    0    0.000000
Representativeness.           0    0.000000
Gender                        0    0.000000
Area covered                  0    0.000000
Date                          0    0.000000
Begin year                    0    0.000000
Country                       0    0.000000
End year                      0    0.000000
CountryCode                   0    0.000000
Indicator unit                5    4.716981
Link to reference 1          10    9.433962
End month                    11   10.377358
Begin month                  11   10.377358
Age to                       14   13.207547
Reference no# 2              19   17.924528
Reference 2                  19   17.924528
Reference no# 3              23   21.698113
Reference 3                  23   21.698113
Median                       28   26.415094
Link to reference 2          28   26.415094
Sample size                  30   28.301887
Link to reference 3          49   46.226415
L95CI                        60   56.603774
U95CI                        60   56.603774
General data comments        67   63.207547
Mean                         78   73.584906
Old Reference no# 1          83   78.301887
Old Reference no# 2          92   86.792453
Geo mean                     95   89.622642
Old Reference no# 3          96   90.566038
SE                           98   92.452830
SD                          103   97.169811
Representativeness name     106  100.000000

In [338]:
df127['Sample type'].head()

0    Urine sample - spot
1    Urine sample - spot
2    Urine sample - spot
3    Urine sample - spot
4    Urine sample - spot
Name: Sample type, dtype: object

In [339]:
df127.Country.unique()

array(['Belgium', 'Malawi', 'Australia', 'Austria', 'Canada',
       'United Kingdom of Great Britain and Northern', 'Ireland',
       'New Zealand', 'Philippines', 'United Republic of Tanzania',
       'Slovenia', 'Germany', 'Mauritius', 'France', 'Bangladesh', 'Chad'],
      dtype=object)

In [340]:
df127['Begin year'].unique()

array([2018, 2015, 2011, 2010, 2009, 2008, 2004, 2003, 2002, 1996, 1995,
       1994, 1993])

In [341]:
labels=["Indicator.", "Country", "Date", "Population", "Gender", "Indicator unit", "Mean", "Median", "U95CI", "L95CI"]
df127=df127[labels]

In [342]:
df127.shape
df127.head(15)

,Indicator.,Country,Date,Population,Gender,Indicator unit,Mean,Median,U95CI,L95CI
0,Iodine,Belgium,2018,Adults,All,µg/L,NaN,93.6,NaN,NaN
1,Iodine,Belgium,2018,Adults,All,µg/L,NaN,98.0,NaN,NaN
2,Iodine,Belgium,2018,Adults,All,µg/L,NaN,91.0,NaN,NaN
3,Iodine,Belgium,2018,Elderly,All,µg/L,NaN,93.4,NaN,NaN
4,Iodine,Belgium,2018,Men,Male,µg/L,NaN,94.2,NaN,NaN
5,Iodine,Belgium,2018,Women,Female,µg/L,NaN,91.7,NaN,NaN
6,Iodine,Malawi,2016,Adolescents,All,µg/L,NaN,267.5,NaN,NaN
7,Iodine,Australia,2012,Adolescents,All,µg/L,NaN,149.0,NaN,NaN
8,Iodine,Australia,2012,Adults,All,µg/L,NaN,124.0,NaN,NaN
9,Iodine,Australia,2012,Adults,All,µg/L,NaN,138.2,NaN,NaN
10,Iodine,Australia,2012,Adults,All,µg/L,NaN,124.0,NaN,NaN
11,Iodine,Australia,2012,Adults,All,µg/L,NaN,122.0,NaN,NaN
12,Iodine,Australia,2012,Adults,All,µg/L,NaN,119.0,NaN,NaN
13,Iodine,Australia,2012,Adults,All,µg/L,NaN,119.0,NaN,NaN
14,Iodine,Australia,2012,Adults,Female,µg/L,NaN,118.0,NaN,NaN

In [343]:
(df127["Country"] + ", " + df127["Population"]).value_counts()

Austria, Men                                                 8
Austria, Adolescents                                         8
Australia, Adults                                            7
Austria, Elderly                                             4
Austria, Women                                               4
France, Women                                                4
Ireland, Adults                                              4
New Zealand, Adolescents                                     4
New Zealand, Men                                             4
France, Men                                                  4
Ireland, Men                                                 4
Mauritius, Adults                                            3
Belgium, Adults                                              3
Ireland, Elderly                                             3
Canada, Elderly                                              3
Slovenia, Adolescents                                        3
United Republic of Tanzania, Adolescents                     3
Canada, Adolescents                                          3
Canada, Adults                                               2
Ireland, Women                                               2
Australia, Elderly                                           2
New Zealand, Elderly                                         2
New Zealand, Women                                           2
Canada, Men                                                  2
Germany, Men                                                 2
Malawi, Adolescents                                          1
Belgium, Women                                               1
Philippines, Adults                                          1
Philippines, Elderly                                         1
Chad, Adolescents                                            1
Australia, Men                                               1
Belgium, Elderly                                             1
Bangladesh, Adults                                           1
Canada, Women                                                1
United Kingdom of Great Britain and Northern, Adolescents    1
Belgium, Men                                                 1
Germany, Women                                               1
New Zealand, Adults                                          1
Australia, Adolescents                                       1
Bangladesh, Men                                              1
Philippines, Adolescents                                     1
dtype: int64

In [344]:
df127.Country.value_counts()

Austria                                         24
Ireland                                         13
New Zealand                                     13
Canada                                          11
Australia                                       11
France                                           8
Belgium                                          6
United Republic of Tanzania                      3
Philippines                                      3
Germany                                          3
Mauritius                                        3
Slovenia                                         3
Bangladesh                                       2
Malawi                                           1
Chad                                             1
United Kingdom of Great Britain and Northern     1
Name: Country, dtype: int64

In [345]:
df128.info()
df128.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 52 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Indicator.                   26 non-null     object
 1   CountryCode                  26 non-null     object
 2   Country                      26 non-null     object
 3   Representativeness.          26 non-null     object
 4   Representativeness name      0 non-null      float64
 5   Area covered                 26 non-null     object
 6   Date                         26 non-null     int64
 7   Begin month                  26 non-null     int64
 8   Begin year                   26 non-null     int64
 9   End month                    26 non-null     int64
 10  End year                     26 non-null     int64
 11  Population                   26 non-null     object
 12  Gender                       26 non-null     object
 13  Age unit                     26 non-null     object
 14  Age from                     26 non-null     int64
 15  Age to                       21 non-null     float64
 16  Sample size                  18 non-null     float64
 17  Indicator unit               24 non-null     object
 18  Mean                         24 non-null     float64
 19  Geo mean                     0 non-null      float64
 20  Median                       14 non-null     float64
 21  SD                           14 non-null     float64
 22  SE                           0 non-null      float64
 23  L95CI                        10 non-null     float64
 24  U95CI                        10 non-null     float64
 25  Low iron cut-off             18 non-null     object
 26  Prevalence of low iron       18 non-null     float64
 27  Marginal iron cut-off        4 non-null      object
 28  Prevalence of marginal iron  4 non-null      float64
 29  Elevated iron threshold      0 non-null      float64
 30  Prevalence of elevated iron  0 non-null      float64
 31  Sample type                  26 non-null     object
 32  Fasting                      26 non-null     object
 33  Method of analysis           26 non-null     object
 34  General data comments        7 non-null      object
 35  Indicator comments           26 non-null     object
 36  Survey methodology           26 non-null     object
 37  Season                       26 non-null     object
 38  Old Reference no# 1          14 non-null     float64
 39  Reference no# 1              26 non-null     int64
 40  Reference 1                  26 non-null     object
 41  Link to reference 1          26 non-null     object
 42  Old Reference no# 2          5 non-null      float64
 43  Reference no# 2              17 non-null     float64
 44  Reference 2                  17 non-null     object
 45  Link to reference 2          17 non-null     object
 46  Old Reference no# 3          0 non-null      float64
 47  Reference no# 3              17 non-null     float64
 48  Reference 3                  17 non-null     object
 49  Link to reference 3          5 non-null      object
 50  SurveyId                     26 non-null     int64
 51  Survey status                26 non-null     object
dtypes: float64(19), int64(8), object(25)
memory usage: 10.7+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Iron (serum or plasma),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
1,Iron (serum or plasma),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
2,Iron (serum or plasma),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
3,Iron (serum or plasma),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
4,Iron (serum or plasma),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified

Checking for missing values:

In [346]:
missing = pd.concat([df128.isnull().sum(), 100 * df128.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                             count           %
Indicator.                       0    0.000000
Link to reference 1              0    0.000000
Reference 1                      0    0.000000
Reference no# 1                  0    0.000000
Season                           0    0.000000
Survey methodology               0    0.000000
Indicator comments               0    0.000000
Method of analysis               0    0.000000
Fasting                          0    0.000000
Sample type                      0    0.000000
SurveyId                         0    0.000000
Age from                         0    0.000000
Age unit                         0    0.000000
Survey status                    0    0.000000
Population                       0    0.000000
CountryCode                      0    0.000000
Country                          0    0.000000
Representativeness.              0    0.000000
Area covered                     0    0.000000
Date                             0    0.000000
Begin month                      0    0.000000
Gender                           0    0.000000
End month                        0    0.000000
End year                         0    0.000000
Begin year                       0    0.000000
Indicator unit                   2    7.692308
Mean                             2    7.692308
Age to                           5   19.230769
Low iron cut-off                 8   30.769231
Prevalence of low iron           8   30.769231
Sample size                      8   30.769231
Reference 3                      9   34.615385
Reference no# 3                  9   34.615385
Link to reference 2              9   34.615385
Reference 2                      9   34.615385
Reference no# 2                  9   34.615385
Old Reference no# 1             12   46.153846
Median                          12   46.153846
SD                              12   46.153846
U95CI                           16   61.538462
L95CI                           16   61.538462
General data comments           19   73.076923
Old Reference no# 2             21   80.769231
Link to reference 3             21   80.769231
Prevalence of marginal iron     22   84.615385
Marginal iron cut-off           22   84.615385
Representativeness name         26  100.000000
SE                              26  100.000000
Prevalence of elevated iron     26  100.000000
Elevated iron threshold         26  100.000000
Old Reference no# 3             26  100.000000
Geo mean                        26  100.000000

In [347]:
df128.Country.unique()

array(['Austria', 'United Kingdom of Great Britain and Northern'],
      dtype=object)

In [348]:
df128['Begin year'].unique()

array([2010, 1994, 2000])

Another indicator with too little data to use for this project.

In [349]:
df129.info()
df129.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 42 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Indicator.                78 non-null     object
 1   CountryCode               78 non-null     object
 2   Country                   78 non-null     object
 3   Representativeness.       78 non-null     object
 4   Representativeness name   0 non-null      float64
 5   Area covered              78 non-null     object
 6   Date                      78 non-null     int64
 7   Begin month               70 non-null     float64
 8   Begin year                77 non-null     float64
 9   End month                 70 non-null     float64
 10  End year                  78 non-null     int64
 11  Population                78 non-null     object
 12  Gender                    78 non-null     object
 13  Age unit                  78 non-null     object
 14  Age from                  77 non-null     float64
 15  Age to                    69 non-null     float64
 16  Sample size               68 non-null     float64
 17  IDA cut-off               77 non-null     object
 18  IDA Prevalence            78 non-null     float64
 19  Sample collection method  78 non-null     object
 20  Sample type               78 non-null     object
 21  Fasting                   78 non-null     object
 22  Method of analysis        78 non-null     object
 23  Data adjusted for         78 non-null     object
 24  General data comments     39 non-null     object
 25  Indicator comments        78 non-null     object
 26  Survey methodology        78 non-null     object
 27  Season                    78 non-null     object
 28  Old Reference no# 1       18 non-null     float64
 29  Reference no# 1           78 non-null     int64
 30  Reference 1               78 non-null     object
 31  Link to reference 1       67 non-null     object
 32  Old Reference no# 2       17 non-null     float64
 33  Reference no# 2           42 non-null     float64
 34  Reference 2               42 non-null     object
 35  Link to reference 2       39 non-null     object
 36  Old Reference no# 3       2 non-null      float64
 37  Reference no# 3           23 non-null     float64
 38  Reference 3               23 non-null     object
 39  Link to reference 3       23 non-null     object
 40  SurveyId                  78 non-null     int64
 41  Survey status             78 non-null     object
dtypes: float64(13), int64(4), object(25)
memory usage: 25.7+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Iron deficiency anaemia,BGD,Bangladesh,national,NaN,both urban and rural,2011,10.0,2011.0,12.0,...,NaN,1166.0,"Rahman S, Rahman AS, Alam N, Ahmed AMS, Ireen ...",http://dx.doi.org/10.1017/S1368980016003049,NaN,NaN,NaN,NaN,10764,verified
1,Iron deficiency anaemia,BGD,Bangladesh,national,NaN,rural,2011,10.0,2011.0,12.0,...,NaN,1166.0,"Rahman S, Rahman AS, Alam N, Ahmed AMS, Ireen ...",http://dx.doi.org/10.1017/S1368980016003049,NaN,NaN,NaN,NaN,10764,verified
2,Iron deficiency anaemia,BGD,Bangladesh,national,NaN,urban,2011,10.0,2011.0,12.0,...,NaN,1166.0,"Rahman S, Rahman AS, Alam N, Ahmed AMS, Ireen ...",http://dx.doi.org/10.1017/S1368980016003049,NaN,NaN,NaN,NaN,10764,verified
3,Iron deficiency anaemia,BGD,Bangladesh,national,NaN,urban (other),2011,10.0,2011.0,12.0,...,NaN,1166.0,"Rahman S, Rahman AS, Alam N, Ahmed AMS, Ireen ...",http://dx.doi.org/10.1017/S1368980016003049,NaN,NaN,NaN,NaN,10764,verified
4,Iron deficiency anaemia,CAN,Canada,national,NaN,both urban and rural,2011,8.0,2009.0,11.0,...,NaN,763.0,Canadian Health Measures Survey (CHMS) data us...,http://data.library.utoronto.ca/datapub/codebo...,NaN,1057.0,"Janz T, Pearson C. Vitamin D blood levels of C...",http://www.statcan.gc.ca/pub/82-624-x/2013001/...,10819,verified

Checking for missing values:

In [350]:
missing = pd.concat([df129.isnull().sum(), 100 * df129.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                          count           %
Indicator.                    0    0.000000
Reference 1                   0    0.000000
Reference no# 1               0    0.000000
Season                        0    0.000000
Survey methodology            0    0.000000
Indicator comments            0    0.000000
Data adjusted for             0    0.000000
Method of analysis            0    0.000000
Fasting                       0    0.000000
SurveyId                      0    0.000000
Sample collection method      0    0.000000
IDA Prevalence                0    0.000000
Age unit                      0    0.000000
Sample type                   0    0.000000
Representativeness.           0    0.000000
CountryCode                   0    0.000000
Country                       0    0.000000
Gender                        0    0.000000
Area covered                  0    0.000000
Date                          0    0.000000
Survey status                 0    0.000000
End year                      0    0.000000
Population                    0    0.000000
Begin year                    1    1.282051
IDA cut-off                   1    1.282051
Age from                      1    1.282051
Begin month                   8   10.256410
End month                     8   10.256410
Age to                        9   11.538462
Sample size                  10   12.820513
Link to reference 1          11   14.102564
Reference no# 2              36   46.153846
Reference 2                  36   46.153846
Link to reference 2          39   50.000000
General data comments        39   50.000000
Reference no# 3              55   70.512821
Reference 3                  55   70.512821
Link to reference 3          55   70.512821
Old Reference no# 1          60   76.923077
Old Reference no# 2          61   78.205128
Old Reference no# 3          76   97.435897
Representativeness name      78  100.000000

In [351]:
df129.Country.unique()

array(['Bangladesh', 'Canada', 'Ecuador', 'France', 'Kenya', 'Kuwait',
       'Mexico', 'Mauritius', 'Malawi', 'Nepal', 'New Zealand'],
      dtype=object)

In [352]:
df129['Begin year'].unique()

array([2011., 2009., 2012., 1994., 2006.,   nan, 1995., 2001., 2015.,
       2016., 2002., 2008.])

In [353]:
labels=["Indicator.", "Country", "Date", "Population", "Gender", "IDA Prevalence", "IDA cut-off"]
df129=df129[labels]

In [354]:
df129.shape
df129.head(15)

,Indicator.,Country,Date,Population,Gender,IDA Prevalence,IDA cut-off
0,Iron deficiency anaemia,Bangladesh,2011,Adolescents,All,1.8,Hgb <120 g/L and ferritin <15 µg/L
1,Iron deficiency anaemia,Bangladesh,2011,Adolescents,All,1.8,Hgb <120 g/L and ferritin <15 µg/L
2,Iron deficiency anaemia,Bangladesh,2011,Adolescents,All,1.7,Hgb <120 g/L and ferritin <15 µg/L
3,Iron deficiency anaemia,Bangladesh,2011,Adolescents,All,1.8,Hgb <120 g/L and ferritin <15 µg/L
4,Iron deficiency anaemia,Canada,2011,Adolescents,Female,15.0,Hgb <120 g/L and ferritin <15 µg/L
5,Iron deficiency anaemia,Ecuador,2012,Adolescents,Female,1.9,Hgb <120 g/L and ferritin <15 µg/L
6,Iron deficiency anaemia,Ecuador,2012,Adolescents,Female,5.3,Hgb <120 g/L and ferritin <15 µg/L
7,Iron deficiency anaemia,Ecuador,2012,Adolescents,Female,7.4,Hgb <120 g/L and ferritin <15 µg/L
8,Iron deficiency anaemia,Ecuador,2012,Adults,Female,1.5,Hgb <120 g/L and ferritin <15 µg/L
9,Iron deficiency anaemia,France,1995,Men,Male,0.4,Hgb <130 g/L and ferritin <15 µg/L
10,Iron deficiency anaemia,France,1995,Women,Female,0.7,Specify Hgb (g/L) and ferritin (µg/L)
11,Iron deficiency anaemia,France,2007,Adults,All,1.2,Hgb <120 g/L and ferritin <15 µg/L
12,Iron deficiency anaemia,France,2007,Adults,Female,1.9,Hgb <120 g/L and ferritin <15 µg/L
13,Iron deficiency anaemia,France,2007,Adults,Male,0.5,Hgb <130 g/L and ferritin <15 µg/L
14,Iron deficiency anaemia,Kenya,2011,Men,Male,2.9,Hgb <130 g/L and ferritin <15 µg/L

In [355]:
(df129["Country"] + ", " + df129["Population"]).value_counts()

Malawi, Men                 21
Nepal, Adolescents          16
Mexico, Elderly              6
New Zealand, Men             4
New Zealand, Adolescents     4
Bangladesh, Adolescents      4
Kenya, Men                   3
France, Adults               3
Ecuador, Adolescents         3
Malawi, Adolescents          3
New Zealand, Adults          2
New Zealand, Elderly         2
Mauritius, Men               1
Kuwait, Adolescents          1
New Zealand, Women           1
France, Men                  1
France, Women                1
Canada, Adolescents          1
Ecuador, Adults              1
dtype: int64

In [356]:
df129.Country.value_counts()

Malawi         24
Nepal          16
New Zealand    13
Mexico          6
France          5
Bangladesh      4
Ecuador         4
Kenya           3
Canada          1
Mauritius       1
Kuwait          1
Name: Country, dtype: int64

In [357]:
df130.info()
df130.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 50 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Indicator.                   13 non-null     object
 1   CountryCode                  13 non-null     object
 2   Country                      13 non-null     object
 3   Representativeness.          13 non-null     object
 4   Representativeness name      0 non-null      float64
 5   Area covered                 13 non-null     object
 6   Date                         13 non-null     int64
 7   Begin month                  13 non-null     int64
 8   Begin year                   13 non-null     int64
 9   End month                    13 non-null     int64
 10  End year                     13 non-null     int64
 11  Population                   13 non-null     object
 12  Gender                       13 non-null     object
 13  Age unit                     13 non-null     object
 14  Age from                     13 non-null     int64
 15  Age to                       13 non-null     int64
 16  Sample size                  0 non-null      float64
 17  Indicator unit               10 non-null     object
 18  Mean                         10 non-null     float64
 19  Geo mean                     0 non-null      float64
 20  Median                       0 non-null      float64
 21  SD                           0 non-null      float64
 22  SE                           0 non-null      float64
 23  L95CI                        10 non-null     float64
 24  U95CI                        10 non-null     float64
 25  Deficiency cut-off           2 non-null      object
 26  Prevalence of deficiency     2 non-null      float64
 27  Low cut-off                  0 non-null      float64
 28  Prevalence of low magnesium  0 non-null      float64
 29  Sample type                  13 non-null     object
 30  Fasting                      13 non-null     object
 31  Method of analysis           13 non-null     object
 32  General data comments        2 non-null      object
 33  Indicator comments           13 non-null     object
 34  Survey methodology           13 non-null     object
 35  Season                       13 non-null     object
 36  Old Reference no# 1          0 non-null      float64
 37  Reference no# 1              13 non-null     int64
 38  Reference 1                  13 non-null     object
 39  Link to reference 1          13 non-null     object
 40  Old Reference no# 2          0 non-null      float64
 41  Reference no# 2              13 non-null     int64
 42  Reference 2                  13 non-null     object
 43  Link to reference 2          13 non-null     object
 44  Old Reference no# 3          0 non-null      float64
 45  Reference no# 3              13 non-null     int64
 46  Reference 3                  13 non-null     object
 47  Link to reference 3          0 non-null      float64
 48  SurveyId                     13 non-null     int64
 49  Survey status                13 non-null     object
dtypes: float64(16), int64(11), object(23)
memory usage: 5.2+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Magnesium,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
1,Magnesium,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
2,Magnesium,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
3,Magnesium,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
4,Magnesium,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified

Checking for missing values:

In [358]:
missing = pd.concat([df130.isnull().sum(), 100 * df130.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                             count           %
Indicator.                       0    0.000000
Reference 3                      0    0.000000
Reference no# 3                  0    0.000000
Link to reference 2              0    0.000000
Reference 2                      0    0.000000
Reference no# 2                  0    0.000000
Link to reference 1              0    0.000000
Reference 1                      0    0.000000
Reference no# 1                  0    0.000000
Season                           0    0.000000
Survey methodology               0    0.000000
Indicator comments               0    0.000000
Method of analysis               0    0.000000
Fasting                          0    0.000000
Sample type                      0    0.000000
SurveyId                         0    0.000000
Survey status                    0    0.000000
Population                       0    0.000000
CountryCode                      0    0.000000
Country                          0    0.000000
Representativeness.              0    0.000000
Area covered                     0    0.000000
Date                             0    0.000000
Begin month                      0    0.000000
Age to                           0    0.000000
Begin year                       0    0.000000
End month                        0    0.000000
End year                         0    0.000000
Gender                           0    0.000000
Age from                         0    0.000000
Age unit                         0    0.000000
Indicator unit                   3   23.076923
U95CI                            3   23.076923
Mean                             3   23.076923
L95CI                            3   23.076923
Deficiency cut-off              11   84.615385
General data comments           11   84.615385
Prevalence of deficiency        11   84.615385
Low cut-off                     13  100.000000
SE                              13  100.000000
Prevalence of low magnesium     13  100.000000
SD                              13  100.000000
Representativeness name         13  100.000000
Median                          13  100.000000
Old Reference no# 3             13  100.000000
Geo mean                        13  100.000000
Sample size                     13  100.000000
Link to reference 3             13  100.000000
Old Reference no# 1             13  100.000000
Old Reference no# 2             13  100.000000

In [359]:
df130.Country.unique()

array(['Austria'], dtype=object)

In [360]:
df130['Begin year'].unique()

array([2010])

Another indicator with too little data to use for this project.

In [361]:
df131.info()
df131.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 50 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Indicator.                        42 non-null     object
 1   CountryCode                       42 non-null     object
 2   Country                           42 non-null     object
 3   Representativeness.               42 non-null     object
 4   Representativeness name           0 non-null      float64
 5   Area covered                      42 non-null     object
 6   Date                              42 non-null     int64
 7   Begin month                       42 non-null     int64
 8   Begin year                        42 non-null     int64
 9   End month                         42 non-null     int64
 10  End year                          42 non-null     int64
 11  Population                        42 non-null     object
 12  Gender                            42 non-null     object
 13  Age unit                          42 non-null     object
 14  Age from                          42 non-null     int64
 15  Age to                            37 non-null     float64
 16  Sample size                       35 non-null     float64
 17  Indicator unit                    38 non-null     object
 18  Mean                              38 non-null     float64
 19  Geo mean                          0 non-null      float64
 20  Median                            25 non-null     float64
 21  SD                                25 non-null     float64
 22  SE                                0 non-null      float64
 23  L95CI                             24 non-null     float64
 24  U95CI                             24 non-null     float64
 25  Microcytic anaemia cut-off        27 non-null     object
 26  Prevalence of microcytic anaemia  27 non-null     float64
 27  Macrocytic anaemia cut-off        14 non-null     object
 28  Prevalence of macrocytic anaemia  14 non-null     float64
 29  Sample type                       42 non-null     object
 30  Fasting                           42 non-null     object
 31  Method of analysis                42 non-null     object
 32  General data comments             12 non-null     object
 33  Indicator comments                42 non-null     object
 34  Survey methodology                42 non-null     object
 35  Season                            42 non-null     object
 36  Old Reference no# 1               14 non-null     float64
 37  Reference no# 1                   42 non-null     int64
 38  Reference 1                       42 non-null     object
 39  Link to reference 1               42 non-null     object
 40  Old Reference no# 2               5 non-null      float64
 41  Reference no# 2                   18 non-null     float64
 42  Reference 2                       18 non-null     object
 43  Link to reference 2               18 non-null     object
 44  Old Reference no# 3               0 non-null      float64
 45  Reference no# 3                   18 non-null     float64
 46  Reference 3                       18 non-null     object
 47  Link to reference 3               12 non-null     object
 48  SurveyId                          42 non-null     int64
 49  Survey status                     42 non-null     object
dtypes: float64(17), int64(8), object(25)
memory usage: 16.5+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Mean corpuscular volume (MCV),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
1,Mean corpuscular volume (MCV),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
2,Mean corpuscular volume (MCV),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
3,Mean corpuscular volume (MCV),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
4,Mean corpuscular volume (MCV),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified

Checking for missing values:

In [362]:
missing = pd.concat([df131.isnull().sum(), 100 * df131.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                                  count           %
Indicator.                            0    0.000000
Link to reference 1                   0    0.000000
Reference 1                           0    0.000000
Reference no# 1                       0    0.000000
Season                                0    0.000000
Survey methodology                    0    0.000000
Indicator comments                    0    0.000000
Method of analysis                    0    0.000000
Fasting                               0    0.000000
Sample type                           0    0.000000
SurveyId                              0    0.000000
Age from                              0    0.000000
Age unit                              0    0.000000
Survey status                         0    0.000000
Population                            0    0.000000
CountryCode                           0    0.000000
Country                               0    0.000000
Representativeness.                   0    0.000000
Area covered                          0    0.000000
Date                                  0    0.000000
Gender                                0    0.000000
Begin year                            0    0.000000
End month                             0    0.000000
End year                              0    0.000000
Begin month                           0    0.000000
Indicator unit                        4    9.523810
Mean                                  4    9.523810
Age to                                5   11.904762
Sample size                           7   16.666667
Microcytic anaemia cut-off           15   35.714286
Prevalence of microcytic anaemia     15   35.714286
SD                                   17   40.476190
Median                               17   40.476190
U95CI                                18   42.857143
L95CI                                18   42.857143
Reference 3                          24   57.142857
Reference no# 3                      24   57.142857
Reference no# 2                      24   57.142857
Reference 2                          24   57.142857
Link to reference 2                  24   57.142857
Prevalence of macrocytic anaemia     28   66.666667
Old Reference no# 1                  28   66.666667
Macrocytic anaemia cut-off           28   66.666667
Link to reference 3                  30   71.428571
General data comments                30   71.428571
Old Reference no# 2                  37   88.095238
SE                                   42  100.000000
Representativeness name              42  100.000000
Geo mean                             42  100.000000
Old Reference no# 3                  42  100.000000

In [363]:
df131.Country.unique()

array(['Austria', 'Canada', 'Ecuador',
       'United Kingdom of Great Britain and Northern'], dtype=object)

In [364]:
df131['Begin year'].unique()

array([2010, 2009, 2012, 1994, 2000])

Another indicator with too little data to use for this project.

In [365]:
df132.info()
df132.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 49 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Indicator.               23 non-null     object
 1   CountryCode              23 non-null     object
 2   Country                  23 non-null     object
 3   Representativeness.      23 non-null     object
 4   Representativeness name  0 non-null      float64
 5   Area covered             23 non-null     object
 6   Date                     23 non-null     int64
 7   Begin month              23 non-null     int64
 8   Begin year               23 non-null     int64
 9   End month                23 non-null     int64
 10  End year                 23 non-null     int64
 11  Population               23 non-null     object
 12  Gender                   23 non-null     object
 13  Age unit                 23 non-null     object
 14  Age from                 23 non-null     int64
 15  Age to                   23 non-null     int64
 16  Sample size              23 non-null     int64
 17  Indicator unit           20 non-null     object
 18  Mean                     4 non-null      float64
 19  Geo mean                 16 non-null     float64
 20  Median                   0 non-null      float64
 21  SD                       16 non-null     float64
 22  SE                       0 non-null      float64
 23  L95CI                    4 non-null      float64
 24  U95CI                    4 non-null      float64
 25  Inadequacy cut-off       19 non-null     object
 26  Inadequacy prevalence    19 non-null     float64
 27  Sample type              23 non-null     object
 28  Fasting                  23 non-null     object
 29  Method of analysis       23 non-null     object
 30  Data adjusted for        23 non-null     object
 31  General data comments    19 non-null     object
 32  Indicator comments       23 non-null     object
 33  Survey methodology       23 non-null     object
 34  Season                   23 non-null     object
 35  Old Reference no# 1      0 non-null      float64
 36  Reference no# 1          23 non-null     int64
 37  Reference 1              23 non-null     object
 38  Link to reference 1      21 non-null     object
 39  Old Reference no# 2      0 non-null      float64
 40  Reference no# 2          4 non-null      float64
 41  Reference 2              4 non-null      object
 42  Link to reference 2      4 non-null      object
 43  Old Reference no# 3      0 non-null      float64
 44  Reference no# 3          4 non-null      float64
 45  Reference 3              4 non-null      object
 46  Link to reference 3      0 non-null      float64
 47  SurveyId                 23 non-null     int64
 48  Survey status            23 non-null     object
dtypes: float64(15), int64(10), object(24)
memory usage: 8.9+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Retinol binding protein,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
1,Retinol binding protein,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
2,Retinol binding protein,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
3,Retinol binding protein,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
4,Retinol binding protein,KEN,Kenya,national,NaN,both urban and rural,2011,9,2011,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10957,verified

Checking for missing values:

In [366]:
missing = pd.concat([df132.isnull().sum(), 100 * df132.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                         count           %
Indicator.                   0    0.000000
Reference 1                  0    0.000000
Reference no# 1              0    0.000000
Season                       0    0.000000
Survey methodology           0    0.000000
Indicator comments           0    0.000000
Data adjusted for            0    0.000000
Method of analysis           0    0.000000
Fasting                      0    0.000000
Sample type                  0    0.000000
SurveyId                     0    0.000000
Sample size                  0    0.000000
Age to                       0    0.000000
Age from                     0    0.000000
Survey status                0    0.000000
Gender                       0    0.000000
Population                   0    0.000000
CountryCode                  0    0.000000
Country                      0    0.000000
Representativeness.          0    0.000000
Area covered                 0    0.000000
Age unit                     0    0.000000
End year                     0    0.000000
Date                         0    0.000000
Begin month                  0    0.000000
End month                    0    0.000000
Begin year                   0    0.000000
Link to reference 1          2    8.695652
Indicator unit               3   13.043478
General data comments        4   17.391304
Inadequacy cut-off           4   17.391304
Inadequacy prevalence        4   17.391304
SD                           7   30.434783
Geo mean                     7   30.434783
Reference 3                 19   82.608696
Reference no# 3             19   82.608696
Link to reference 2         19   82.608696
Reference 2                 19   82.608696
Reference no# 2             19   82.608696
U95CI                       19   82.608696
L95CI                       19   82.608696
Mean                        19   82.608696
Median                      23  100.000000
Old Reference no# 1         23  100.000000
Representativeness name     23  100.000000
Old Reference no# 3         23  100.000000
SE                          23  100.000000
Link to reference 3         23  100.000000
Old Reference no# 2         23  100.000000

In [367]:
df132.Country.unique()

array(['Austria', 'Kenya', 'Malawi', 'Nepal'], dtype=object)

In [368]:
df132['Begin year'].unique()

array([2010, 2011, 2009, 2015, 2016])

Another indicator with too little data to use for this project.

In [369]:
df133.info()
df133.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 50 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Indicator.                     21 non-null     object
 1   CountryCode                    21 non-null     object
 2   Country                        21 non-null     object
 3   Representativeness.            21 non-null     object
 4   Representativeness name        0 non-null      float64
 5   Area covered                   21 non-null     object
 6   Date                           21 non-null     int64
 7   Begin month                    21 non-null     int64
 8   Begin year                     21 non-null     int64
 9   End month                      21 non-null     int64
 10  End year                       21 non-null     int64
 11  Population                     21 non-null     object
 12  Gender                         21 non-null     object
 13  Age unit                       21 non-null     object
 14  Age from                       21 non-null     int64
 15  Age to                         21 non-null     int64
 16  Sample size                    13 non-null     float64
 17  Indicator unit                 19 non-null     object
 18  Mean                           19 non-null     float64
 19  Geo mean                       0 non-null      float64
 20  Median                         5 non-null      float64
 21  SD                             5 non-null      float64
 22  SE                             0 non-null      float64
 23  L95CI                          14 non-null     float64
 24  U95CI                          14 non-null     float64
 25  Deficiency cut-off             11 non-null     object
 26  Prevalence of deficiency       11 non-null     float64
 27  Marginal cut-off               0 non-null      float64
 28  Prevalence of marginal values  0 non-null      float64
 29  Sample type                    21 non-null     object
 30  Fasting                        21 non-null     object
 31  Method of analysis             21 non-null     object
 32  General data comments          8 non-null      object
 33  Indicator comments             21 non-null     object
 34  Survey methodology             21 non-null     object
 35  Season                         21 non-null     object
 36  Old Reference no# 1            5 non-null      float64
 37  Reference no# 1                21 non-null     int64
 38  Reference 1                    21 non-null     object
 39  Link to reference 1            17 non-null     object
 40  Old Reference no# 2            5 non-null      float64
 41  Reference no# 2                17 non-null     float64
 42  Reference 2                    17 non-null     object
 43  Link to reference 2            17 non-null     object
 44  Old Reference no# 3            0 non-null      float64
 45  Reference no# 3                17 non-null     float64
 46  Reference 3                    17 non-null     object
 47  Link to reference 3            5 non-null      object
 48  SurveyId                       21 non-null     int64
 49  Survey status                  21 non-null     object
dtypes: float64(17), int64(9), object(24)
memory usage: 8.3+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Selenium (plama or serum),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
1,Selenium (plama or serum),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
2,Selenium (plama or serum),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
3,Selenium (plama or serum),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
4,Selenium (plama or serum),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified

Checking for missing values:

In [370]:
missing = pd.concat([df133.isnull().sum(), 100 * df133.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                               count           %
Indicator.                         0    0.000000
Reference 1                        0    0.000000
Reference no# 1                    0    0.000000
Season                             0    0.000000
Survey methodology                 0    0.000000
Indicator comments                 0    0.000000
Method of analysis                 0    0.000000
Fasting                            0    0.000000
Sample type                        0    0.000000
SurveyId                           0    0.000000
Age to                             0    0.000000
Age from                           0    0.000000
Age unit                           0    0.000000
Survey status                      0    0.000000
Population                         0    0.000000
CountryCode                        0    0.000000
Country                            0    0.000000
Representativeness.                0    0.000000
Area covered                       0    0.000000
Gender                             0    0.000000
Begin month                        0    0.000000
Begin year                         0    0.000000
End month                          0    0.000000
Date                               0    0.000000
End year                           0    0.000000
Mean                               2    9.523810
Indicator unit                     2    9.523810
Reference 3                        4   19.047619
Reference no# 3                    4   19.047619
Link to reference 2                4   19.047619
Reference 2                        4   19.047619
Reference no# 2                    4   19.047619
Link to reference 1                4   19.047619
U95CI                              7   33.333333
L95CI                              7   33.333333
Sample size                        8   38.095238
Deficiency cut-off                10   47.619048
Prevalence of deficiency          10   47.619048
General data comments             13   61.904762
Link to reference 3               16   76.190476
Old Reference no# 1               16   76.190476
Median                            16   76.190476
SD                                16   76.190476
Old Reference no# 2               16   76.190476
Representativeness name           21  100.000000
Geo mean                          21  100.000000
Old Reference no# 3               21  100.000000
Prevalence of marginal values     21  100.000000
Marginal cut-off                  21  100.000000
SE                                21  100.000000

In [371]:
df133.Country.unique()

array(['Austria', 'Costa Rica',
       'United Kingdom of Great Britain and Northern'], dtype=object)

In [372]:
df133['Begin year'].unique()

array([2010, 2008, 2000])

Another indicator with too little data to use for this project.

In [373]:
df134.info()
df134.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 49 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Indicator.                          17 non-null     object
 1   CountryCode                         17 non-null     object
 2   Country                             17 non-null     object
 3   Representativeness.                 17 non-null     object
 4   Representativeness name             0 non-null      float64
 5   Area covered                        17 non-null     object
 6   Date                                17 non-null     int64
 7   Begin month                         17 non-null     int64
 8   Begin year                          17 non-null     int64
 9   End month                           17 non-null     int64
 10  End year                            17 non-null     int64
 11  Population                          17 non-null     object
 12  Gender                              17 non-null     object
 13  Age unit                            17 non-null     object
 14  Age from                            17 non-null     int64
 15  Age to                              17 non-null     int64
 16  Sample size                         5 non-null      float64
 17  Indicator unit                      15 non-null     object
 18  Mean                                10 non-null     float64
 19  Geo mean                            0 non-null      float64
 20  Median                              5 non-null      float64
 21  SD                                  0 non-null      float64
 22  SE                                  0 non-null      float64
 23  L95CI                               10 non-null     float64
 24  U95CI                               10 non-null     float64
 25  Iodine insufficiency cut-off        0 non-null      float64
 26  Prevalence of iodine insufficiency  0 non-null      float64
 27  Sample collection method            17 non-null     object
 28  Sample type                         17 non-null     object
 29  Fasting                             17 non-null     object
 30  Method of analysis                  17 non-null     object
 31  General data comments               2 non-null      object
 32  Indicator comments                  17 non-null     object
 33  Survey methodology                  17 non-null     object
 34  Season                              17 non-null     object
 35  Old Reference no# 1                 5 non-null      float64
 36  Reference no# 1                     17 non-null     int64
 37  Reference 1                         17 non-null     object
 38  Link to reference 1                 17 non-null     object
 39  Old Reference no# 2                 5 non-null      float64
 40  Reference no# 2                     17 non-null     int64
 41  Reference 2                         17 non-null     object
 42  Link to reference 2                 12 non-null     object
 43  Old Reference no# 3                 5 non-null      float64
 44  Reference no# 3                     17 non-null     int64
 45  Reference 3                         17 non-null     object
 46  Link to reference 3                 5 non-null      object
 47  SurveyId                            17 non-null     int64
 48  Survey status                       17 non-null     object
dtypes: float64(14), int64(11), object(24)
memory usage: 6.6+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Thyroid stimulating hormone (TSH),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
1,Thyroid stimulating hormone (TSH),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
2,Thyroid stimulating hormone (TSH),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
3,Thyroid stimulating hormone (TSH),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
4,Thyroid stimulating hormone (TSH),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified

Checking for missing values:

In [374]:
missing = pd.concat([df134.isnull().sum(), 100 * df134.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                                    count           %
Indicator.                              0    0.000000
Reference 3                             0    0.000000
Reference no# 3                         0    0.000000
Reference 2                             0    0.000000
Reference no# 2                         0    0.000000
Link to reference 1                     0    0.000000
Reference 1                             0    0.000000
Reference no# 1                         0    0.000000
Season                                  0    0.000000
Survey methodology                      0    0.000000
Indicator comments                      0    0.000000
Method of analysis                      0    0.000000
Fasting                                 0    0.000000
Sample type                             0    0.000000
Sample collection method                0    0.000000
SurveyId                                0    0.000000
Survey status                           0    0.000000
End year                                0    0.000000
CountryCode                             0    0.000000
Country                                 0    0.000000
Representativeness.                     0    0.000000
Area covered                            0    0.000000
Date                                    0    0.000000
Begin month                             0    0.000000
Age to                                  0    0.000000
Begin year                              0    0.000000
End month                               0    0.000000
Age from                                0    0.000000
Age unit                                0    0.000000
Gender                                  0    0.000000
Population                              0    0.000000
Indicator unit                          2   11.764706
Link to reference 2                     5   29.411765
U95CI                                   7   41.176471
Mean                                    7   41.176471
L95CI                                   7   41.176471
Link to reference 3                    12   70.588235
Old Reference no# 3                    12   70.588235
Median                                 12   70.588235
Sample size                            12   70.588235
Old Reference no# 1                    12   70.588235
Old Reference no# 2                    12   70.588235
General data comments                  15   88.235294
SD                                     17  100.000000
SE                                     17  100.000000
Geo mean                               17  100.000000
Iodine insufficiency cut-off           17  100.000000
Prevalence of iodine insufficiency     17  100.000000
Representativeness name                17  100.000000

In [375]:
df134.Country.unique()

array(['Austria', 'France'], dtype=object)

In [376]:
df134['Begin year'].unique()

array([2010, 1994])

Another indicator with too little data to use for this project.

In [377]:
df135.info()
df135.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 51 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Indicator.                   107 non-null    object
 1   CountryCode                  107 non-null    object
 2   Country                      107 non-null    object
 3   Representativeness.          107 non-null    object
 4   Representativeness name      0 non-null      float64
 5   Area covered                 107 non-null    object
 6   Date                         107 non-null    int64
 7   Begin month                  107 non-null    int64
 8   Begin year                   107 non-null    int64
 9   End month                    107 non-null    int64
 10  End year                     107 non-null    int64
 11  Population                   107 non-null    object
 12  Gender                       107 non-null    object
 13  Age unit                     107 non-null    object
 14  Age from                     107 non-null    int64
 15  Age to                       88 non-null     float64
 16  Sample size                  86 non-null     float64
 17  Indicator unit               96 non-null     object
 18  Mean                         81 non-null     float64
 19  Geo mean                     15 non-null     float64
 20  Median                       66 non-null     float64
 21  SD                           37 non-null     float64
 22  SE                           2 non-null      float64
 23  L95CI                        48 non-null     float64
 24  U95CI                        48 non-null     float64
 25  Deficiency cut-off           77 non-null     object
 26  Prevalence of deficiency     77 non-null     float64
 27  Insufficiency cut-off        18 non-null     object
 28  Prevalence of insufficiency  18 non-null     float64
 29  Sample collection method     107 non-null    object
 30  Sample type                  107 non-null    object
 31  Fasting                      107 non-null    object
 32  Method of analysis           107 non-null    object
 33  General data comments        43 non-null     object
 34  Indicator comments           107 non-null    object
 35  Survey methodology           107 non-null    object
 36  Season                       107 non-null    object
 37  Old Reference no# 1          14 non-null     float64
 38  Reference no# 1              107 non-null    int64
 39  Reference 1                  107 non-null    object
 40  Link to reference 1          93 non-null     object
 41  Old Reference no# 2          5 non-null      float64
 42  Reference no# 2              66 non-null     float64
 43  Reference 2                  66 non-null     object
 44  Link to reference 2          66 non-null     object
 45  Old Reference no# 3          0 non-null      float64
 46  Reference no# 3              59 non-null     float64
 47  Reference 3                  59 non-null     object
 48  Link to reference 3          47 non-null     object
 49  SurveyId                     107 non-null    int64
 50  Survey status                107 non-null    object
dtypes: float64(17), int64(8), object(26)
memory usage: 42.8+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Vitamin B12,AUS,Australia,national,NaN,both urban and rural,2012,3,2011,9,...,NaN,107.0,"Australian Health Survey: user's guide, 2011-1...",http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,NaN,176.0,Australian Health Survey: biomedical results f...,http://www.ausstats.abs.gov.au/ausstats/subscr...,10160,verified
1,Vitamin B12,AUS,Australia,national,NaN,both urban and rural,2012,3,2011,9,...,NaN,107.0,"Australian Health Survey: user's guide, 2011-1...",http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,NaN,176.0,Australian Health Survey: biomedical results f...,http://www.ausstats.abs.gov.au/ausstats/subscr...,10160,verified
2,Vitamin B12,AUS,Australia,national,NaN,both urban and rural,2012,3,2011,9,...,NaN,107.0,"Australian Health Survey: user's guide, 2011-1...",http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,NaN,176.0,Australian Health Survey: biomedical results f...,http://www.ausstats.abs.gov.au/ausstats/subscr...,10160,verified
3,Vitamin B12,AUS,Australia,national,NaN,both urban and rural,2012,3,2011,9,...,NaN,107.0,"Australian Health Survey: user's guide, 2011-1...",http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,NaN,176.0,Australian Health Survey: biomedical results f...,http://www.ausstats.abs.gov.au/ausstats/subscr...,10160,verified
4,Vitamin B12,AUS,Australia,national,NaN,both urban and rural,2012,3,2011,9,...,NaN,107.0,"Australian Health Survey: user's guide, 2011-1...",http://www.abs.gov.au/ausstats/abs@.nsf/mf/436...,NaN,176.0,Australian Health Survey: biomedical results f...,http://www.ausstats.abs.gov.au/ausstats/subscr...,10160,verified

Checking for missing values:

In [378]:
missing = pd.concat([df135.isnull().sum(), 100 * df135.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                             count           %
Indicator.                       0    0.000000
Reference 1                      0    0.000000
Reference no# 1                  0    0.000000
Season                           0    0.000000
Survey methodology               0    0.000000
Indicator comments               0    0.000000
Method of analysis               0    0.000000
Fasting                          0    0.000000
Sample type                      0    0.000000
Sample collection method         0    0.000000
SurveyId                         0    0.000000
Age from                         0    0.000000
Age unit                         0    0.000000
Survey status                    0    0.000000
Population                       0    0.000000
CountryCode                      0    0.000000
Country                          0    0.000000
Representativeness.              0    0.000000
Area covered                     0    0.000000
Gender                           0    0.000000
Begin month                      0    0.000000
Begin year                       0    0.000000
End month                        0    0.000000
End year                         0    0.000000
Date                             0    0.000000
Indicator unit                  11   10.280374
Link to reference 1             14   13.084112
Age to                          19   17.757009
Sample size                     21   19.626168
Mean                            26   24.299065
Deficiency cut-off              30   28.037383
Prevalence of deficiency        30   28.037383
Link to reference 2             41   38.317757
Reference 2                     41   38.317757
Median                          41   38.317757
Reference no# 2                 41   38.317757
Reference 3                     48   44.859813
Reference no# 3                 48   44.859813
L95CI                           59   55.140187
U95CI                           59   55.140187
Link to reference 3             60   56.074766
General data comments           64   59.813084
SD                              70   65.420561
Prevalence of insufficiency     89   83.177570
Insufficiency cut-off           89   83.177570
Geo mean                        92   85.981308
Old Reference no# 1             93   86.915888
Old Reference no# 2            102   95.327103
SE                             105   98.130841
Representativeness name        107  100.000000
Old Reference no# 3            107  100.000000

In [379]:
df135.Country.unique()

array(['Australia', 'Austria', 'Canada', 'Chile', 'Costa Rica', 'Ecuador',
       'France', 'United Kingdom of Great Britain and Northern',
       'Ireland'], dtype=object)

In [380]:
df135['Begin year'].unique()

array([2011, 2010, 2007, 2009, 2008, 2012, 2006, 1994, 2000])

In [381]:
labels=["Indicator.", "Country", "Date", "Population", "Gender", "Indicator unit", "Prevalence of deficiency", "Mean", "Deficiency cut-off", "Median", "Prevalence of insufficiency", "Insufficiency cut-off", "U95CI", "L95CI"]
df135=df135[labels]

In [382]:
df135.shape
df135.head(15)

,Indicator.,Country,Date,Population,Gender,Indicator unit,Prevalence of deficiency,Mean,Deficiency cut-off,Median,Prevalence of insufficiency,Insufficiency cut-off,U95CI,L95CI
0,Vitamin B12,Australia,2012,Adolescents,All,pmol/L,NaN,372.8,NaN,348.9,NaN,NaN,NaN,NaN
1,Vitamin B12,Australia,2012,Adults,All,pmol/L,2.3,368.6,<145 pmol/L,337.8,14.7,<220 pmol/L,NaN,NaN
2,Vitamin B12,Australia,2012,Adults,All,pmol/L,NaN,376.0,NaN,348.0,NaN,NaN,NaN,NaN
3,Vitamin B12,Australia,2012,Adults,All,pmol/L,NaN,375.0,NaN,351.0,NaN,NaN,NaN,NaN
4,Vitamin B12,Australia,2012,Adults,All,pmol/L,NaN,374.7,NaN,343.0,NaN,NaN,NaN,NaN
5,Vitamin B12,Australia,2012,Adults,All,pmol/L,NaN,373.2,NaN,349.0,NaN,NaN,NaN,NaN
6,Vitamin B12,Australia,2012,Adults,All,pmol/L,NaN,369.1,NaN,340.0,NaN,NaN,NaN,NaN
7,Vitamin B12,Australia,2012,Adults,Female,pmol/L,2.3,371.0,<145 pmol/L,337.0,15.0,<220 pmol/L,NaN,NaN
8,Vitamin B12,Australia,2012,Elderly,All,pmol/L,NaN,345.9,NaN,305.0,NaN,NaN,NaN,NaN
9,Vitamin B12,Australia,2012,Elderly,All,pmol/L,NaN,341.9,NaN,304.0,NaN,NaN,NaN,NaN
10,Vitamin B12,Australia,2012,Men,Male,pmol/L,2.4,366.1,<145 pmol/L,338.0,14.3,<220 pmol/L,NaN,NaN
11,Vitamin B12,Austria,2012,Adolescents,Female,pmol/L,NaN,363.3,NaN,NaN,NaN,NaN,402.5,324.2
12,Vitamin B12,Austria,2012,Adolescents,Female,pmol/L,NaN,369.7,NaN,NaN,NaN,NaN,428.2,311.1
13,Vitamin B12,Austria,2012,Adolescents,Male,pmol/L,NaN,363.5,NaN,NaN,NaN,NaN,401.2,325.9
14,Vitamin B12,Austria,2012,Adolescents,Male,pmol/L,NaN,354.5,NaN,NaN,NaN,NaN,413.3,295.8

In [383]:
(df135["Country"] + ", " + df135["Population"]).value_counts()

Ecuador, Adults                                          12
United Kingdom of Great Britain and Northern, Elderly     9
Ireland, Adults                                           8
Chile, Elderly                                            7
Australia, Adults                                         7
Canada, Elderly                                           6
Ecuador, Adolescents                                      6
Costa Rica, Elderly                                       6
United Kingdom of Great Britain and Northern, Men         5
Canada, Adolescents                                       4
Costa Rica, Men                                           4
Austria, Men                                              4
Austria, Adolescents                                      4
Costa Rica, Women                                         4
Canada, Adults                                            4
France, Adults                                            3
Ireland, Elderly                                          3
Austria, Women                                            2
Canada, Men                                               2
Austria, Elderly                                          2
Australia, Elderly                                        2
Australia, Adolescents                                    1
Australia, Men                                            1
Canada, Women                                             1
dtype: int64

In [384]:
df135.Country.value_counts()

Ecuador                                         18
Canada                                          17
Costa Rica                                      14
United Kingdom of Great Britain and Northern    14
Austria                                         12
Ireland                                         11
Australia                                       11
Chile                                            7
France                                           3
Name: Country, dtype: int64

In [385]:
df136.info()
df136.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 51 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Indicator.                        37 non-null     object
 1   CountryCode                       37 non-null     object
 2   Country                           37 non-null     object
 3   Representativeness.               37 non-null     object
 4   Representativeness name           0 non-null      float64
 5   Area covered                      37 non-null     object
 6   Date                              37 non-null     int64
 7   Begin month                       37 non-null     int64
 8   Begin year                        37 non-null     int64
 9   End month                         37 non-null     int64
 10  End year                          37 non-null     int64
 11  Population                        37 non-null     object
 12  Gender                            37 non-null     object
 13  Age unit                          37 non-null     object
 14  Age from                          37 non-null     int64
 15  Age to                            32 non-null     float64
 16  Sample size                       27 non-null     float64
 17  Indicator unit                    34 non-null     object
 18  Mean                              34 non-null     float64
 19  Geo mean                          0 non-null      float64
 20  Median                            14 non-null     float64
 21  SD                                22 non-null     float64
 22  SE                                0 non-null      float64
 23  L95CI                             20 non-null     float64
 24  U95CI                             20 non-null     float64
 25  Low vitamin C cut-off             17 non-null     object
 26  Prevalence of low vitamin C       17 non-null     float64
 27  Marginal vitamin C cut-off        0 non-null      float64
 28  Prevalence of marginal vitamin C  0 non-null      float64
 29  Sample collection method          37 non-null     object
 30  Sample type                       37 non-null     object
 31  Fasting                           37 non-null     object
 32  Method of analysis                37 non-null     object
 33  General data comments             7 non-null      object
 34  Indicator comments                37 non-null     object
 35  Survey methodology                37 non-null     object
 36  Season                            37 non-null     object
 37  Old Reference no# 1               25 non-null     float64
 38  Reference no# 1                   37 non-null     int64
 39  Reference 1                       37 non-null     object
 40  Link to reference 1               37 non-null     object
 41  Old Reference no# 2               16 non-null     float64
 42  Reference no# 2                   28 non-null     float64
 43  Reference 2                       28 non-null     object
 44  Link to reference 2               17 non-null     object
 45  Old Reference no# 3               11 non-null     float64
 46  Reference no# 3                   28 non-null     float64
 47  Reference 3                       28 non-null     object
 48  Link to reference 3               16 non-null     object
 49  SurveyId                          37 non-null     int64
 50  Survey status                     37 non-null     object
dtypes: float64(18), int64(8), object(25)
memory usage: 14.9+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Vitamin C,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
1,Vitamin C,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
2,Vitamin C,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
3,Vitamin C,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
4,Vitamin C,AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified

Checking for missing values:

In [386]:
missing = pd.concat([df136.isnull().sum(), 100 * df136.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                                  count           %
Indicator.                            0    0.000000
Link to reference 1                   0    0.000000
Reference 1                           0    0.000000
Reference no# 1                       0    0.000000
Season                                0    0.000000
Survey methodology                    0    0.000000
Indicator comments                    0    0.000000
Method of analysis                    0    0.000000
Fasting                               0    0.000000
Sample type                           0    0.000000
Sample collection method              0    0.000000
SurveyId                              0    0.000000
Age from                              0    0.000000
Survey status                         0    0.000000
Gender                                0    0.000000
CountryCode                           0    0.000000
Country                               0    0.000000
Representativeness.                   0    0.000000
Area covered                          0    0.000000
Date                                  0    0.000000
Age unit                              0    0.000000
Begin year                            0    0.000000
End month                             0    0.000000
End year                              0    0.000000
Population                            0    0.000000
Begin month                           0    0.000000
Indicator unit                        3    8.108108
Mean                                  3    8.108108
Age to                                5   13.513514
Reference 3                           9   24.324324
Reference no# 3                       9   24.324324
Reference 2                           9   24.324324
Reference no# 2                       9   24.324324
Sample size                          10   27.027027
Old Reference no# 1                  12   32.432432
SD                                   15   40.540541
L95CI                                17   45.945946
U95CI                                17   45.945946
Link to reference 2                  20   54.054054
Prevalence of low vitamin C          20   54.054054
Low vitamin C cut-off                20   54.054054
Old Reference no# 2                  21   56.756757
Link to reference 3                  21   56.756757
Median                               23   62.162162
Old Reference no# 3                  26   70.270270
General data comments                30   81.081081
Geo mean                             37  100.000000
SE                                   37  100.000000
Prevalence of marginal vitamin C     37  100.000000
Marginal vitamin C cut-off           37  100.000000
Representativeness name              37  100.000000

In [387]:
df136.Country.unique()

array(['Austria', 'France',
       'United Kingdom of Great Britain and Northern'], dtype=object)

In [388]:
df136['Begin year'].unique()

array([2010, 1994, 2000])

Another indicator with too little data to use for this project.

In [389]:
df137.info()
df137.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 52 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Indicator.                         35 non-null     object
 1   CountryCode                        35 non-null     object
 2   Country                            35 non-null     object
 3   Representativeness.                35 non-null     object
 4   Representativeness name            0 non-null      float64
 5   Area covered                       35 non-null     object
 6   Date                               35 non-null     int64
 7   Begin month                        35 non-null     int64
 8   Begin year                         35 non-null     int64
 9   End month                          35 non-null     int64
 10  End year                           35 non-null     int64
 11  Population                         35 non-null     object
 12  Gender                             35 non-null     object
 13  Age unit                           35 non-null     object
 14  Age from                           35 non-null     int64
 15  Age to                             30 non-null     float64
 16  Sample size                        25 non-null     float64
 17  Indicator unit                     32 non-null     object
 18  Mean                               32 non-null     float64
 19  Geo mean                           0 non-null      float64
 20  Median                             14 non-null     float64
 21  SD                                 22 non-null     float64
 22  SE                                 0 non-null      float64
 23  L95CI                              18 non-null     float64
 24  U95CI                              18 non-null     float64
 25  Deficiency cut-off                 17 non-null     object
 26  Prevalence of deficiency           17 non-null     float64
 27  Marginal deficiency cut-off        0 non-null      float64
 28  Prevalence of marginal deficiency  0 non-null      float64
 29  Sample collection method           35 non-null     object
 30  Sample type                        35 non-null     object
 31  Fasting                            35 non-null     object
 32  Method of analysis                 35 non-null     object
 33  Data adjusted for                  35 non-null     object
 34  General data comments              16 non-null     object
 35  Indicator comments                 30 non-null     object
 36  Survey methodology                 35 non-null     object
 37  Season                             35 non-null     object
 38  Old Reference no# 1                25 non-null     float64
 39  Reference no# 1                    35 non-null     int64
 40  Reference 1                        35 non-null     object
 41  Link to reference 1                35 non-null     object
 42  Old Reference no# 2                16 non-null     float64
 43  Reference no# 2                    26 non-null     float64
 44  Reference 2                        26 non-null     object
 45  Link to reference 2                15 non-null     object
 46  Old Reference no# 3                11 non-null     float64
 47  Reference no# 3                    26 non-null     float64
 48  Reference 3                        26 non-null     object
 49  Link to reference 3                16 non-null     object
 50  SurveyId                           35 non-null     int64
 51  Survey status                      35 non-null     object
dtypes: float64(18), int64(8), object(26)
memory usage: 14.3+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Vitamin E (alpha-tocopherol),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
1,Vitamin E (alpha-tocopherol),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
2,Vitamin E (alpha-tocopherol),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
3,Vitamin E (alpha-tocopherol),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
4,Vitamin E (alpha-tocopherol),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified

Checking for missing values:

In [390]:
missing = pd.concat([df137.isnull().sum(), 100 * df137.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                                   count           %
Indicator.                             0    0.000000
Link to reference 1                    0    0.000000
Reference 1                            0    0.000000
Reference no# 1                        0    0.000000
Season                                 0    0.000000
Survey methodology                     0    0.000000
Data adjusted for                      0    0.000000
Method of analysis                     0    0.000000
Fasting                                0    0.000000
Sample type                            0    0.000000
Sample collection method               0    0.000000
SurveyId                               0    0.000000
Age from                               0    0.000000
Survey status                          0    0.000000
Gender                                 0    0.000000
CountryCode                            0    0.000000
Country                                0    0.000000
Representativeness.                    0    0.000000
Area covered                           0    0.000000
Date                                   0    0.000000
Age unit                               0    0.000000
Begin year                             0    0.000000
End month                              0    0.000000
End year                               0    0.000000
Population                             0    0.000000
Begin month                            0    0.000000
Mean                                   3    8.571429
Indicator unit                         3    8.571429
Age to                                 5   14.285714
Indicator comments                     5   14.285714
Reference 3                            9   25.714286
Reference no# 3                        9   25.714286
Reference 2                            9   25.714286
Reference no# 2                        9   25.714286
Old Reference no# 1                   10   28.571429
Sample size                           10   28.571429
SD                                    13   37.142857
L95CI                                 17   48.571429
U95CI                                 17   48.571429
Prevalence of deficiency              18   51.428571
Deficiency cut-off                    18   51.428571
General data comments                 19   54.285714
Old Reference no# 2                   19   54.285714
Link to reference 3                   19   54.285714
Link to reference 2                   20   57.142857
Median                                21   60.000000
Old Reference no# 3                   24   68.571429
Geo mean                              35  100.000000
SE                                    35  100.000000
Prevalence of marginal deficiency     35  100.000000
Marginal deficiency cut-off           35  100.000000
Representativeness name               35  100.000000

In [391]:
df137.Country.unique()

array(['Austria', 'France',
       'United Kingdom of Great Britain and Northern'], dtype=object)

In [392]:
df137['Begin year'].unique()

array([2010, 1994, 2000])

Another indicator with too little data to use for this project.

In [393]:
df138.info()
df138.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 50 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Indicator.                         24 non-null     object
 1   CountryCode                        24 non-null     object
 2   Country                            24 non-null     object
 3   Representativeness.                24 non-null     object
 4   Representativeness name            0 non-null      float64
 5   Area covered                       24 non-null     object
 6   Date                               24 non-null     int64
 7   Begin month                        24 non-null     int64
 8   Begin year                         24 non-null     int64
 9   End month                          24 non-null     int64
 10  End year                           24 non-null     int64
 11  Population                         24 non-null     object
 12  Gender                             24 non-null     object
 13  Age unit                           24 non-null     object
 14  Age from                           24 non-null     int64
 15  Age to                             19 non-null     float64
 16  Sample size                        14 non-null     float64
 17  Indicator unit                     24 non-null     object
 18  Mean                               24 non-null     float64
 19  Geo mean                           0 non-null      float64
 20  Median                             14 non-null     float64
 21  SD                                 14 non-null     float64
 22  SE                                 0 non-null      float64
 23  L95CI                              10 non-null     float64
 24  U95CI                              10 non-null     float64
 25  Deficiency cut-off                 14 non-null     object
 26  Prevalence of deficiency           14 non-null     float64
 27  Marginal deficiency cut-off        0 non-null      float64
 28  Prevalence of marginal deficiency  0 non-null      float64
 29  Sample collection method           24 non-null     object
 30  Sample type                        24 non-null     object
 31  Fasting                            24 non-null     object
 32  Method of analysis                 24 non-null     object
 33  Data adjusted for                  24 non-null     object
 34  General data comments              5 non-null      object
 35  Indicator comments                 24 non-null     object
 36  Survey methodology                 24 non-null     object
 37  Season                             24 non-null     object
 38  Old Reference no# 1                14 non-null     float64
 39  Reference no# 1                    24 non-null     int64
 40  Reference 1                        24 non-null     object
 41  Link to reference 1                24 non-null     object
 42  Old Reference no# 2                5 non-null      float64
 43  Reference no# 2                    15 non-null     float64
 44  Reference 2                        15 non-null     object
 45  Link to reference 2                15 non-null     object
 46  Old Reference no# 3                0 non-null      float64
 47  Reference no# 3                    15 non-null     float64
 48  Reference 3                        15 non-null     object
 49  Link to reference 3                5 non-null      object
dtypes: float64(18), int64(7), object(25)
memory usage: 9.5+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Reference 1,Link to reference 1,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3
0,Vitamin E (gamma-tocopherol),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,Institut für ErnährungswissenschaftenUniversit...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN
1,Vitamin E (gamma-tocopherol),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,Institut für ErnährungswissenschaftenUniversit...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN
2,Vitamin E (gamma-tocopherol),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,Institut für ErnährungswissenschaftenUniversit...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN
3,Vitamin E (gamma-tocopherol),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,Institut für ErnährungswissenschaftenUniversit...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN
4,Vitamin E (gamma-tocopherol),AUT,Austria,national,NaN,both urban and rural,2012,8,2010,2,...,Institut für ErnährungswissenschaftenUniversit...,http://www.bmgf.gv.at/cms/home/attachments/4/5...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN

Checking for missing values:

In [394]:
missing = pd.concat([df138.isnull().sum(), 100 * df138.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                                   count           %
Indicator.                             0    0.000000
Sample collection method               0    0.000000
Sample type                            0    0.000000
Fasting                                0    0.000000
Method of analysis                     0    0.000000
Data adjusted for                      0    0.000000
Reference no# 1                        0    0.000000
Season                                 0    0.000000
Mean                                   0    0.000000
Indicator unit                         0    0.000000
Indicator comments                     0    0.000000
Age from                               0    0.000000
Reference 1                            0    0.000000
Age unit                               0    0.000000
Population                             0    0.000000
End year                               0    0.000000
End month                              0    0.000000
Begin year                             0    0.000000
Begin month                            0    0.000000
Date                                   0    0.000000
Area covered                           0    0.000000
Survey methodology                     0    0.000000
Representativeness.                    0    0.000000
Country                                0    0.000000
CountryCode                            0    0.000000
Gender                                 0    0.000000
Link to reference 1                    0    0.000000
Age to                                 5   20.833333
Link to reference 2                    9   37.500000
Reference 3                            9   37.500000
Reference no# 2                        9   37.500000
Reference 2                            9   37.500000
Reference no# 3                        9   37.500000
Deficiency cut-off                    10   41.666667
SD                                    10   41.666667
Median                                10   41.666667
Sample size                           10   41.666667
Prevalence of deficiency              10   41.666667
Old Reference no# 1                   10   41.666667
U95CI                                 14   58.333333
L95CI                                 14   58.333333
Old Reference no# 2                   19   79.166667
General data comments                 19   79.166667
Link to reference 3                   19   79.166667
Prevalence of marginal deficiency     24  100.000000
Marginal deficiency cut-off           24  100.000000
SE                                    24  100.000000
Geo mean                              24  100.000000
Old Reference no# 3                   24  100.000000
Representativeness name               24  100.000000

In [395]:
df138.Country.unique()

array(['Austria', 'United Kingdom of Great Britain and Northern'],
      dtype=object)

In [396]:
df138['Begin year'].unique()

array([2010, 1994, 2000])

Another indicator with too little data to use for this project.

In [397]:
df139.info()
df139.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 54 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Indicator.                21 non-null     object
 1   CountryCode               21 non-null     object
 2   Country                   21 non-null     object
 3   Representativeness.       21 non-null     object
 4   Representativeness name   0 non-null      float64
 5   Area covered              21 non-null     object
 6   Date                      21 non-null     int64
 7   Begin month               21 non-null     int64
 8   Begin year                21 non-null     int64
 9   End month                 21 non-null     int64
 10  End year                  21 non-null     int64
 11  Population                21 non-null     object
 12  Gender                    21 non-null     object
 13  Age unit                  21 non-null     object
 14  Age from                  21 non-null     int64
 15  Age to                    18 non-null     float64
 16  Sample size               20 non-null     float64
 17  Indicator unit            0 non-null      float64
 18  Mean                      0 non-null      float64
 19  Geo mean                  0 non-null      float64
 20  Median                    0 non-null      float64
 21  SD                        0 non-null      float64
 22  SE                        0 non-null      float64
 23  L95CI                     0 non-null      float64
 24  U95CI                     0 non-null      float64
 25  Current XN prevalence     8 non-null      float64
 26  Previous XN prevalence    3 non-null      float64
 27  X1A prevalence            10 non-null     float64
 28  X1B prevalence            18 non-null     float64
 29  X2 prevalence             8 non-null      float64
 30  X3A prevalence            6 non-null      float64
 31  X3B prevalence            6 non-null      float64
 32  XS prevalence             0 non-null      float64
 33  Sample collection method  21 non-null     object
 34  Method of analysis        21 non-null     object
 35  Data adjusted for         21 non-null     object
 36  General data comments     7 non-null      object
 37  Indicator comments        21 non-null     object
 38  Survey methodology        21 non-null     object
 39  Season                    21 non-null     object
 40  Old Reference no# 1       20 non-null     float64
 41  Reference no# 1           21 non-null     int64
 42  Reference 1               21 non-null     object
 43  Link to reference 1       3 non-null      object
 44  Old Reference no# 2       0 non-null      float64
 45  Reference no# 2           0 non-null      float64
 46  Reference 2               0 non-null      float64
 47  Link to reference 2       0 non-null      float64
 48  Old Reference no# 3       0 non-null      float64
 49  Reference no# 3           0 non-null      float64
 50  Reference 3               0 non-null      float64
 51  Link to reference 3       0 non-null      float64
 52  SurveyId                  21 non-null     int64
 53  Survey status             21 non-null     object
dtypes: float64(28), int64(8), object(18)
memory usage: 9.0+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Xerophthalmia,NPL,Nepal,national,NaN,both urban and rural,2016,4,2016,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11063,verified
1,Xerophthalmia,CMR,Cameroon,national,NaN,both urban and rural,2004,2,2004,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10091,verified
2,Xerophthalmia,ARM,Armenia,national,NaN,both urban and rural,2000,10,2000,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10159,verified
3,Xerophthalmia,LAO,Lao People's Democratic Republic,national,NaN,both urban and rural,2000,3,2000,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10216,verified
4,Xerophthalmia,LAO,Lao People's Democratic Republic,national,NaN,both urban and rural,2000,3,2000,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10216,verified

Checking for missing values:

In [398]:
missing = pd.concat([df139.isnull().sum(), 100 * df139.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                          count           %
Indicator.                    0    0.000000
Reference 1                   0    0.000000
Reference no# 1               0    0.000000
Season                        0    0.000000
Survey methodology            0    0.000000
Indicator comments            0    0.000000
Data adjusted for             0    0.000000
Method of analysis            0    0.000000
Sample collection method      0    0.000000
SurveyId                      0    0.000000
Age from                      0    0.000000
Age unit                      0    0.000000
Survey status                 0    0.000000
Population                    0    0.000000
CountryCode                   0    0.000000
Country                       0    0.000000
Representativeness.           0    0.000000
Area covered                  0    0.000000
Date                          0    0.000000
Begin month                   0    0.000000
Gender                        0    0.000000
End month                     0    0.000000
Begin year                    0    0.000000
End year                      0    0.000000
Old Reference no# 1           1    4.761905
Sample size                   1    4.761905
Age to                        3   14.285714
X1B prevalence                3   14.285714
X1A prevalence               11   52.380952
Current XN prevalence        13   61.904762
X2 prevalence                13   61.904762
General data comments        14   66.666667
X3A prevalence               15   71.428571
X3B prevalence               15   71.428571
Previous XN prevalence       18   85.714286
Link to reference 1          18   85.714286
Link to reference 2          21  100.000000
Reference no# 2              21  100.000000
Old Reference no# 2          21  100.000000
Reference no# 3              21  100.000000
Reference 3                  21  100.000000
Link to reference 3          21  100.000000
Reference 2                  21  100.000000
Old Reference no# 3          21  100.000000
L95CI                        21  100.000000
Indicator unit               21  100.000000
Mean                         21  100.000000
Geo mean                     21  100.000000
Median                       21  100.000000
XS prevalence                21  100.000000
SD                           21  100.000000
U95CI                        21  100.000000
SE                           21  100.000000
Representativeness name      21  100.000000

In [399]:
df139.Country.unique()

array(['Nepal', 'Cameroon', 'Armenia', "Lao People's Democratic Republic",
       'Thailand'], dtype=object)

In [400]:
df139['Begin year'].unique()

array([2016, 2004, 2000, 1995])

Another indicator with too little data to use for this project.

In [401]:
df140.info()
df140.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 50 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Indicator.                76 non-null     object
 1   CountryCode               76 non-null     object
 2   Country                   76 non-null     object
 3   Representativeness.       76 non-null     object
 4   Representativeness name   0 non-null      float64
 5   Area covered              76 non-null     object
 6   Date                      76 non-null     int64
 7   Begin month               69 non-null     float64
 8   Begin year                69 non-null     float64
 9   End month                 69 non-null     float64
 10  End year                  76 non-null     int64
 11  Population                76 non-null     object
 12  Gender                    76 non-null     object
 13  Age unit                  76 non-null     object
 14  Age from                  76 non-null     int64
 15  Age to                    65 non-null     float64
 16  Sample size               74 non-null     float64
 17  Indicator unit            65 non-null     object
 18  Mean                      61 non-null     float64
 19  Geo mean                  1 non-null      float64
 20  Median                    20 non-null     float64
 21  SD                        34 non-null     float64
 22  SE                        26 non-null     float64
 23  L95CI                     32 non-null     float64
 24  U95CI                     32 non-null     float64
 25  Deficiency cut-off        68 non-null     object
 26  Prevalence of deficiency  68 non-null     float64
 27  Sample collection method  76 non-null     object
 28  Sample type               76 non-null     object
 29  Fasting                   76 non-null     object
 30  Method of analysis        76 non-null     object
 31  Data adjusted for         76 non-null     object
 32  General data comments     45 non-null     object
 33  Indicator comments        76 non-null     object
 34  Survey methodology        76 non-null     object
 35  Season                    76 non-null     object
 36  Old Reference no# 1       10 non-null     float64
 37  Reference no# 1           76 non-null     int64
 38  Reference 1               76 non-null     object
 39  Link to reference 1       67 non-null     object
 40  Old Reference no# 2       0 non-null      float64
 41  Reference no# 2           37 non-null     float64
 42  Reference 2               37 non-null     object
 43  Link to reference 2       37 non-null     object
 44  Old Reference no# 3       0 non-null      float64
 45  Reference no# 3           37 non-null     float64
 46  Reference 3               37 non-null     object
 47  Link to reference 3       24 non-null     object
 48  SurveyId                  76 non-null     int64
 49  Survey status             76 non-null     object
dtypes: float64(19), int64(5), object(26)
memory usage: 29.8+ KB

,Indicator.,CountryCode,Country,Representativeness.,Representativeness name,Area covered,Date,Begin month,Begin year,End month,...,Old Reference no# 2,Reference no# 2,Reference 2,Link to reference 2,Old Reference no# 3,Reference no# 3,Reference 3,Link to reference 3,SurveyId,Survey status
0,Zinc (plasma or serum),AUT,Austria,national,NaN,both urban and rural,2012,8.0,2010.0,2.0,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
1,Zinc (plasma or serum),AUT,Austria,national,NaN,both urban and rural,2012,8.0,2010.0,2.0,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
2,Zinc (plasma or serum),AUT,Austria,national,NaN,both urban and rural,2012,8.0,2010.0,2.0,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
3,Zinc (plasma or serum),AUT,Austria,national,NaN,both urban and rural,2012,8.0,2010.0,2.0,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified
4,Zinc (plasma or serum),AUT,Austria,national,NaN,both urban and rural,2012,8.0,2010.0,2.0,...,NaN,1244.0,"Elmadfa I, L Meyer A, Kuen T, Wagner K, Hasene...",https://econtent.hogrefe.com/doi/abs/10.1024/0...,NaN,1399.0,"Elmadfa I, Meyer AL, Wottawa D, Wagner K and H...",NaN,10872,verified

Checking for missing values:

In [402]:
missing = pd.concat([df140.isnull().sum(), 100 * df140.isnull().mean()], axis=1)
missing.columns=['count','%']
missing.sort_values(by='count',ascending=True)

                          count           %
Indicator.                    0    0.000000
Reference 1                   0    0.000000
Reference no# 1               0    0.000000
Season                        0    0.000000
Survey methodology            0    0.000000
Indicator comments            0    0.000000
Data adjusted for             0    0.000000
Method of analysis            0    0.000000
Fasting                       0    0.000000
Sample type                   0    0.000000
Sample collection method      0    0.000000
SurveyId                      0    0.000000
Age from                      0    0.000000
Survey status                 0    0.000000
Gender                        0    0.000000
CountryCode                   0    0.000000
Country                       0    0.000000
Representativeness.           0    0.000000
Area covered                  0    0.000000
Age unit                      0    0.000000
End year                      0    0.000000
Population                    0    0.000000
Date                          0    0.000000
Sample size                   2    2.631579
End month                     7    9.210526
Begin year                    7    9.210526
Begin month                   7    9.210526
Deficiency cut-off            8   10.526316
Prevalence of deficiency      8   10.526316
Link to reference 1           9   11.842105
Age to                       11   14.473684
Indicator unit               11   14.473684
Mean                         15   19.736842
General data comments        31   40.789474
Reference no# 3              39   51.315789
Reference 2                  39   51.315789
Reference no# 2              39   51.315789
Reference 3                  39   51.315789
Link to reference 2          39   51.315789
SD                           42   55.263158
L95CI                        44   57.894737
U95CI                        44   57.894737
SE                           50   65.789474
Link to reference 3          52   68.421053
Median                       56   73.684211
Old Reference no# 1          66   86.842105
Geo mean                     75   98.684211
Representativeness name      76  100.000000
Old Reference no# 3          76  100.000000
Old Reference no# 2          76  100.000000

In [403]:
df140.Country.unique()

array(['Austria', 'Ecuador',
       'United Kingdom of Great Britain and Northern', 'Kenya', 'Kuwait',
       'Malawi', 'New Zealand', 'Philippines'], dtype=object)

In [404]:
df140['Begin year'].unique()

array([2010., 2012., 1994., 1999., 2011.,   nan, 2015., 2002., 2008.])

In [405]:
labels=["Indicator.", "Country", "Date", "Population", "Gender", "Indicator unit", "Prevalence of deficiency", "Mean", "Deficiency cut-off", "Median", "U95CI", "L95CI"]
df140=df140[labels]

In [406]:
df140.shape
df140.head(15)

,Indicator.,Country,Date,Population,Gender,Indicator unit,Prevalence of deficiency,Mean,Deficiency cut-off,Median,U95CI,L95CI
0,Zinc (plasma or serum),Austria,2012,Adolescents,Female,µmol/L,19.6,12.8,<10.7 µmol/L,NaN,NaN,NaN
1,Zinc (plasma or serum),Austria,2012,Adolescents,Female,µmol/L,38.9,11.2,<10.7 µmol/L,NaN,NaN,NaN
2,Zinc (plasma or serum),Austria,2012,Adolescents,Male,µmol/L,48.1,11.6,<11.3 µmol/L,NaN,NaN,NaN
3,Zinc (plasma or serum),Austria,2012,Adolescents,Male,µmol/L,42.9,11.3,<11.3 µmol/L,NaN,NaN,NaN
4,Zinc (plasma or serum),Austria,2012,Elderly,All,µmol/L,NaN,12.2,NaN,NaN,13.2,11.2
5,Zinc (plasma or serum),Austria,2012,Elderly,Female,µmol/L,33.3,12.2,<10.7 µmol/L,NaN,NaN,NaN
6,Zinc (plasma or serum),Austria,2012,Elderly,Male,µmol/L,27.6,13.0,<11.3 µmol/L,NaN,NaN,NaN
7,Zinc (plasma or serum),Austria,2012,Men,Male,µmol/L,10.7,14.1,<11.3 µmol/L,NaN,NaN,NaN
8,Zinc (plasma or serum),Austria,2012,Men,Male,µmol/L,13.4,14.4,<11.3 µmol/L,NaN,NaN,NaN
9,Zinc (plasma or serum),Austria,2012,Men,Male,µmol/L,13.4,14.8,<11.3 µmol/L,NaN,NaN,NaN
10,Zinc (plasma or serum),Austria,2012,Men,Male,µmol/L,17.0,13.6,<11.3 µmol/L,NaN,NaN,NaN
11,Zinc (plasma or serum),Austria,2012,Women,Female,µmol/L,18.1,13.1,<10.7 µmol/L,NaN,NaN,NaN
12,Zinc (plasma or serum),Austria,2012,Women,Female,µmol/L,27.5,12.3,<10.7 µmol/L,NaN,NaN,NaN
13,Zinc (plasma or serum),Ecuador,2012,Adolescents,All,NaN,51.4,NaN,<10.7 µmol/L,NaN,NaN,NaN
14,Zinc (plasma or serum),Ecuador,2012,Adolescents,All,NaN,51.3,NaN,<10.7 µmol/L,NaN,NaN,NaN

In [407]:
(df140["Country"] + ", " + df140["Population"]).value_counts()

Philippines, Elderly                                     9
Ecuador, Adolescents                                     9
United Kingdom of Great Britain and Northern, Elderly    9
Philippines, Adults                                      6
Philippines, Men                                         5
Malawi, Men                                              5
Kuwait, Men                                              4
Kenya, Men                                               4
Austria, Adolescents                                     4
Austria, Men                                             4
Austria, Elderly                                         3
Malawi, Adolescents                                      3
Philippines, Adolescents                                 3
Austria, Women                                           2
Kuwait, Elderly                                          2
New Zealand, Adolescents                                 2
Philippines, Women                                       1
Kuwait, Adults                                           1
dtype: int64

In [408]:
df140.Country.value_counts()

Philippines                                     24
Austria                                         13
Ecuador                                          9
United Kingdom of Great Britain and Northern     9
Malawi                                           8
Kuwait                                           7
Kenya                                            4
New Zealand                                      2
Name: Country, dtype: int64

### Micronutrient Status Data Availability Summary

Indicators with data for more than five countries:
<br>df114 25-Hydroxyvitamin D
<br>df121 ferritin
<br>df122 folate (plasma or serum)
<br>df123 folate (red blood cell)
<br>df125 haemoglobin
<br>df127 iodine
<br>df129 iron-deficiency anaemia
<br>df135 vitamin B12
<br>df140 zinc (plasma or serum)

Indicators with data for more than three years:
<br>df114 25-Hydroxyvitamin D
<br>df121 ferritin
<br>df122 folate (plasma or serum)
<br>df123 folate (red blood cell)
<br>df125 haemoglobin
<br>df127 iodine
<br>df129 iron-deficiency anaemia 
<br>df131 mean corpuscular volume (MCV)
<br>df132 retinol binding protein
<br>df135 vitamin B12
<br>df139 xerophthalmia
<br>df140 zinc (plasma or serum)

Indicators with data for more than five countries and more than three years:
<br>df114 25-Hydroxyvitamin D
<br>df121 ferritin
<br>df122 folate (plasma or serum)
<br>df123 folate (red blood cell)
<br>df125 haemoglobin
<br>df127 iodine
<br>df129 iron-deficiency anaemia
<br>df135 vitamin B12
<br>df140 zinc (plasma or serum)

Upon closer examination of the above nine indicators, the information is not complete enough to use except potentially in the case of haemoglobin. For example, some indicators will have information for one subpopulation of a country (e.g. Men or Elderly) but not others (e.g. Women, Adolescents). As such, micronutrient status indicators will not be used.